### ISSUE TITLE
[ENHANCEMENT] Add support for LLM-assisted ranking metrics to `experimental` sub-module

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1008]
- [x] add utility function for relevance classifications
- [x] add utility function for computing precision@k

_Originally posted by @axiomofjoy in https://github.com/Arize-ai/phoenix/issues/815#issuecomment-1654247301_

**Comment by mikeldking** [comment]
@axiomofjoy don't forget you will need a publish for this to work
