### ISSUE TITLE
[trace] llamaIndex debug callback handler

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1011]
@mikeldking 

I think how that we have callbacks it's more important to just be able to log out the data and see it as it runs.

Create a callback handler under the `llama_index` integration directory called `DebugCallback` that can be mounted on the callback manager so that we can instropect the data that is available during each step.

**Comment by mikeldking** [comment]
@axiomofjoy I'm gonna switch this to a debug callback handler to start so that we can just attach these as callbacks and print out the progress.

**Comment by RogerHYang** [comment]
Why can't we use the Python debugger for this (which is what I have been doing myself)? Since we can't guaranteed that all payloads objects can be printed, the usefulness of printing is limited in the general case.

**Comment by RogerHYang** [comment]
Note that LlamaIndex also has a debug [handler](https://github.com/run-llama/llama_index/blob/8db57ff47d74a6838470ff919766b9fffa94f174/llama_index/callbacks/llama_debug.py#L15), which just prints out the trace map.
```
**********
Trace: query
    |_agent_step ->  1.957762 seconds
      |_llm ->  1.248495 seconds
      |_function_call ->  0.000384 seconds
      |_llm ->  0.706331 seconds
**********
```

**Comment by anticorrelator** [comment]
@RogerHYang if we don't think this is useful I think it's fine to close, which is what @mikeldking mentioned earlier too. Last we spoke we ended at: a wall of event text can be both convenient and helpful in some situations hence the PR

**Comment by RogerHYang** [comment]
> @RogerHYang if we don't think this is useful I think it's fine to close, which is what @mikeldking mentioned earlier too. Last we spoke we ended at: a wall of event text can be both convenient and helpful in some situations hence the PR

OK i see. We can also print just the keys and `repr(value)` of the payload to reduce the amount of text. But ultimately there's the downside of spending too much energy on prettifying text when a debugger is what everyone would graduate to sooner or later.
