### ISSUE TITLE
[ENHANCEMENT] Add support for arbitrary edge metadata + metrics

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1012]
We currently support "relevance" as a property on edges. There are additional fields that belong on the edges, such as LLM-assisted relevance classifications. In our tutorial notebooks, that data is currently added as tags "openai_relevance_0" and "openai_relevance_1", but this not a clean solution and won't generalize to the case where the number of retrieved documents varies by query.

_Originally posted by @axiomofjoy in https://github.com/Arize-ai/phoenix/issues/815#issuecomment-1654550561_

**Comment by mikeldking** [comment]
punt
