### ISSUE TITLE
[ENHANCEMENT] Highlight point in the point cloud when I hover over the card in the cluster details panel.

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1014]
When I hover over a card in the cluster details panel, I would like for the point to be highlighted in the UI (perhaps by changing the color of the white cloud surrounding the point) and for lines to retrieved context to be drawn. Without this, it becomes difficult to demo the retrieved document lines, and it's difficult to locate individual points in the point cloud.

<img width="1460" alt="Screenshot 2023-07-27 at 2 12 50 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/1e429710-001b-46ea-9547-32be38b14e55">

_Originally posted by @axiomofjoy in https://github.com/Arize-ai/phoenix/issues/815#issuecomment-1654583397_

**Comment by mikeldking** [comment]
This is completed via #814
