### ISSUE TITLE
[BUG] UI crashes when selecting area of high drift

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1020]
**Describe the bug**
UI crashes when running credit fraud detection notebook
`Cannot read properties of undefined (reading 'join')`
No stacktrace in the notebook itself

![select_area_of_high_drift](https://github.com/Arize-ai/phoenix/assets/15664869/b927cd16-b76c-4b61-9dfa-a4d45d4a0e8b)

**To Reproduce**
- Run the credit card fraud detection notebook
- Go to the embeddings tab
- Select a time of high drift
- The UI typically crashes soon after

**Expected behavior**
I expect the application to run without crashing

**Screenshots**
<img width="669" alt="Screenshot 2023-07-27 at 11 06 14 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/57aed7ae-d299-4c24-a12a-40375a6a39a7">

**Environment (please complete the following information):**
 - OS: Linux
 - Notebook Runtime: Colab
 - Browser: Chrome
 - Version: 0.0.30

**Comment by mikeldking** [comment]
@axiomofjoy I cannot repro this in colab. I wonder if you ran this with a local build.

https://colab.research.google.com/drive/1dz2IjVOZoY_pCATevis-LckOIXj_lDZr#scrollTo=nCsJ-cZ3wGDT

**Comment by axiomofjoy** [comment]
This issue is stale, I'll reopen if I encounter again.
