### ISSUE TITLE
[ENHANCEMENT] provide a way to pas in default UMAP parameters

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1028]
> When using phoenix e.g. via session = px.launch_app(primary=query_ds, corpus=database_ds)
Any way to pass in non-default UMAP Parameters - e.g. n neighbors, n samples per dataset?
Context: trying to get an intuition for the point cloud visualization - was surprised to see when i duplicate my dataframe/ds content (of a small dataset) & put it all in the same ds (so that each row appears twice), identical embeddings had a notable distance between their points
Thinking this might be due to randomness in the dimensionality reduction, so i'm wondering how to reduce this randomness & whether changing the UMAP params could help

**Comment by mikeldking** [comment]
@pbadhe I can assign this ticket to you once you have read access.

I think we should tacke this in parts

- [ ] Add `default_umap_parameters｀ as optional kwargs - e.g. it would take in a `UMAPParameters` class that is a dictionary of the configurable params
- [ ] mount this class as context to the server runtime - e.g. make it available on the server via `context.config.default_umap_params` or something of that nature
- [ ] add a graphQL resolver for `Config` - that resolves the config for the frontend
- [ ] We will then mount the config at the root of the application or at the root of all `embeddings/:dimensionId` routes
- [ ] We will then initialize the point-cloud store with these defaults when it's being initialized

Hope that makes sense. Feel free to open a draft - we can review as you go!

**Comment by pbadhe** [comment]
Hi @mikeldking, sorry for being late, was away for a while.
Can you please tell me from where we check that this config object is successfully received or requested by the frontend? or any details on where to look into for the next steps?

**Comment by axiomofjoy** [comment]
Hey @pbadhe, thanks for picking this ticket up. Mikyo is on PTO for the week. Give @RogerHYang and I a bit of time to catch up on this thread and we'll see if we can point you in the right direction 😄

**Comment by axiomofjoy** [comment]
Hey @pbadhe, not sure of the answer here. Are you blocked at the moment?

**Comment by pbadhe** [comment]
Hey @axiomofjoy, thanks for informing. I am not blocked as such but will try to explore the code a bit deeper gradually. This feature is not high priority so should not be an issue.

**Comment by axiomofjoy** [comment]
Sounds good @pbadhe.
