### ISSUE TITLE
[BUG] "Import phoenix" throwing error

### ISSUE THREAD

**Issue by AbdullahMakhdoom** [Arize-ai/phoenix#1043]
**Describe the bug**

**To Reproduce**
1. Go to Quickstart -> Google Colab
2. Install arize-phoenix by `!pip install arize-phoenix`
3. Importing phoenix results in the following error :
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-4f642603617d>](https://localhost:8080/#) in <cell line: 3>()
      1 from IPython.display import display, HTML
      2 import pandas as pd
----> 3 import phoenix as px

[/usr/local/lib/python3.10/dist-packages/phoenix/__init__.py](https://localhost:8080/#) in <module>
      3 from .datasets.schema import EmbeddingColumnNames, RetrievalEmbeddingColumnNames, Schema
      4 from .session.session import Session, active_session, close_app, launch_app
----> 5 from .trace.fixtures import load_example_traces
      6 
      7 __version__ = "0.0.31"

ModuleNotFoundError: No module named 'phoenix.trace'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

**Expected behavior**
Phoenix should be imported without throwing any error.

**Screenshots**
![Screenshot from 2023-08-04 20-29-23](https://github.com/Arize-ai/phoenix/assets/30556653/e45b451d-fe4f-4048-9f3f-d2fd6f6fa903)
**Environment (please complete the following information):**
 - Notebook Runtime : Jupyter on Colab
 - Browser : Chrome 

**Additional context**
Link to a colab : https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/image_classification_tutorial.ipynb

**Comment by mikeldking** [comment]
@AbdullahMakhdoom We had a bad release - our apologies. This should be fixed in 0.0.32
```
pip install arize-phoenix@0.0.32
``` 

Really appreciate the ticket and for trying out phoenix!

**Comment by Jacck** [comment]
no matter whatm it persists: ModuleNotFoundError: No module named 'arize_phoenix'

**Comment by axiomofjoy** [comment]
hey @Jacck, thanks for reporting. can you file a new issue with the details?
