### ISSUE TITLE
[ENHANCEMENT] mp4 video rendering of video URLs

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1048]
**Is your feature request related to a problem? Please describe.**
Embeddings can represent video as well as the captions associated with it. Phoenix should render these video URLs.

Note

The video might require signing for AWS or Google Cloud.

**Comment by tomukmatthews** [comment]
Hello @mikeldking ! May i humbly request that we bump this feature? Our team is very keen to make use of this!! If you / your team don't have time to work on this would you be open to open source contributions?

**Comment by mikeldking** [comment]
> Hello @mikeldking ! May i humbly request that we bump this feature please? Our team is very keen to make use of this!! If you / your team don't have time to work on this would you be open to open source contributions?

hey @tomukmatthews good to hear from you! Yeah sorry this has been sitting there - Can I ask some clarifying questions:

- What are the file extensions you are using for the video - do they always end with a specific extension? Because if it's not natively embeddable via HTML video easily this might be tough
- When you launch the application, does the browser you view the notebook in have direct access to the videos? E.g. there is no signing that has to happen, the URLs can be directly accessed?

If possible could you send an example URL of a video? No need for it to be a real URL for privacy reasons ofc but it will help me understand whether or not we can tackle this via extensions. AKA I think this will be significantly harder if we need to rely on MIME types etc.

On the contributions side Ofc! Would love to have you contribute :)

**Comment by tomukmatthews** [comment]
No problem at all, i appreciate you taking feature requests in the first place!

- Our video extensions are mostly `mp4`, sometimes `mov`.
- Yes the browser would have access, our data lives in private S3 buckets, however i would generate presigned url's before firing up phoenix so that the URL's could be directly accessed 👍  an example presigned url looks like this: `https://s3.<region>.amazonaws.com/<bucket>/<folder>/<video_id>.mp4?AWSAccessKeyId=<AWS_access_key>&Signature=<signature>&x-amz-security-token=<token>&Expires=<expiration_time>`

**Comment by mikeldking** [comment]
Thanks for the details @tomukmatthews ! I'll give it a stab.

**Comment by mikeldking** [comment]
@tomukmatthews I added support for rendering `<video>` in 0.0.49 - this should get you basically what you need - althought you might have issues with the URL being hit as you select and needing thumbnails. LMK if you have issues (notably with things like .mov). 

We can attempt some optemizations if need be.

**Comment by tomukmatthews** [comment]
Thanks so much @mikeldking! I'm planning to test this out as soon as i can find some time!
