### ISSUE TITLE
[BUG] Rather than forcing UTC, convert timestamp columns to UTC

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1060]
Forcing UTC makes timeseries data to be off. Rather than forcing it - convert it. If you force the timezone to be UTC, it inevitably doesn't align with the user's thinking of the data. We should always respect this.

**Comment by axiomofjoy** [comment]
I think we already convert to UTC?

https://github.com/Arize-ai/phoenix/blob/4e02625bbb85a89299021eeb7ece2e4b888b0ff6/tests/datasets/test_dataset.py#L1022

**Comment by axiomofjoy** [comment]
The additional work we need to do is to find the timezone of the server running Phoenix and infer that as the timezone when the user inputs timezone-naive timestamps.
