### ISSUE TITLE
point-cloud source removed from GitHub?

### ISSUE THREAD

**Issue by mmisiewicz** [Arize-ai/phoenix#1072]
Hello! I noticed that while [@arizeai/point-cloud](https://www.npmjs.com/package/@arizeai/point-cloud/v/3.0.4) is still showing new releases on NPM, the GitHub repository mentioned in the docs [Arize-ai/point-cloud](https://github.com/Arize-ai/point-cloud) appears to be missing. Is this intentional?

**Comment by mikeldking** [comment]
Hey @mmisiewicz ! Thanks for the issue! The repo is right now closed because we haven't fleshed out the docs. Will go public once we do a pass. Thanks for checking it out!
