### ISSUE TITLE
[BUG] Minor Issues with Langchain Pinecone notebook

### ISSUE THREAD

**Issue by pbadhe** [Arize-ai/phoenix#1074]
**Describe the bug**
1. Var not defined in 7th section. When a user wants to execute just the pre-fed data cells and avoid using the OpenAI API cells, he gets this error "name 'num_retrieved_documents' is not defined" as it was declared earlier in the 4th section which this user will not be executing.
2. The follow-along colab link (https://bit.ly/arize-langchain-pinecone-colab) in the [youtube video](https://www.youtube.com/watch?v=eDW1EsXMNY4&t=1112s) is not working, so someone can update bit.ly link. 

Will raise PR for 1st. 2nd needs to be addressed.

**Comment by mikeldking** [comment]
closed by #1074
