### ISSUE TITLE
[traces][semantic] LLM attributes

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1078]
- invocation_parameters
      -  temp
 - model_name (distinguish Azure private)
 - model_vendor (reverse DNS?)
 - role, message tuple (system, user)
 - openAI function callbacks
 - token count (impacts cost)
 - context window size (impacts cost)

**Comment by axiomofjoy** [comment]
I'm not seeing a straightforward way to get context window size for the LangChain callback. If this is something we want, we will have to maintain our own map of model name to context window size like LlamaIndex does.

https://github.com/jerryjliu/llama_index/blob/32fc54410d6f73ccb47ab5ed6c2244719ee4ccdb/llama_index/llms/langchain_utils.py#L105

**Comment by axiomofjoy** [comment]
I'm not clear on the idea of using a reverse DNS to get the model vendor, can you elaborate? @mikeldking

**Comment by axiomofjoy** [comment]
I'm not seeing unformatted role-message tuples in the LangChain callback system.

**Comment by axiomofjoy** [comment]
I'm tracking attribute support here https://docs.google.com/spreadsheets/d/1mQRoHuIpQdWFwTIEr4S6-nysVJVO6BlZPhr84saN0dA/edit?usp=sharing
