### ISSUE TITLE
[BUG] phoenix does not load with traces dataset

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1082]
**Describe the bug**
Phoenix crashes when running with the trace data fixture.

![Screenshot 2023-08-10 at 12 45 37 PM](https://github.com/Arize-ai/phoenix/assets/15664869/869c3f76-e113-40f9-96b9-fd20bd00aec0)

No console logs or logs in the Jupyter notebook cell output.

**To Reproduce**
Launch Phoenix with

```python
import phoenix as px
from phoenix.trace.fixtures import load_example_traces

ds = load_example_traces("random")
px.launch_app(trace=ds)
```

Open the Phoenix UI.

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Jupyter
 - Browser: Chrome
 - Version: latest `main` (61c94ca)

**Comment by RogerHYang** [comment]
trace needs to be added [here](https://github.com/Arize-ai/phoenix/blob/a92253fb514b4384e3b709c16612f994e31a3cfe/src/phoenix/session/session.py#L198-L202) and a few other places
