### ISSUE TITLE
[Question] How to add multiple response columns?

### ISSUE THREAD

**Issue by rnyak** [Arize-ai/phoenix#1117]
**Describe the bug**
Hello, my dataset has `query` `answer` and  `ground_truth_answer` text columns and I would like to visualize embeddings of all these three at the same time, but so far I could not make it happen. Is there any notebook example or tutorial you can recommend for that?

**To Reproduce**
This is my script. With that I am able to get prompt and response when I select points in a cluster, but not the ground_truth_answers even when I add them as another EmbeddingColumnNames. I assume I am missing something.. I'd appreciate the help . thanks!

```
df["gt_answers_vector"] = generator.generate_embeddings(text_col=df["gt_answers"])
df["answer_vector"] = generator.generate_embeddings(text_col=df["answer"])
df["query_vector"] = generator.generate_embeddings(text_col=df["query"])

schema = px.Schema(
    response_column_names=px.EmbeddingColumnNames(
        vector_column_name="answer_vector", raw_data_column_name="answer"
    ),
    prompt_column_names=px.EmbeddingColumnNames(
        vector_column_name="query_vector", raw_data_column_name="query"
    ),
   feature_column_names=["f1", "sas"],
)

px.launch_app(px.Dataset(df, schema), port=7070)
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS] : Linux Ubuntu
 - Notebook Runtime [e.g. Jupyter, Colab]: Jupyter
 - Browser [e.g. chrome, safari] :  Chrome
 - Version [e.g. 0.0.1]

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by axiomofjoy** [comment]
Hey @rnyak, thanks for trying out Phoenix!

Can you elaborate on your use-case and what problem you are trying to solve by plotting queries, responses, and ground truth answers in the same space? Our approach is typically to visualize one type of text at a time. This allows you to ask questions such as "What kinds of queries is my model struggling on?" or "What clusters of responses bear a low similarity to the reference answer (e.g., have a low ROUGE score)?"

If your goal is to visualize all three in the same embedding space, one way to accomplish this is to add the queries, responses, and ground truth answers to a single column named `text`, their associated embeddings to a column named `text_vector`, and the tags for `query`, `answer`, and `ground_truth` to a column named `text_type`. Your schema would then look like:

```
schema = px.Schema(
    embedding_column_names={
        "text_embedding": px.EmbeddingColumnNames(
            vector_column_name="text_vector", raw_data_column_name="text"
        ),
    },
    tag_column_names=["text_type"]
)
```

**Comment by axiomofjoy** [comment]
Also, I recommend joining the Arize Slack community and posting in the #phoenix-support channel. We respond more quickly there than on GitHub. https://join.slack.com/t/arize-ai/shared_invite/zt-1px8dcmlf-fmThhDFD_V_48oU7ALan4Q

**Comment by rnyak** [comment]
@axiomofjoy thanks. I thought of your workaround yes. I can stack all queries in the same df and feed a single df but not sure this will give me what I want. 

What I want to get is an extra box here as my ground_truth. My use case is QA. I have query, I have generated answer from model and I have my ground truth answer.

![image](https://github.com/Arize-ai/phoenix/assets/16246900/0657a7f3-46a4-468e-ad44-ec758e455b08)

As you can see here there is prompt and response, but I would like to have another `ground_truth_answer` from my df.  I have the embeddings of all three columns, so yes,  my goal is to visualize all three in the same embedding space.

**Comment by axiomofjoy** [comment]
@rnyak Thanks for the feedback. I've recorded this feature request [here](https://github.com/Arize-ai/phoenix/issues/1146).

**Comment by axiomofjoy** [comment]
For now, I would recommend adding the ground truth text as a tag, which will be visible in the slideover when you click on each individual point.

**Comment by rnyak** [comment]
@axiomofjoy thanks! yes, this FEA looks like what I would like to do. Is there any timeline on completing it?

**Comment by axiomofjoy** [comment]
@rnyak No concrete timeline yet, but we'll keep you posted!
