### ISSUE TITLE
[traces][integrations] llamaIndex token count capture

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1127]

**Comment by mikeldking** [comment]
blocked by the fact that depending on the model type, the token count might not be passed through. See #1078

**Comment by axiomofjoy** [comment]
Token counts for completion, prompt, and total are returned by the OpenAI API. LlamaIndex does not currently store that information. We need to file a ticket to save that information and make it available in the callback hooks.

**Comment by RogerHYang** [comment]
resolved by #1257
