### ISSUE TITLE
🗺️ [tracing] tracing without a framework

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1170]
As an AI engineer, I may not want to use any LLM app framework. I would still be able to generate spans and traces

```python
@traceable(kind="llm", attribues={})
def my_function_call():
   ....
```
## Components
- A **context manager** - Keeps track of the active spans

## Questions 
- How to deal with async executed function

**Comment by axiomofjoy** [comment]
In addition to tracing without a framework, we need to support applications that mix different LLM orchestration frameworks, or mix framework components with bespoke components/ spans.

For example, LlamaIndex supports incorporating LangChain embedding and LLM components into query engines, agents, and other higher-level abstractions:
- https://github.com/jerryjliu/llama_index/blob/d24767b0812ac56104497d8f59095eccbe9f2b08/llama_index/embeddings/langchain.py
- https://github.com/jerryjliu/llama_index/blob/d24767b0812ac56104497d8f59095eccbe9f2b08/llama_index/llms/langchain.py

As a user, I would like for the LangChain components to appear as sub-spans of my LlamaIndex trace.

Similarly, LangChain supports retrievers over LlamaIndex indexes:
- https://github.com/langchain-ai/langchain/blob/fc64e6349e6680758e0ebc837ebe7d0e3e4107b4/libs/langchain/langchain/retrievers/llama_index.py

Based on what I've heard, another common pattern is to leverage lower-level components such as the embeddings and LLM interfaces from LLM orchestration libraries and build bespoke applications around them.

Context managers sound like a good approach to tackling these usability issues. We could build a context manager in Phoenix such that any span created within that context, whether it is created by a LlamaIndex callback handler, a LangChain tracer, or a direct call to our own `Tracer.create_span` method would have the same trace ID.
