### ISSUE TITLE
[BUG] LLM invocation parameters present on every span

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1173]
**Describe the bug**
Run the langchain notebook and notice all the spans contain the same invocation parameters

<img width="905" alt="Screenshot 2023-08-21 at 10 34 50 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/33eafd9a-f1b8-40dd-a90a-6fbaa41c428f">

**Comment by mikeldking** [comment]
@axiomofjoy mind taking a look?

**Comment by axiomofjoy** [comment]
@mikeldking Is the issue that empty invocation parameters are appearing on LLM spans? This is what it looks like in the screenshot above. Or are the invocation parameters appearing on non-LLM spans?

**Comment by mikeldking** [comment]
@axiomofjoy it's showing up in all non-llm spans
<img width="455" alt="Screenshot 2023-08-22 at 3 58 22 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/191a8935-0ce7-4e89-b3c3-16ce527ccfee">
