### ISSUE TITLE
[BUG] The token counts in the traces view should reflect the token count of the child spans

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1174]
At least this is how some of the other platforms do it - at a minimum the top level traces do need to reflect the total token count so that you can sort on it.

**Comment by axiomofjoy** [comment]
Does this ticket refer to accumulating the total number of tokens of all descendent spans in parent spans? Or does it refer to the top level trace containing that total?

**Comment by mikeldking** [comment]
> Does this ticket refer to accumulating the total number of tokens of all descendent spans in parent spans? Or does it refer to the top level trace containing that total?

@axiomofjoy I think the fact that we do not aggregate on the trace table view is a problem. The way other platforms aggregate tokens feels non semantic.
