### ISSUE TITLE
[traces] notebook for a langchain agent w/ CSV (titanic dataset)

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1199]
Replicate the issues surfaces in this article and cross-compare with competitors: https://blog.langchain.dev/benchmarking-question-answering-over-csv-data/

**Comment by axiomofjoy** [comment]
Also investigate how reference output gets ingested into LangSmith.

**Comment by mikeldking** [comment]
Find a simpler agent to use an example - we have a fixture now
