### ISSUE TITLE
[evals] Support to map over traces and append metrics to spans

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1208]
As a user of phoenix traces, I will run my application for X number of queries. I will then want to evaluate these queries for bad retrieval. 

## Tradeoffs
- The evaluations will be run in the notebook so that we don't have to hoist different LLM providers into the phoenix runtime

run over the rows in the trace "dataset" and annotate the span attributes with evaluations (as well as derived metrics)

- Retriever Spans; document relevancy, retrieval precision, retrieval percent relevant

Below is pseudocode

```python
traces_with_evals = evaluate_traces(trace_df, evaluators=["RAG_RELEVANCE"])

session.run_evaluators(evaluators=["RAG_RELEVANCE"])
```

## Decisions
- Do we use a dataframe for the traces - I think there's an argument to still represent this as a dataframe within the notebook for two reasons: 1 it's easy to explore the data using dataframes in the notebook. 2. It's easy to mount the data back into phoenix via `TraceDataset(df)`.

**Comment by mikeldking** [comment]
punting until we have more metrics

**Comment by axiomofjoy** [comment]
I think there are a few implicit items in this ticket:

- We want to define a declarative way of specifying the eval configuration, e.g., via an `LLMEval` class.
- If multiple evals are run via the same model, we ought to eventually share the resources of the model (e.g., the available tokens per minute or requests per minute). Not necessarily something we need to tackle in this particular ticket.
- The `evaluate` function is intended to accept dataframes of different formats, including:
  - dataframes exported from Phoenix in OpenInference trace format
  - dataframes of user queries and retrieved documents that a user collects for analysis (i.e., not in OpenInference format)

**Comment by mikeldking** [comment]
> We want to define a declarative way of specifying the eval configuration, e.g., via an LLMEval class.

I think there are basically evaluation `tasks` that define a set of evaluations that we want to produce. These tasks don't necessarily need to be LLM assisted necessarily but for now it's safe to say most will be. The output of those tasks will then necessarily be appended to the source data to form a dataset that contains both the data and the evals as a singular artifact.

**Comment by mikeldking** [comment]
> If multiple evals are run via the same model, we ought to eventually share the resources of the model (e.g., the available tokens per minute or requests per minute). Not necessarily something we need to tackle in this particular ticket.

I think out of scope here - we should learn the bottlenecks and solve them as they come. We are already investigating in #1599 and the associated ticket.

**Comment by mikeldking** [comment]
> The evaluate function is intended to accept dataframes of different formats, including:
dataframes exported from Phoenix in OpenInference trace format
dataframes of user queries and retrieved documents that a user collects for analysis (i.e., not in OpenInference format)

I think this actually is a design decision I'm pretty happy to roll back a bit - where `llm_evals` is still a primitive building block I think running evals on traces might significantly diverge from a normal dataframe it might not be worth overloading. We can introduce something like `evaluate_traces()` where this function call would appropriately pre/post process the data to make it conducive for analysis - both in the notebook and as part of a `TraceDataset`

**Comment by mikeldking** [comment]
> The evaluate function is intended to accept multiple types of LLM evals as input.
I think for traces we can start with a known set - the reason being that we are focusing on RAG at first AND because the results need to be explicitly mapped back to a semantic attribution. some of the evals relate to sub-parts of a span, notably a document and it will be hard to build a clean abstraction for cases where we are really evaluating lists within a record. It's something for which we do need a very good simple first approach.

**Comment by mikeldking** [comment]
> Which of our LLM evals in addition to relevancy is evaluate meant to support?

I think we relax the definition here a bit - it's not LLM Evals per-se - it is an evaluation task. An evaluation task can be LLM assisted but might leverage more DS centric approaches (e.x. scikit)

**Comment by mikeldking** [comment]
> Is the function intended to run evals that apply to differing kinds of spans? For example, should a user be able to run evaluate(dataframe, [rag_relevancy, hallucinations]) even though those evals apply to distinct kinds of spans?

Very keen observations - I think another point for why maybe saying this can be run over ANY dataframe in the same way seems more and more a bad strategy

Note the pseudocode int the ticket I think is informing the design a bit too heavily and I apologize for that. I think let's reframe the user pain / story here:

We are aiming to evaluate a set of traces (not just a subset, a complete TraceDataset) for specific performance indicators - notably RAG related performance problems. So from a user's perspective, they want to know which retrievals, and ultimately traces have underlying retrieval problems. In the most abstract sense we want an API that:

```pyton
def evaluate_traces(traces, tasks=['RETRIEVAL_EVALUATION']) -> traces_with_evals
```

this way the data is savable, re-ingestable, and savable.
