### ISSUE TITLE
[ENHANCEMENT] support azure openai for relevance classifications

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1211]
**Is your feature request related to a problem? Please describe.**

Some users are unable to send data to the OpenAI API and would like to use GPT-4 in Azure OpenAI in order to perform relevance predictions for LLM-assisted ranking metrics.

**Describe the solution you'd like**

Support generic LLM interfaces.

**Additional context**

Hello everyone,
I am in kind of situation here,
I am trying to run the code with gpt-35-turbo and I am facing an error
I tried everything but couldn’t understand what’s wrong here
I am trying to run this code: https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/llama_index_search_and_retrieval_tutorial.ipynb
And on the line
first_document_relevances, second_document_relevances = [
    [
        classify_relevance(query_text, document_text, evals_model_name)
        for query_text, document_text in zip(query_texts, first_document_texts)
    ]
    for document_texts in [first_document_texts, second_document_texts]
]
I am getting this error message:
InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>
The above exception was the direct cause of the following exception:
 RetryError Traceback (most recent call last)
 /usr/local/lib/python3.10/dist-packages/tenacity/__init__.py in iter(self, retry_state)
324 if self.reraise:
325 raise retry_exc.reraise()
--> 326 raise retry_exc from fut.exception()
327
328 if self.wait:
 RetryError: RetryError[<Future at 0x7d7ee9aaa650 state=finished raised InvalidRequestError>]
And i am passing my credentials like this
evals_model_name = AzureOpenAI(
            openai_api_base= openai.api_base,
            engine = "gpt-35-turbo",
            openai_api_key = openai.api_key,
            openai_api_version = openai.api_version,
            typed_api_type = openai.api_type,
            deployment_id = "gpt-35-turbo",
            temperature=0
        )
I also tried just passing eval_model_name=“gpt-35-turbo”, but getting same error. I checked github page and couldn’t find anything
Any input on this would be highly appreciated

**Comment by mikeldking** [comment]
Now supported
