### ISSUE TITLE
LlamaIndex + OpenAI notebook

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1238]
## Goal

Show users how to instrument our OpenInference callback and use Phoenix to inspect the spans and traces of their LLM application built using LlamaIndex and OpenAI.

## Resources

The structure and copy of the notebook should mirror the [LangChain + Google PaLM tracing tutorial](https://github.com/Arize-ai/phoenix/blob/main/tutorials/langchain_google_palm_tracing_tutorial.ipynb). The code can come from our [LlamaIndex dogfooding notebook](https://github.com/Arize-ai/phoenix/blob/main/tutorials/internal/llama_index_tracing_example.ipynb).

## Use-case
RAG

**Comment by mikeldking** [comment]
done
