### ISSUE TITLE
Is it possible to host Phoenix as a service 

### ISSUE THREAD

**Issue by bindu-0107** [Arize-ai/phoenix#1243]
Is it possible to host it as service as it hosts in local host 6060 by default and if I host it as service if any new user launched another phoenix session does it impact the exisiting session of other user.

How to host it as service and enable it to different set of sessions with different data at a single time without interrupting the existing sessions

**Comment by axiomofjoy** [comment]
Hey @bindu-0107 👋  I saw that this question was addressed in community.

It's certainly possible to run Phoenix on a server. However, the IO to Phoenix is currently via pandas dataframes and we don't provide persistent storage. We also currently support only a single session at a time.

Can you tell us more about how you're thinking of using Phoenix?

**Comment by bindu-0107** [comment]
Hi @axiomofjoy currently I hosted it as service integrated with playground which takes the dataset from weaviate class selected from the user so I want to know if I can create multiple sessions at a single time at it wont stop the existing session who are using this service for another usecase

**Comment by axiomofjoy** [comment]
Which playground are you referring to?

It sounds like you are part of a team submitting data to a server running Phoenix. Since you're using Weaviate, it sounds like you might be using Phoenix for evaluating your retrieval-augmented generation pipeline?

**Comment by bindu-0107** [comment]
Yes evaluation is one of the feature we want to use we also want to create new datasets out the exisiting datasets

**Comment by axiomofjoy** [comment]
Got it. Are you using Phoenix for clustering and exporting subsets of your data?

**Comment by bindu-0107** [comment]
yes thats the use case but this service will be used by multiple users so just want to know how to create multiple sessions in the same local host port without shutting down the existing session.

Is it possible?

**Comment by axiomofjoy** [comment]
We don't currently support multiple sessions, as Phoenix has been optimized for individuals working in a notebook environment, but we'll bring your enhancement request back to the team.

What are the main benefits you hope to gain by hosting Phoenix on a single server? Does it help for collecting and curating datasets in a single place?
