### ISSUE TITLE
[trace][langchian] capture GPT messages list

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1259]
For langchain we need to parse out the system, user, assistent messages that are used to invoke an openAI calls.

**Comment by mikeldking** [comment]
# LlamaIndex attributes for chat completion on openAI
```typescript
{
  llm: {
     messages: [{ role: "system", content: "hello world" }]
  }
}

```

# Langchain
```typescript
{
   input: {
       value: "{ prompts: ["system: hello world"]}"
   }
}
```

because of this it might be worth adding a ```llm.prompt``` that captures the explicit "prompt" sent to the LLM.

**Comment by axiomofjoy** [comment]
Added in `llm.prompts` semantic convention in #1200 and

**Comment by axiomofjoy** [comment]
Best we can do on this ticket is to parse the fully formatted prompt, it looks like.

**Comment by axiomofjoy** [comment]
Parsing this prompt is going to lead to tough edge cases that will be hard for the user to understand. Here's the piece of code that formats the prompts from the sequence of messages: https://github.com/langchain-ai/langchain/blob/c898a4d7ba8b3dc338b3d1c57a301333a9edb9dc/libs/langchain/langchain/schema/messages.py#L13

The role could be any string. The following code snippet:

```python
    llm = ChatOpenAI(model_name=model_name, temperature=temperature)
    llm(
        messages=[
            ChatMessage(role="system", content="chat-message-content"),
            ChatMessage(role="user", content="chat-message-content"),
            ChatMessage(role="assistant", content="chat-message-content"),
            ChatMessage(role="function", content="chat-message-content"),
            ChatMessage(role="some-random-role-i-just-made-up", content="chat-message-content"),
        ],
        callbacks=[tracer],
    )
```

produces the following formatted prompt:

```
'system: chat-message-content\nuser: chat-message-content\nassistant: chat-message-content\nfunction: chat-message-content\nsome-random-role-i-just-made-up: chat-message-content'
```

We could do a best-effort attempt at parsing based on common role values such as `system`, `user`, `assistant`, `function`, etc., but those words are likely to be part of prompts. It's not clear to me that we should take this approach. It will work most of the time, but when it doesn't work, it will result in a very confusing user experience.
