### ISSUE TITLE
[traces] add token count to embedding spans

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1268]
Ensure that token counts appear for both LlamaIndex and LangChain for embedding spans.

**Comment by mikeldking** [comment]
@axiomofjoy - it might be good to make sure we can delineate between embedding tokens and llm tokens as they probably should be rolled up differently.

**Comment by axiomofjoy** [comment]
> @axiomofjoy - it might be good to make sure we can delineate between embedding tokens and llm tokens as they probably should be rolled up differently.

Makes sense since the cost associated with embedding vs. chat models is very different. I was thinking of putting these under a different semantic convention from the others. What else did you have in mind?

**Comment by axiomofjoy** [comment]
I'm good to punt on this one until someone asks for it. Thoughts?
