### ISSUE TITLE
[evals] investigate how to maximize throughput through the OpenAI chat completions API

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1269]
Investigate how to maximize throughput through the OpenAI API.

- [ ] Is concurrency necessary?
- [ ] Does scheduling a certain volume of requests per minute help, or are the OpenAI rate limits too variable for this approach to make sense?

Timebox to a half a day.

**Comment by mikeldking** [comment]
let's do some tracking of the progress via `logger.info`

**Comment by mikeldking** [comment]
Punting on this until we complete #1272

**Comment by mikeldking** [comment]
Investigation is complete. closing
