### ISSUE TITLE
[traces][llama_index] capture `message.name` in messages for function callbacks

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1275]
https://openai.com/blog/function-calling-and-other-api-updates

**Comment by mikeldking** [comment]
LlamaIndex - data agents
Langchain - OpenAI agents

**Comment by axiomofjoy** [comment]
Several LangChain agent integration tests in here. https://github.com/Arize-ai/phoenix/blob/main/integration-tests/experimental/callbacks/test_langchain_tracer.py

**Comment by mikeldking** [comment]
blocked by https://github.com/jerryjliu/llama_index/issues/7638

**Comment by mikeldking** [comment]
blocked by https://github.com/jerryjliu/llama_index/issues/7639
