### ISSUE TITLE
setting listening address?

### ISSUE THREAD

**Issue by Data-drone** [Arize-ai/phoenix#1278]
Is it possible to set the app to listen on 0.0.0.0 instead of just localhost? 

I can see that launch_app has a port setting but no host setting.

**Comment by axiomofjoy** [comment]
Hey @Data-drone 👋 As you noticed, we don't currently expose a host parameter. We are running `uvicorn` under the hood, and it might be possible to set an environment variable to configure the host, although I haven't tried this myself.

Can you tell us more about your use-case and what you are using Phoenix for? It sounds like you might be trying to host it on a server?

**Comment by Data-drone** [comment]
My notebook is set up so that there is always a url proxy in front of it. So I need to set it to 0.0.0.0 in order to access even from the notebook

**Comment by Data-drone** [comment]
Do you know the env var?

**Comment by Data-drone** [comment]
I think from uvicorn docs it should be: `UVICORN_HOST` but it doesn't seem to be working for me. Still defaults to `localhost`

**Comment by axiomofjoy** [comment]
Hey @Data-drone, I tested setting the `UVICORN_HOST` environment variable to `0.0.0.0`. It seems to work as I expect (I tested by running Phoenix inside a Docker container and seeing if I could access the UI with and without this environment variable).

Can you tell me more about your setup? It sounds like you've got a URL proxy in front of the notebook server running Phoenix?

**Comment by axiomofjoy** [comment]
I'll drop this link here as well in case it is helpful: https://docs.arize.com/phoenix/reference/frequently-asked-questions#can-i-use-phoenix-locally-from-a-remote-jupyter-instance

**Comment by axiomofjoy** [comment]
Opened a PR to add in `host` as a parameter to `launch_app`. @Data-drone Can you test it out an see if it resolves the issue? You'll need to install the release candidate with `pip install arize-phoenix==0.0.33rc7`.

**Comment by Data-drone** [comment]
ah that kinda worked but I need to change the root path too I am getting: 

<img width="616" alt="Screenshot 2023-09-09 at 7 56 08 pm" src="https://github.com/Arize-ai/phoenix/assets/4410493/45ac2038-5c23-4825-9e7e-13619bed3100">

Because it needs to path to: `{base_path}/driver-proxy/o/5099015744649857/0612-051541-k3er7jhd/{port}/` instead. I did have a go at adding root_path but it doesn't seem to fix those two js files
