### ISSUE TITLE
[ENHANCEMENT] Evals Verbose Mode 

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1308]
Troubleshooting template problems is really hard. We need to print the Evals of the templates as they run, ideally also print the output of the LLM as it returns:
Q_and_A_classifications = llm_eval_binary(
    dataframe=df_sample,
    template=template,
    model=model,
    rails=["correct", "incorrect"], 
   **verbose=True**
)

Example:

    You are comparing a reference text to a question and trying to determine if the reference text contains information relevant to answering the question. Here is the data:
    [BEGIN DATA]
    ************
    [Question]: Where did the harpy eagle came from
    ************
    [Reference text]: The Harpy Eagle (Harpia harpyja) is a Neotropical species of eagle . It is sometimes known as the American Harpy Eagle to distinguish it from the Papuan Eagle which is sometimes known as the New Guinea Harpy Eagle or Papuan Harpy Eagle. It is the largest and most powerful raptor found in the Americas , and among the largest extant species of eagles in the world. It usually inhabits tropical lowland rainforests in the upper (emergent) canopy layer. Destruction of its natural habitat has seen it vanish from many parts of its former range, and it is nearly extirpated in Central America.
    [END DATA]

    Compare the Question above to the Reference text. You must determine whether the Reference text contains information that can answer the Question.
    Please forcus on the very specific question can be answered by the information in the Reference text.
    Your response must be single word, either "relevant" or "irrelevant",
    and should not contain any text or characters aside from that word.
    "irrelevant" means that the reference text does not contain an answer to the query.
    "relevant" means the reference text contains an answer to the query.

--------
Model Answer: 
Irrelevant

**Comment by mikeldking** [comment]
Let's start by adding logger statements throughout the evals invocation and hinge the output based on a global level. If this doesn't sufficiently solve the problem we can add a `kwargs` to explicitly set the level per invocation.
