### ISSUE TITLE
Rails should be optional 

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1309]
The rails option was supposed to be optional in the function call. This is causing problems for some use cases.

def llm_eval_binary(
    dataframe: pd.DataFrame,
    template: Union[PromptTemplate, str],
    model: BaseEvalModel,
    **rails: List[str],**
    system_instruction: Optional[str] = None,
) -> List[Optional[str]]:

**Comment by mikeldking** [comment]
It's not clear from this ticket how the eval would work in the absence of trying to extract binary information. Can you provide details of a binary template that would require no guidance on what the "binary" decision needs to be passed?

**Comment by jlopatec** [comment]
We had two needs in our session:

It was impossible to debug the template as we just got all None's as the rail was forcing the value of None, we just wanted to remove the rail and see the output. It's not in a spot where you can troubleshoot the current implementation. 

2nd

We did use the function to generate some outputs, not the original purpose of the function but we copied it from GitHub and removed the rails, to get the functionality we wanted

**Comment by mikeldking** [comment]
@jlopatec - we will tackle this post adding the verbose logging #1308 and follow-up on if it satisfies the pain you were experiencing.

**Comment by mikeldking** [comment]
will create a separete method of this - if it's used to create artificial columns

**Comment by mikeldking** [comment]
```
generated = llm_generate(
        dataframe=dataframe,
        template=template,
        model=OpenAiModel(),
    )
```
