### ISSUE TITLE
[traces][langchain] capture tool parameters as attributes

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#1330]
follow-up to #1273 

currently not available because `parameters` is not part of [`serialized`](https://github.com/langchain-ai/langchain/blob/596f294b01447774986501d8937def4310e0e0b4/libs/langchain/langchain/tools/base.py#L320) for `callback_manager.on_tool_start`

in llama-index this can be done by calling [`to_openai_function`](https://github.com/jerryjliu/llama_index/blob/8d77d54fe5e9c9c4b2d9735a0131495aa5b0bc3d/llama_index/tools/types.py#L51) under ToolMetadata

**Comment by mikeldking** [comment]
Closing as won't fix
