### ISSUE TITLE
run_relevance_eval only usable for tracing data ([ENHANCEMENT]

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1331]
The run_relevance_eval function assumes a set of columns and formats that make it only usable for a tracing dataframe, its hard coded to our tracing data format.

I need to use this function for a dataframe that does not come back through tracing, Ericks code. 

We should split out the beginning of this function into "map_from_trace_data" so we get 2 functions:

**map_from_trace_data**: Takes a dataframe from tracing and produces a dataframe with each row -> [query, [ref_chunk1, ref_chunk2, ref_chunk3]
**run_relevance_eval**: Takes in a data frame of row format (very normal format to extract from LlamaIndex, very normal format for Retrieval in general)  -> [query, [ref_chunk1, ref_chunk2, ref_chunk3] and outputs relevant.

This section of the run_relevance_eval function needs to be pulled out and slightly rewritten:

   llm_relevance_column_name = "llm_relevance"
    retrieved_document_text_column_name = "retrieved_document_text"

    non_null_query_mask = dataframe[query_column_name].notnull()
    non_empty_retrievals_mask = dataframe[retrieved_documents_column_name].apply(
        lambda x: x is not None and len(x) > 0
    )
    filtered_mask = non_null_query_mask & non_empty_retrievals_mask
    filtered_df = dataframe[filtered_mask][[query_column_name]].copy()
    filtered_df[retrieved_documents_column_name] = dataframe[filtered_mask][
        retrieved_documents_column_name
    ].map(list)

    exploded_df = filtered_df.explode(retrieved_documents_column_name, ignore_index=False)
    exploded_df[retrieved_document_text_column_name] = [
        document_data["document.content"] if document_data is not None else None
        for document_data in exploded_df[retrieved_documents_column_name]
    ]
    exploded_df = exploded_df.rename(
        columns={
            query_column_name: "query",
            retrieved_document_text_column_name: "reference",
        }
    )

**Comment by mikeldking** [comment]
tracing: `query, [doc1, doc2]`
non-tracing: `query, [txt1, txt2]`

**Comment by mikeldking** [comment]
@fjcasti1 can you propose the flat mapping mechanism by which you think this should be done - once agreed upon let's move on to implementation.

**Comment by axiomofjoy** [comment]
> tracing: `query, [doc1, doc2]` non-tracing: `query, [txt1, txt2]`
> 
> ```python
> evals = llm_relevance(map_trace(traces_df))
> ```

Can you explain the intended behavior of `map_trace` here?
