### ISSUE TITLE
[ENHANCEMENT] support for non-OpenAI models.

### ISSUE THREAD

**Issue by think-circle** [Arize-ai/phoenix#1374]
**Is your feature request related to a problem? Please describe.**
Problem is that for using evaluation to determine whether the retrieved context is RELEVANT to the question currently uses the function **_classify_relevance_** which you can either choose OpenAI GPT3.5 & GPT4. 

**Describe the solution you'd like**
I would like classify_relevance to be expanded so it can accept any llm with other frameworks such as langchain to do the evaluation.

**Describe alternatives you've considered**
I considered writing my own function from scratch to do the evaluation using my own llm

**Additional context**

**Comment by mikeldking** [comment]
Hey @think-circle thanks for your feedback! totally understand your desire - we are currently working on more evals and will expand to more types of models as we build confidence. Thanks!

**Comment by axiomofjoy** [comment]
Thanks for the feedback @think-circle!

**Comment by mikeldking** [comment]
Closing this issue as we support quite a few LLM providers like mistral, bedrock, claude, gemini and much more. Check out our docs!
