### ISSUE TITLE
[enhancement] gracefully fail imports for callbacks

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1390]
just a note: we may have to fail the `import` gracefully, because nothing is preventing the user from calling the tracer without installing the optional dependencies first (the code is all there in the same pypi package. it just won't run)

_Originally posted by @RogerHYang in https://github.com/Arize-ai/phoenix/issues/1387#issuecomment-1724564017_

**Comment by axiomofjoy** [comment]
Should we add a `trace` or `tracing` extra instead? So a user would install `pip install arize-phoenix[trace]` or `pip install arize-phoenix[tracing]`?

**Comment by mikeldking** [comment]
better to gracefully fail imports than to install un-needed deps.
