### ISSUE TITLE
[evals] add support for the openai completions api

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1399]
OpenAI recently released a new model `gpt-3.5-turbo-instruct` that appears to be supported only on the completions endpoint. Our current OpenAI LLM model only hits the chat completions endpoint. We should add support for the completions API so we can evaluate the instruct model relative to its non-instruct counterparts.

**Comment by mikeldking** [comment]
Investigate how other frameworks delineate between chat / completion and figure out a good abstraction for these two paradigms

**Comment by RogerHYang** [comment]
> Investigate how other frameworks delineate between chat / completion and figure out a good abstraction for these two paradigms

Probably not worth building out an abstraction because the API is deprecated. LangChain, for example, has two separate object classes for them: https://github.com/langchain-ai/langchain/blob/9e1e0f54d2c57588e0f9cc4c2e3eb772c2a2b1cf/libs/langchain/langchain/llms/openai.py#L215-L217
