### ISSUE TITLE
[BUG] LLM calls using agent fails to show LLM output

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1403]
**Describe the bug**
follow: https://github.com/Arize-ai/phoenix/blob/6013675c7a6f26851c761f232828a0aa8eff0b7f/tutorials/internal/llama_index_data_agent_tracing_example.ipynb#L38
<img width="2056" alt="Screenshot 2023-09-19 at 1 25 00 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/4d4120f5-bdfc-483f-9123-c076063bd1aa">

As a developer, I'd like to see the model output but there are no attributes set.

**Comment by RogerHYang** [comment]
resolved by #1405
