### ISSUE TITLE
We need a Palm 2 Model [ENHANCEMENT]

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1404]
We need a Palm 2 model, Vertex, text bison - parity with OpenAI for Evals

**Comment by mikeldking** [comment]
@fjcasti1 if the number of models we need to support becomes extensive we should consider supporting other model abstractions (llama_index, langchain, litellm) via a bridge (not a direct dependency)

Here is an example of a bridge in llama_index (e.x. https://github.com/jerryjliu/llama_index/blob/725026bfefe78f9009e09dca4b84892bce425da8/llama_index/bridge/langchain.py)

Here's an example of a model bridge (litellm in langchain)
https://api.python.langchain.com/en/latest/_modules/langchain/chat_models/litellm.html#ChatLiteLLM

Notice that langchain is not a direct dependancy of llama_index but there is a level of compatibility between them. Same for litellm with langchain.

 We just make things conform to an abstract interface and proxy calls to it. Litellm is probably an okay example too. We can even create factory methods like llma_index (`from_langchain`) that throw import errors.

https://github.com/jerryjliu/llama_index/blob/725026bfefe78f9009e09dca4b84892bce425da8/llama_index/callbacks/wandb_callback.py#L125

We then will just document explicitly the models that we have tested for and which ones yield good results. This is pretty important in my mind as we need to express our confidence in our approach through benchmarks.

**Comment by krrishdholakia** [comment]
hey @mikeldking to clarify - litellm isn't dependent on langchain. Here's our pyproject.toml - https://github.com/BerriAI/litellm/blob/main/pyproject.toml

**Comment by krrishdholakia** [comment]
@jlopatec if phoenix lets you set the openai base, then i believe you can do this via our openai proxy 

## code
```shell
$ pip install litellm
$ litellm --model palm/text-bison

# OpenAI proxy running on http://0.0.0.0:8000
```

## replace openai api base
```python
import openai 

openai.api_base = "http://0.0.0.0:8000"

print(openai.ChatCompletion.create(model="test", messages=[{"role":"user", "content":"Hey!"}]))
```
