### ISSUE TITLE
[trace][llamaindex] ensure the llamaindex callback handler records span data when directly attached to sub-components

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1437]
Our LlamaIndex callback handler currently does not flush accumulated span data when attached directly to certain components in LlamaIndex, e.g., when attached directly to an LLM component. For example, the following test fails:

```python
def test_callback_llm():
    handler = OpenInferenceTraceCallbackHandler(exporter=NoOpExporter())
    llm = OpenAI(model="gpt-3.5-turbo", callback_manager=CallbackManager([handler]))
    llm.chat([ChatMessage(role=MessageRole.USER, content="Who won the World Cup in 2018?")])

    spans = list(handler.get_spans())
    assert len(spans) == 1
```

The reason for this is that LlamaIndex callback handler currently calls `phoenix.trace.Tracer.create_span` in the `end_trace` hook. However, the `start_trace` and `end_trace` hooks are called by LlamaIndex's callback system only for certain high-level abstractions such as query engines. The result is that, if a user enables runs a single LLM or another component in isolation, the span data is accumulated on our callback without ever being added to the callback's instance of `phoenix.trace.Tracer`.

- [ ] For one-click, we need to ensure that every span shows up in the Phoenix UI, including if someone directly invokes a component span such as an LLM.
- [ ] For general usability of the callback, we need to ensure that the callback's tracer actually receives all spans, even when using LLMs or other components that do not make a call to the `start_trace` and `end_trace` hooks.

**Comment by RogerHYang** [comment]
Discussed with @mikeldking. Tagging this ticket as won't fix (for now)
