### ISSUE TITLE
[evals] handle context window overflow

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1445]
Can start with a simple truncation strategy if needed but we need to figure out how to refine down to a single answer when the context window overflows. See llama_index's refine strategies.

**Comment by mikeldking** [comment]
launch with truncation

**Comment by axiomofjoy** [comment]
GPT-4 and GPT-3.5-turbo have long context versions: https://platform.openai.com/docs/models/overview

**Comment by fjcasti1** [comment]
I believe the current decision is to implement simple truncation to unblock, can iterate after
