### ISSUE TITLE
[llama_index] PR to place the callback handler to be mounted one-click

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1447]
If the arize_phoenix env var is set, mount the phoenix callback handler to llama_index while keeping the code still part of phoenix

**Comment by RogerHYang** [comment]
Is the name really `arize_phoenix` for [one-click](https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/one_click_observability.html#openinference), as in `llama_index.set_global_handler("arize_phoenix")`?

**Comment by RogerHYang** [comment]
resolved by https://github.com/jerryjliu/llama_index/pull/7835
