### ISSUE TITLE
[evals] docs - document model options

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1481]
Document the available options for models under API

**Comment by fjcasti1** [comment]
We have one documentation improvement left to close this ticket. We need more detail in the class/model parameters. Options:
* A parameter section like in the Datasset and Schema page
* Cleaning the docstring from code and pasting it in the class definition in docs
* By linking to the respective providers pages

**Comment by axiomofjoy** [comment]
> We have one documentation improvement left to close this ticket. We need more detail in the class/model parameters. Options:
> 
> * A parameter section like in the Datasset and Schema page
> * Cleaning the docstring from code and pasting it in the class definition in docs
> * By linking to the respective providers pages

I'd vote for 1 or 3.

**Comment by mikeldking** [comment]
complteded
