### ISSUE TITLE
[BUG] UMAP fails  with error: Cannot use scipy.linalg.eigh

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1486]
Error fetching GraphQL query 'EmbeddingPageUMAPQuery' with variables '{"id":"RW1iZWRkaW5nRGltZW5zaW9uOjA=","timeRange":{"start":"2023-09-24T18:30:00.000Z","end":"2023-09-26T18:30:00.000Z"},"minDist":0,"nNeighbors":30,"nSamples":500,"minClusterSize":10,"clusterMinSamples":1,"clusterSelectionEpsilon":0,"fetchDataQualityMetric":false,"fetchPerformanceMetric":true,"dataQualityMetricColumnName":null,"performanceMetric":"accuracyScore"}': [{"message":"Cannot use scipy.linalg.eigh for sparse A with k >= N. Use scipy.linalg.eigh(A.toarray()) or reduce k.","locations":[{"line":18,"column":7}],"path":["embedding","UMAPPoints"]}]

**Comment by RogerHYang** [comment]
We fixed a similar [bug](https://github.com/Arize-ai/phoenix/issues/801) previously. Not sure what this new one is about.

**Comment by mikeldking** [comment]
Customer says it errors out only if there is a timestamp column.
