### ISSUE TITLE
[ENHANCEMENT] OpenAI Instrumentation for traces

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1524]
**Is your feature request related to a problem? Please describe.**
As a user of Phoenix, there are times where I don't want to have to use a framework, I just want to invoke an LLM and have Phoenix capture the spans to the LLM so I can inspect the call signature and to accumulate spans for analysis.

**Describe the solution you'd like**
```python
import openai
from phoenix.trace.openai import OpenAIInstrumentor
from phoenix.trace import Tracer

tracer = Tracer()
OpenAIInstrumentor(tracer).instrument()

openai.ChatCompletion.create(...)

# Traces show up in phoenix
```

**Additional context**
This will be very useful when people are using much simpler use-cases - such as LLMs for simple summaries

**Comment by axiomofjoy** [comment]
Started out by building support for synchronous chat completions requests to the OpenAI API with @anticorrelator. Do we also want to build out support for the following, or should we punt?


- [ ] completions
- [ ] embeddings
- [ ] async

**Comment by RogerHYang** [comment]
> Started out by building support for synchronous chat completions requests to the OpenAI API with @anticorrelator. Do we also want to build out support for the following, or should we punt?
> 
> * [ ]  completions
> * [ ]  embeddings
> * [ ]  async

Would it make sense to patch [`request_raw`](https://github.com/openai/openai-python/blob/284c1799070c723c6a553337134148a7ab088dd8/openai/api_requestor.py#L579)? This seems to used by everything.
