### ISSUE TITLE
[evals] chore: switch over rag notebooks to use new `rag_relevancy` over classify_relevance method in experimental

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1544]
For now it might make better sense to keep the API signature simpler as it causes some confusion - though the binding of a template will have to exist for there to be a pipelining of LLM evals on traces.

**Comment by axiomofjoy** [comment]
We should at the same time deprecate `classify_relevance`, or add a deprecation warning.

**Comment by mikeldking** [comment]
Close out if a non issue @axiomofjoy

**Comment by axiomofjoy** [comment]
After looking at this one, not sure it is necessary. Closing out.
