### ISSUE TITLE
[evals] Huggingface models - Llama 7B

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1545]
Certain enterprises have already built out LLM evals of their own and are leveraging Llama models. In order to not change their workflow, we should natively support models that can be downloaded bia Hugglingface - notably Llama 2 - 7B as the main candidate.

There will have to be data science rigor applied to validate that LLM evals.

NB: this ticket - though phrased as Llama 2 support should lay the foundation for any huggingface model. This wouldn't use huggingface as a host but rather use huggingface to download the model and run it locally.

**Comment by mikeldking** [comment]
Maybe relevant documentation: https://huggingface.co/docs/transformers/model_doc/llama2

**Comment by RogerHYang** [comment]
Needs information on whether users actually want to run this on "bare metal" or behind an endpoint that looks just like OpenAI.

Unassigned myself for the time being.

**Comment by mikeldking** [comment]
Assigning @jlopatec for clarification

**Comment by mikeldking** [comment]
closing as this is possible right now via light llm
