### ISSUE TITLE
CI: Preserve the output of the eval notebooks

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1559]
We would like to have eval notebooks that contain a clean output of the results without containing secret openAI keys in the metadata. The notebooks need to be a bit cleaner so it's not polluted with output.

Acceptance criteria
- notebook metadata cleared
- OpenAI keys etc are not embedded
- cleanup the notebooks to not output massive progress bars etc.

**Comment by pbadhe** [comment]
If no one is working yet, I can try this. It's just all the existing notebooks from tutorials/evals/* which required to preserve output in this PR, right?

**Comment by axiomofjoy** [comment]
@pbadhe That would be great! Let me know if you want to chat on it. I'm going to assign to you.

**Comment by axiomofjoy** [comment]
> It's just all the existing notebooks from tutorials/evals/* which are required to preserve output in this PR, right?

Exactly. We want to continue to scrub notebook metadata, but keep the output. And maybe do a sanity check to make sure our API keys stored in `getpass` aren't been saved in the output somehow.

**Comment by pbadhe** [comment]
Thanks for assigning @mikeldking. @axiomofjoy I think I cannot change the assignee that's why didn't assign the issue to myself.

**Comment by mikeldking** [comment]
The pre-commit still contains the wrong sanitization logic so I will re-open https://github.com/Arize-ai/phoenix/blob/main/.pre-commit-config.yaml

**Comment by pbadhe** [comment]
> The pre-commit still contains the wrong sanitization logic so I will re-open https://github.com/Arize-ai/phoenix/blob/main/.pre-commit-config.yaml

Sorry, missed it. @mikeldking You want the same logic as present in the existing PR, instead of the [shell command](https://github.com/Arize-ai/phoenix/pull/1590#discussion_r1358432951), right?

**Comment by mikeldking** [comment]
> Sorry, missed it. @mikeldking. 

No worries @pbadhe !

**Comment by axiomofjoy** [comment]
Good catch @mikeldking
