### ISSUE TITLE
[BUG] 403 on Firefox and Brave

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1565]
**Describe the bug**
Running the LlamaIndex [tracing tutorial](https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb) on Colab and opening up the Phoenix link results in a 403 on Firefox and Brave.

![image (6)](https://github.com/Arize-ai/phoenix/assets/15664869/dd959b8a-b012-4fc5-89e3-55047d6545f5)

**Comment by axiomofjoy** [comment]
I think we were aware of this issue for Brave. This is the first time I have heard of this issue on Firefox. I am able to reproduce.

**Comment by LeMoussel** [comment]
Not this issue with Chrome

**Comment by hidek84** [comment]
It works after upgrading the Brave version on my Mac.

My Brave version is `Version 1.61.104 Chromium: 120.0.6099.115 (Official Build) (arm64)`

**Comment by wenxijuji** [comment]
I was trying these two tutorial:
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/llm_ops_overview.ipynb
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/openai_tracing_tutorial.ipynb

The generated links gave me 403 on both chrome and Firefox on Linux
