### ISSUE TITLE
[ENHANCEMENT] enhance LlamaIndex documentation to describe how to check for an active Phoenix session and how to restart the session if needed

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1571]
**Is your feature request related to a problem? Please describe.**
Users of our LlamaIndex callback are unclear on how to check if a Phoenix session is currently active. We document how to check for an active Phoenix session, and how to restart Phoenix if the existing session has died.

**Comment by mikeldking** [comment]
Closing as this is old
