### ISSUE TITLE
[BUG] Phoenix does not support LlamaIndex streaming methods

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1572]
**Describe the bug**
Users report issues with the streaming methods for LlamaIndex models, e.g., https://github.com/run-llama/llama_index/blob/9e62bc084cb25f7fe5977cf7150f6456e8c82673/llama_index/llms/openai.py#L129

**Comment by mikeldking** [comment]
@anticorrelator let's at least create an example of a streaming and see what happens

**Comment by brenkehoe** [comment]
I have also noticed this when the  OpenInferenceTraceCallbackHandler  is used with streaming set to true in llama_index the generator is empty and does not yield the results. The result is however correctly recorded in the phoenix interface.

**Comment by mikeldking** [comment]
Moving back to todo to figure out a fix.

**Comment by axiomofjoy** [comment]
Follow-up ticket: https://github.com/Arize-ai/phoenix/issues/1867
