### ISSUE TITLE
[BUG] Errors reported in the llama_index callback

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1579]
**Describe the bug**
As reported in discord
![image (1)](https://github.com/Arize-ai/phoenix/assets/5640648/9dfb4914-472f-4dee-ade4-147ac157a3d6)

**Comment by mikeldking** [comment]
this might be why the users may be reporting chats being swallowed.

**Comment by axiomofjoy** [comment]
That's a good call. We probably need to do that with all our callbacks.

**Comment by RogerHYang** [comment]
This is interesting, because something has called `on_event_end` without calling `on_event_start`, or the event_id has changed.

**Comment by RogerHYang** [comment]
Instead of `TypeDict` we could make [this](https://github.com/Arize-ai/phoenix/blob/5e127b2d093343ef220debe78921d3ead4590fbb/src/phoenix/trace/llama_index/callback.py#L70C43-L70C43) a (data)class, which will give us more options when initializing it.

**Comment by mikeldking** [comment]
Marking this as high as we should never be causing stack traces in user code.

**Comment by RogerHYang** [comment]
I think we have flagged two separate issues in this ticket. 

Are we addressing just the first one below, or both?

### Issue no. 1

> ... never be causing stack traces in user code.

### Issue no. 2

> ... something has called `on_event_end` without calling `on_event_start` ...
> Instead of `TypeDict` we could make [this](https://github.com/Arize-ai/phoenix/blob/5e127b2d093343ef220debe78921d3ead4590fbb/src/phoenix/trace/llama_index/callback.py#L70C43) a (data)class, which will give us more options when initializing it.

**Comment by anticorrelator** [comment]
@RogerHYang I think you're right about the two different parts. #1606 focuses on Issue 1 as I think that's why @mikeldking marked this task as high prio. Maybe we can seperately address Issue 2 in a different PR?

**Comment by mikeldking** [comment]
Re-opening to investigate the actual error
