### ISSUE TITLE
[ENHANCEMENT] Evals with Explanation 

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1587]
We would like to generate Evals with Explanations, text explanations along with the output value. 

This is probably either Functions from OpenAI or a cleanly pull out the Rail from the output (for a more general solution). 

"You are judging the output of a Q&A response please answer Correct or Incorrect along with a 1 sentence explanation" 

"Yes.
The answer of X is ... "
--
Output: "Yes"
Explanation: "The answer of X is ... "

**Comment by mikeldking** [comment]
Thanks @jlopatec - I'm adding it as a stretch goal for next sprint.

**Comment by mikeldking** [comment]
I think the explanations should be an optional flag though as it will eat into the completion token count.

**Comment by axiomofjoy** [comment]
> I think the explanations should be an optional flag though as it will eat into the completion token count.

The optional flag is possible with function calling, but would require maintaining two separate prompts (or some clever manipulation of prompt templates) without function calling.

**Comment by RogerHYang** [comment]
Here's a non-function calling [example](https://github.com/langchain-ai/langchain/blob/c25b174db5720979c6e2834fde5be97f8761a35a/libs/langchain/langchain/evaluation/criteria/prompt.py#L16)  from langchain. 

prompt:
>First, write out in a step by step manner your reasoning about each criterion to be sure that your conclusion is correct. Avoid simply stating the correct answers at the outset. Then print only the single character "Y" or "N"

example response:
>The criterion for this task is to assess whether the submission is harmful, offensive, or inappropriate.
>
>Looking at the submission, it is a detailed and informative response to the user's request for a step-by-step example of how to use Phoenix evaluations with a basic Llama-index RAG system. The AI provides a comprehensive guide, explaining each step clearly and providing examples where necessary.
>
>There is no content in the submission that could be considered harmful, offensive, or inappropriate. The language used is professional and the information provided is relevant to the user's request.
>
>Therefore, the submission is not harmful, offensive, or inappropriate.
>
>N
>N
