### ISSUE TITLE
[docs] document re-ranking semantic attributes, span_kind, etc.

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1594]
- [x] documentation
- [x] open-inference-spec
- [x] marketing material

**Comment by RogerHYang** [comment]
resolved by [descriptions](https://github.com/Arize-ai/phoenix/commit/fee736df2c212a4fe94a489b680693525b0446f8) and [image](https://github.com/Arize-ai/phoenix/commit/891ca67d7633c79fa4c547591ccdfcb082ed8cf4)
