### ISSUE TITLE
[traces] tracing instrumentation for Bedrock - Claude 

### ISSUE THREAD

**Issue by amank94** [Arize-ai/phoenix#1598]
**Is your feature request related to a problem? Please describe.**
Support for AWS Bedrock hosted models (specifically Claude) for instrumentation for spans and traces
https://aws.amazon.com/bedrock/claude/

Describe the solution you'd like
Instrumentation to collect spans and traces from Bedrock models (specifically Claude)

**Comment by mikeldking** [comment]
@amank94 a bit confused here - you are referring to evals correct? I'm a bit confused how this differs from our existing bedrock support https://docs.arize.com/phoenix/api/evaluation-models#phoenix.experimental.evals.bedrockmodel

**Comment by mikeldking** [comment]
We support these bedrock models:
    "anthropic.claude-instant-v1"
    "anthropic.claude-v1"
    "anthropic.claude-v2"
    "amazon.titan-text-express-v1"
    "ai21.j2-mid-v1"
    "ai21.j2-ultra-v1"

**Comment by mikeldking** [comment]
Closing as the ask is not clear @amank94 - bedrock and claude are already supported

**Comment by amank94** [comment]
Hey Mikyo - reopening with more info:

Is your feature request related to a problem? Please describe.
Support for Bedrock hosted models (specifically Claude) for "Open AI" (LLM) instrumentation for spans and traces

Describe the solution you'd like
Instrumentation to collect spans and traces from Bedrock models (specifically Claude)

Describe alternatives you've considered
NA

Additional context
None to add, but @amank94 can add more based on questions

**Comment by lou-k** [comment]
The request here is to support bedrock models for traces, not evals.

**Comment by mikeldking** [comment]
> The request here is to support bedrock models for traces, not evals.

Got it, thanks @lou-k - curious how you are using Claude right now - Are you using as part of a larger application, evals in a notebook, or other?

Will work with the team to get this prioritized @amank94

**Comment by lou-k** [comment]
Part of a larger application -- we're building a RAG application and tracing is extremely helpful for debugging.

**Comment by anticorrelator** [comment]
Superceded by openinference implementation: https://github.com/orgs/Arize-ai/projects/42/views/5?pane=issue&itemId=48921876
