### ISSUE TITLE
[ENHANCEMENT] Add support to filter spans via computed and numeric fields

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1604]
As a user, I want to find spans that exceed certain threshold values:

e.x.
- I want to view high token usage
- I want to view high latency spans

Examples pulled from another platform:

<img width="505" alt="Screenshot 2023-10-11 at 4 43 06 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/012cde37-ca39-44bc-8340-d81b5bcd6d25">

These filters are important because they can be used in conjunction with other filtering criteria to isolate a segment of data that something like sorting does not.

Acceptance criteria:
- [ ] DSL for token count and greater than / less than operators
- [ ] variables and magics added to the `SpanFilterConditionField` to allow for typeahead support

**Comment by RogerHYang** [comment]
For token count, we already have the semantic attributes as shown below, but it doesn't work on root spans, i.e. the `Traces` tab. So this ticket wants to add `cumulative_token_count` for the `Traces` tab, is that correct?

<img width="682" alt="Screenshot 2023-10-12 at 12 41 35 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/8f5c0c39-86a7-4388-9269-e98fc7d94192">
