### ISSUE TITLE
[ENHANCEMENT] protect langchain callbacks from unhandled errors

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1615]
Similar to how it is executed in llama_index, all callback handling should be protected from creating runtime exceptions - similar to https://github.com/Arize-ai/phoenix/pull/1606

**Comment by Dominik26-1** [comment]
Hi, I would like to contribute to this issue, can you assign to me?

**Comment by mikeldking** [comment]
Already handled by the langchain system so might not be needed
