### ISSUE TITLE
[BUG] https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb | set_global_handler("arize_phoenix")

### ISSUE THREAD

**Issue by cmagganas** [Arize-ai/phoenix#1619]
**Describe the bug**
set_global_handler("arize_phoenix")
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/callbacks/arize_phoenix_callback.py](https://localhost:8080/#) in arize_phoenix_callback_handler(**kwargs)
      8         from phoenix.trace.exporter import HttpExporter
----> 9         from phoenix.trace.llama_index import OpenInferenceTraceCallbackHandler
     10     except ImportError:

6 frames
ImportError: cannot import name 'cast' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/callbacks/arize_phoenix_callback.py](https://localhost:8080/#) in arize_phoenix_callback_handler(**kwargs)
      9         from phoenix.trace.llama_index import OpenInferenceTraceCallbackHandler
     10     except ImportError:
---> 11         raise ImportError(
     12             "Please install Arize Phoenix with `pip install -q arize-phoenix`"
     13         )

ImportError: Please install Arize Phoenix with `pip install -q arize-phoenix`

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**To Reproduce**
Run all

**Expected behavior**
All cells ran together before today (new release 0.0.45)

**Screenshots**
![image](https://github.com/Arize-ai/phoenix/assets/42946720/2e7a23b1-0767-4e26-a1d4-de7072689fac)

**Environment (please complete the following information):**
 - Notebook Runtime [Colab]
 - Browser [chrome]

**Additional context**
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb

**Comment by axiomofjoy** [comment]
@cmagganas Thanks for flagging. I am able to reproduce.

**Comment by axiomofjoy** [comment]
Similar issue is arising in other notebooks.
