### ISSUE TITLE
[BUG] Searching breaks trace/span streaming

### ISSUE THREAD

**Issue by anticorrelator** [Arize-ai/phoenix#1674]
**Describe the bug**
Searching in the Phoenix UI breaks trace/span streaming.

**To Reproduce**
1. Activate some instrumentation to send traces and spans to phoenix
2. Run some instrumented code and watch traces and spans start to appear
3. Search for a span in the search bar
4. Traces should no longer appear automaticcaly, but do so after a refresh

**Expected behavior**
We should continuously stream independent of the searching behavior

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Colab
 - Browser: Chrome
 - Version '0.0.50rc5'

**Comment by mikeldking** [comment]
Thanks for the catch - actually knew about this issue. It's related to refechable fragments with relay - the second you refetch the fragment becomes stateful and is no longer part of the parent query. This means that we need to use the fragment to refetch the paginated views and can no longer rely on the parent. It's a pretty massive pain but probably the right thing will be to refactor the refetch logic.
