### ISSUE TITLE
[BUG] Snap to Rails for Chatty Models

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1679]
I'm seeing performance being lower than it should be for chatty models because of the following issue:

The snap to rails option doesn't know what to snap to if both rails are in the text, for very chatty models this can happen. Below is an example of Claude V2, where it should have been snapped to unreadable, yet because it kind of blabbered on it talked about both rails - so we don't know what to snap to. Note it got **unreadable** correct below but then it went on to talk about **readable** many sentences later, confusing the rails

Fix- We should add an option to limit the snap to text window characters to only the first X characters of the text string to look for the rail. Easiest approach would be to only look at 2x the largest rails in characters. 

unreadable is longest rail (longer than readable) it is 10 characters so we would only look at first 20 characters  

Output:
- Cannot snap " unreadable\n\nThe code is unnecessarily complex and hard to read. Some ways to improve:\n\n- Use more descriptive variable names than just 'num' and single letter variables like 'i'\n\n- Break the logic into smaller functions with clear names describing what they do rather than one big function\n\n- Avoid indexing directly into the string with num[i]. Instead iterate over the string directly with for ch in num:\n\n- Put the list of primes into a set for faster lookup instead of a tuple\n\n- Use more explicit comparisons like ch in prime_digits_set rather than ch in primes\n\n- Use a counter variable instead of manually incrementing total for more readable counting\n\nOverall the logic is quite complex for what should be a simple hex digit counting function. Breaking it down into smaller pieces with descriptive names would make it much more readable." to rails

**Comment by jlopatec** [comment]
I think this char limit should be the default, but given the team is finding snap to rails useful for general strings, we should make that limit optional or have a flag to run on full text.

**Comment by mikeldking** [comment]
Worth experimenting with token limit parameters (we know this exists with OpenAI). 

IF not we can truncate to the max rails plus a bit of padding for the rails code for now.

**Comment by mikeldking** [comment]
Deprioritizing bedrock for now since we have a fair amount of OpenAI missing parts. Will re-prioritize as bedrock becomes more urgent.
