### ISSUE TITLE
[BUG] Hatch environments are probably underspecified

### ISSUE THREAD

**Issue by anticorrelator** [Arize-ai/phoenix#1685]
**Describe the bug**
After a fresh reinstall of my `hatch` environment, some of my versions of hatch dependencies are different from @axiomofjoy's. This is probably leading to inconsistent output from `hatch` scripts.

**To Reproduce**
1. `source PATH_TO_HATCH_ENV/bin/activate`
2. `pip freeze`

**Expected behavior**
Xander's dependencies should match mine

**Screenshots**
Some of Xander's dependencies:
```
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.3.1
jupyter_core==5.3.1
jupyter_server==2.7.2
jupyter_server_terminals==0.4.4
jupyterlab==4.0.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.24.0
```

My dependencies
```
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.8.0
jupyter-lsp==2.2.0
jupyter_client==8.5.0
jupyter_core==5.5.0
jupyter_server==2.9.1
jupyter_server_terminals==0.4.4
jupyterlab==4.0.7
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.0
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Same python branch

**Comment by axiomofjoy** [comment]
@anticorrelator Can you try running that hatch command in a zsh shell?
