### ISSUE TITLE
[BUG] Llama Index callback missing LLM calls in query engine

### ISSUE THREAD

**Issue by SlapDrone** [Arize-ai/phoenix#1700]
**Describe the bug**

Using a simple query engine, a bunch of information (in particular, LLM calls) seem to be missing from the phoenix spans. Only the "top-level" information (the query that goes into the query engine and the final output) is logged. Under the hood of course, there's the system message, the QA and refine prompts that are sent in-between, and so on.

**To Reproduce**

Here's a (reasonably M)WE:

```python
import phoenix as px
import llama_index
from pydantic import BaseModel, Field
from llama_index.callbacks import CallbackManager
from llama_index.llms import OpenAI
from llama_index.query_engine import RetrieverQueryEngine 
from llama_index.indices.list import SummaryIndexRetriever
from llama_index.response_synthesizers import CompactAndRefine
from llama_index import Document, SummaryIndex, ServiceContext
from phoenix.trace.llama_index import (
    OpenInferenceTraceCallbackHandler,
)

session = px.active_session()
if session is None:
    session = px.launch_app()
llama_index.set_global_handler("arize_phoenix")

# Initialize the callback handler
# NOTE: this doesn't work with the global handler nor with the explicit callback manager
# callback_handler = OpenInferenceTraceCallbackHandler()

service_ctx = ServiceContext.from_defaults(
    llm=(
        OpenAI(
            model="gpt-3.5-turbo-16k",
            max_retries=10
        )
    ),
    # callback_manager=CallbackManager(handlers=[callback_handler]),
)

class Person(BaseModel):
    """A class representing a person mentioned in the text"""
    name: str = Field(description="The person's name")
    age: int | None = Field(description="The person's age")

class People(BaseModel):
    """A class representing a collection of unique individuals"""
    people: list[Person] = Field(
        description="A list of all unique people mentioned in a text."
    )
    
from textwrap import dedent

doc = Document(
    text=dedent(
        """
        Bobby Shaftoe was only 16 when he went to sea as a deckhand. \
        He fell victim to the scurvy after just 2 months. \
        Unfazed, Captain Jack discharged his duties with extreme prejudice. \
        """
    )
)

response_synth = CompactAndRefine(
    service_context=service_ctx,
    output_cls=People,
)

query_eng = RetrieverQueryEngine(
    retriever=SummaryIndexRetriever(index=SummaryIndex.from_documents([doc])),
    response_synthesizer=response_synth
)

query_eng.query("Who is mentioned in this contrived, minimal 'story'?")

df = session.get_spans_dataframe()
```

Screenshot:

![span](https://github.com/Arize-ai/phoenix/assets/32279503/d2ac274a-7a50-421b-b16a-d9325d573923)

I'm sure you could get a similar result with less code using the high-level API, but I am using the low-level API for more control in production so figured I'd spell everything out in the example.

**Environment (please complete the following information):**
 - OS: Linux
 - Notebook Runtime: Jupyter
 - Browser: Firefox
 - Version 0.0.51

**Comment by SlapDrone** [comment]
Poking around my local phoenix here [src/phoenix/trace/llama_index/callback.py](https://github.com/Arize-ai/phoenix/blob/dc7f3ef6fa7c184e46ef92f1c035a29345e0b12e/src/phoenix/trace/llama_index/callback.py) and it seems like *all* the spans which should be properly displayed are correctly being passed in as part of the `event_id_to_event_data` arg at the beginning of the `_add_spans_to_tracer` function here:

https://github.com/Arize-ai/phoenix/blob/dc7f3ef6fa7c184e46ef92f1c035a29345e0b12e/src/phoenix/trace/llama_index/callback.py#L321

but these never make it to `tracer.create_span` here: 

https://github.com/Arize-ai/phoenix/blob/dc7f3ef6fa7c184e46ef92f1c035a29345e0b12e/src/phoenix/trace/llama_index/callback.py#L390

In this MWE, and possibly in general, these spans get spawned only for a subtype of events: `RETRIEVER` and `CHAIN`.

![span2](https://github.com/Arize-ai/phoenix/assets/32279503/8c435da8-a3a9-4c36-9513-02dd21f43011)

**Comment by mikeldking** [comment]
Hi @SlapDrone ! Thanks so much for filing this issue! After a quck bit of investigation, it does appear like there might be an issue with how llama_index is not passing down the global callback manager correctly to some sub-parts. You will have to restart your runtime but here is your code slightly modified that manually passes the context manager to all the necessary parts:

```python
import llama_index
import phoenix as px
from llama_index import Document, ServiceContext, SummaryIndex
from llama_index.callbacks import CallbackManager
from llama_index.indices.list import SummaryIndexRetriever
from llama_index.llms import OpenAI
from llama_index.query_engine import RetrieverQueryEngine
from llama_index.response_synthesizers import CompactAndRefine
from phoenix.trace.llama_index import (
    OpenInferenceTraceCallbackHandler,
)
from pydantic import BaseModel, Field

session = px.launch_app()

callback_handler = OpenInferenceTraceCallbackHandler()
cb_manager = CallbackManager(handlers=[callback_handler])

service_ctx = ServiceContext.from_defaults(
    llm=(OpenAI(model="gpt-3.5-turbo-16k", max_retries=10, callback_manager=cb_manager)),
    callback_manager=cb_manager,
)


class Person(BaseModel):
    """A class representing a person mentioned in the text"""

    name: str = Field(description="The person's name")
    age: int | None = Field(description="The person's age")


class People(BaseModel):
    """A class representing a collection of unique individuals"""

    people: list[Person] = Field(description="A list of all unique people mentioned in a text.")


from textwrap import dedent

doc = Document(
    text=dedent(
        """
        Bobby Shaftoe was only 16 when he went to sea as a deckhand. \
        He fell victim to the scurvy after just 2 months. \
        Unfazed, Captain Jack discharged his duties with extreme prejudice. \
        """
    )
)

response_synth = CompactAndRefine(
    service_context=service_ctx,
)

query_eng = RetrieverQueryEngine(
    retriever=SummaryIndexRetriever(index=SummaryIndex.from_documents([doc])),
    response_synthesizer=response_synth,
    callback_manager=cb_manager,
)

query_eng.query("Who is mentioned in this contrived, minimal 'story'?")

df = session.get_spans_dataframe()
```

This produces the right output in the UI as seen here.
<img width="2056" alt="Screenshot 2023-11-02 at 8 59 59 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/83758278-17b4-4b46-b771-2c327ef8cc71">

We work pretty closely with the llama_index team so we will root cause it and escalate a fix as needed. Thanks again for the report. Hopefully the above can unblock you for a bit!

**Comment by mikeldking** [comment]
tracked in llama_index https://github.com/run-llama/llama_index/issues/8657

**Comment by SlapDrone** [comment]
Hey @mikeldking, thanks for investigating and for your suggested tempfix, this works for me to show the main LLM calls :3

I still don't seem to see the function calls as separate entities in the dashboard. Been playing around a bit with one of the arize colab notebooks [here](https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb) and it seems like in this case, function calls get their own spans. This would be really nice if we were able to track function calls and their supplied schemas.

Is there perhaps another place I can pass the callback handler explicitly to handle this behaviour? I appreciate that the function-calling (`PydanticProgram`) query engines are quite a special case within LlamaIndex, so this might have escaped testing. 

Happy to help with any PR btw if you don't have time to address this now but could point me in the right direction :). And thanks for your efforts, this is a nice library.

**Comment by SlapDrone** [comment]
(in case it wasn't clear btw, function calls can now come into query engines by supplying `output_cls` to the `ResponseSynthesizer` to get structured outputs)

**Comment by mikeldking** [comment]
@SlapDrone I think you may be right that it's a special case within llama_index as there's a few things I saw that point this direction:

1. If you attach the `llama_index.callbacks.LLamaDebug` as an additional callback, you can see that it's missing in the span tree
```
**********
Trace: query
    |_query ->  1.749029 seconds
      |_retrieve ->  7.1e-05 seconds
      |_synthesize ->  1.74883 seconds
        |_templating ->  1.2e-05 seconds
        |_llm ->  1.745828 seconds
**********
```

2. The function calls that produce `tool` spans are llama_index's `FuncTool`s and I don't think this is outside of that paradigm. Notably you can see here that pydantic is just being called directly here: https://github.com/Arize-ai/llama_index/blob/main/llama_index/response_synthesizers/refine.py#L138
Which means that llama_index isn't "calling back" with events for phoenix to track.

The function call parameters are tracked via the llm spans so there is some visibility into this:
<img width="2024" alt="Screenshot 2023-11-03 at 7 41 20 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/c53ee28f-c4d0-406c-a8fc-de58fbfc9c66">

But I get that you would like to see the schema / BaseModel alongside the invocation of pydantic. I'm hoping llama_index will get back to me soon!

**Comment by SlapDrone** [comment]
Thanks @mikeldking, makes sense. Will follow the linked issue and poke around llamaindex incase it's an easy addition.
