### ISSUE TITLE
[traces][ui] keep state on traces view after span inspection

### ISSUE THREAD

**Issue by arizedatngo** [Arize-ai/phoenix#1721]
After inspecting my span, my traces view is all collapsed. Would be nice if we kept state so I can continue what I was doing after inspection.

![chain resets](https://github.com/Arize-ai/phoenix/assets/97070834/a4ee4c70-553c-478c-bb1d-5af37dba93af)

Example Notebook Used - https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb

**Comment by mikeldking** [comment]
Thanks Dat for filing this. This went out as a fix already in #1709 and is in the `0.1.0` release.

**Comment by arizedatngo** [comment]
@mikeldking damn you guys are fast
