### ISSUE TITLE
[BUG] issue with colab - IndexError: list index out of range

### ISSUE THREAD

**Issue by arizedatngo** [Arize-ai/phoenix#1722]
![image](https://github.com/Arize-ai/phoenix/assets/97070834/69443286-677a-4fe8-a748-4a223e9b6ddb)

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-11-efcb5a108e37>](https://localhost:8080/#) in <cell line: 1>()
----> 1 export_df = session.exports[-1]
      2 export_df.head()

[/usr/lib/python3.10/collections/__init__.py](https://localhost:8080/#) in __getitem__(self, i)
   1221             return self.__class__(self.data[i])
   1222         else:
-> 1223             return self.data[i]
   1224 
   1225     def __setitem__(self, i, item):

IndexError: list index out of range`

Link to colab - https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/image_classification_tutorial.ipynb

**Comment by mikeldking** [comment]
While this is true, if you follow the instructions, it actually wants you to export a cluster in the UI first. It's not actually a bug but I understand the notebook fails if you run all. I'm gonna put it in the backlog

**Comment by arizedatngo** [comment]
ahh yes, you are correct @mikeldking

**Comment by mikeldking** [comment]
Not a real bug - though I understand the confusion. Closing for now
