### ISSUE TITLE
[BUG] open ai changes break notebooks

### ISSUE THREAD

**Issue by arizedatngo** [Arize-ai/phoenix#1735]
`AttributeError: module 'openai' has no attribute 'OpenAI'`

Link - https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb
Docs - https://docs.arize.com/phoenix/notebooks
Name - Tracing and Evaluating a LlamaIndex + OpenAI RAG Application

![image](https://github.com/Arize-ai/phoenix/assets/97070834/1c79c663-6f01-4d32-8e32-78691947deea)

**Comment by mikeldking** [comment]
Cannot reproduce. It looks like your openAI version is out of date. Can you confirm?

```python
import openai
print(openai.__version__)
```

**Comment by arizedatngo** [comment]
Issue with runtime, no issue with colab.
