### ISSUE TITLE
[BUG] typo in model name causes tenacity retries resulting in a hanging application because it's sleeping between retries

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#1744]
To reproduce, make a typo in the model name such as the following, and the notebook will hang because it's actually sleeping between `tenacity` retries.

Commentary: under the current design, retries and API calls may be too tightly coupled.

```python
model = OpenAIModel(model_name="gpt-4-turbo")
model("hi")
```

<img width="787" alt="Screenshot 2023-11-14 at 11 52 36 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/31ac6e96-539c-4023-9251-784e827a5170">

**Comment by mikeldking** [comment]
lowering in priority and un-scheduling.
