### ISSUE TITLE
[BUG] llama-index version is incompatible with `OpenInferenceTraceCllbackHandler` in `llama_index_openai_agent_tracing_tutorial` notebook

### ISSUE THREAD

**Issue by Parker-Stafford** [Arize-ai/phoenix#1765]
**Describe the bug**
The llama-index version in the [llama-index tracing notebook](https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb#scrollTo=MfnaJJUEO5e0) is incompatible with `OpenInferenceTraceCallbackHandler`

**To Reproduce**
1. Go to this notebook https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb#scrollTo=MfnaJJUEO5e0
2. Run cells 1-5
3. Run cell 6 and see error below

![image](https://github.com/Arize-ai/phoenix/assets/52351508/2a69b130-bb76-49c9-a700-70c9d2e7adf9)

**Expected behavior**
Cell runs without error

**Screenshots**
Error:
![image](https://github.com/Arize-ai/phoenix/assets/52351508/3f2f48d6-b4eb-4c2d-8ef6-276ea5dbd8c3)

**Environment (please complete the following information):**
 - OS: MacOs
 - Notebook Runtime: colab
 - Browser: chrome
 - Version: phoenix=latest - lama-index=0.8.63.post2

**Comment by axiomofjoy** [comment]
Thanks for the report @Parker-Stafford.

**Comment by axiomofjoy** [comment]
I got the notebook running by just unpinning the LlamaIndex version.
