### ISSUE TITLE
[ENHANCEMENT] enhance evals verbose mode to log retries

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1784]
When running evals, if the system pauses because rate limits have been hit, it is not clear to the user what is going on. We need to log retries and failed requests so the user knows the cause of any slowdown and understands when the system is waiting to make a request.

**Comment by mikeldking** [comment]
@anticorrelator is this basically complete? I think we log retries no matter what correct?

**Comment by anticorrelator** [comment]
@mikeldking yep! this is done
