### ISSUE TITLE
[BUG] Older versions of sci-kitlearn don't have certain metrics

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1788]
Notably in sagemaker studio, the following metrics might be missing with sklearn

    # d2_absolute_error_score = RegressionEval(sk.d2_absolute_error_score)
    # d2_pinball_score = RegressionEval(sk.d2_pinball_score)
    # d2_tweedie_score = RegressionEval(sk.d2_tweedie_score)
    
The solution might be to have a minimum version or to simply not have these for now

**Comment by RogerHYang** [comment]
oh wow, i'll remove them
