### ISSUE TITLE
[BUG] Exporter swallows 403 errors

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1792]
The exporter only validates that an http connection can be established but doesn't actually validate that the server is returning a 200.

Here is the result of a verbose log
<img width="1764" alt="Screenshot 2023-11-21 at 11 41 42 AM" src="https://github.com/Arize-ai/phoenix/assets/5640648/ae2c45f6-61fb-41c6-a9b1-c20a8430ae6c">

**Comment by RogerHYang** [comment]
Your screenshot does show the warning "Arize Phoenix is not running on ...", which is working as intended...unless we want a more specific language for 403.

**Comment by mikeldking** [comment]
> Your screenshot does show the warning "Arize Phoenix is not running on ...", which is working as intended...unless we want a more specific language for 403.

Oh you are right. I think I missed it somehow.
