### ISSUE TITLE
[ENHANCEMENT] custom attributes on spans

### ISSUE THREAD

**Issue by lyie28** [Arize-ai/phoenix#1852]
I am working on a use case where we would like to use Pheonix to add a trace for our LLM application using LlamaIndex but we would like to be able to add custom information/attributes to the trace.

For example, imagine we want to add extra information about the source used for RAG such as where it came from, like 'search engine' etc. So we'd love some way to add custom 'info/columns' that would be displayed in the trace.

Alternatively, I was thinking I could export the data we have from the trace, add custom columns and find a different way to display it but I would like to leverage the clean dashboard visuals of the Pheonix trace if possible.

**Comment by mikeldking** [comment]
Thanks for the feedback @lyie28 - We are actually in the process of switching over to OTEL, which will give you some flexibility into being able to add attributes to the current span.

In the meantime if there is something specific that you are passing to LlamaIndex that you need captured, please let us know, we'd be happy to add semantic attributes related to RAG if need be.

**Comment by mikeldking** [comment]
@lyie28 some update on this, we've moved to OTEL so you can now create spans now: https://docs.arize.com/phoenix/telemetry/custom-spans

We've also added support for metadata via LangChain using `openinference-instrumentation-langchain` 

However I'm not sure there's an equivalent for llama-index

**Comment by mikeldking** [comment]
Closing this ticket as this will be shipped in Phoenix via https://github.com/Arize-ai/openinference/releases/tag/python-openinference-instrumentation-langchain-v0.1.2
