### ISSUE TITLE
[BUG] run_relevance_evals processes chunks incorrectly when data is loaded from csv

### ISSUE THREAD

**Issue by amyxst** [Arize-ai/phoenix#1863]
**Describe the bug**
`run_relevance_evals` processes each character instead of each element of the list (each chunk) of each `reference` entry, when dataset is loaded from CSV.

**To Reproduce**
Documented in detail in this Colab: https://colab.research.google.com/drive/1nd_b2KMvUaEci6xf913Rh0C8J2Mef0Ra#scrollTo=HP3xwTT_r8w9
- When loading data from a CSV, had to add a step to explicitly cast the `reference` column `list` dtype, before running `run_relevance_evals` to have it correctly pick up each chunk (as opposed to one character at a time)

Without casting **Note the reference chunks**:

<img width="770" alt="Screenshot 2023-12-05 at 9 49 08 AM" src="https://github.com/Arize-ai/phoenix/assets/5170374/fdb5ac26-c2a3-4958-b5a5-7b662f47778b">

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Colab
 - Version: arize-phoenix (1.4.0)

**Comment by mikeldking** [comment]
I think `run_relevance_eval` has probably run it's course and should be deprecated in some sense as it assumes too much about the structure of the documents column. It assumes it's a list
```
  document_lists = cast("pd.Series[str]", document_column).tolist()
```
which splits it by character. In any case I think the suggestion here would be to just use `llm_classify` with relevance. cc @axiomofjoy

**Comment by axiomofjoy** [comment]
`run_relevance_eval` is deprecated and is removed [here](https://github.com/Arize-ai/phoenix/pull/2375).
