### ISSUE TITLE
[ENHANCEMENT] docker container build for ARM architecture, Debug buiild

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#1866]
from community request

currently we rely on dockerhub, but it [doesn’t](https://github.com/docker/roadmap/issues/109) support automated ARM builds.

**Comment by mikeldking** [comment]
needs a custom CI job via GH workflows. Marking as good first issue.

**Comment by mikeldking** [comment]
root, nonroot, debug - arm is not priority
