### ISSUE TITLE
convert span proto at the receiver

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#1876]

**Comment by mikeldking** [comment]
@RogerHYang isn't this complete?

**Comment by RogerHYang** [comment]
> @RogerHYang isn't this complete?

That depends on the definition of complete, because right now we're still keeping a copy for the purpose of immutability: we would always return a freshly decoded copy so that nothing that goes out, e.g. through an exported dataframe, can have a pointer back to the stored structures and cause mutability problems. To completely rid the system of protos, we would probably switch over to a deepcopy approach.
