### ISSUE TITLE
🗺️ OTEL Instrumentation

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1926]
In order to reach more languages and to play better with the OTEL ecosystem, phoenix will switch over to using OTEL. 

## Spike
- [x] Investigate llmetry
- [x] #1923 

## Infra
- [x] Setup monorepo for OpenInference
- [x] https://github.com/Arize-ai/openinference/issues/17
- [x] https://github.com/Arize-ai/openinference/issues/23
## Python
- [x] #1961
- [x] #1957
- [x] #1960
- [x] #2014
- [x] [otel] setup python sub-repo under openinference
- [x] [otel] move instrumentation to openinference repo

## Server
- [x] #1952

## Javascript
- [x] https://github.com/Arize-ai/openinference/issues/12
- [x] #1962
- [x] #2013

## Migration
- [x] #2119
- [x] #2129
- [x] #2130

## Documentation
- [x] #2131
- [x] #2132
- [x] #2133
- [x] #2134
- [x] #2135
- [x] #2172
- [x] [openinference] OpenAI Readme
- [x] [openinference] LlamaIndex Readme
- [x] [openinference] LangChain Readme
- [x] [openinference] Bedrock Readme
- [x] [openinference] DSPy Readme
- [x] #2223
- [x] #2224

**Comment by amank94** [comment]
Docs feedback:
- Setup a server section has typo + ends abruptly: https://docs.arize.com/phoenix/deployment/deploying-phoenix#setup-a-server

**Comment by mikeldking** [comment]
`python3 -m phoenix.server.main` fails even when installed.

**Comment by AparnaDhinakaran** [comment]
Is there someway to distinguish between local Phoenix server and the hosted server? 

I had Phoenix pointing to a hosted environment:
![Screenshot 2024-02-05 at 5 52 02 PM](https://github.com/Arize-ai/phoenix/assets/3803589/c43596b2-8213-4dcb-b565-b183a2f59102)


However it still pointed me to the local phoenix server. This didn't have the traces, and makes sense it was in the hosted one. 

![Screenshot 2024-02-05 at 5 51 23 PM](https://github.com/Arize-ai/phoenix/assets/3803589/64a15370-2fc6-4b74-9a44-e548f5e0da02)

Traces showed up in hosted:
![Screenshot 2024-02-05 at 5 53 26 PM](https://github.com/Arize-ai/phoenix/assets/3803589/beaf1142-9b11-407c-a9d6-a2b955c5977a)

**Comment by fjcasti1** [comment]
For spinning up the LLM app + tracing using Phoenix I think the amount of information is great but I would suggest reorganizing. I would first show how to use the deployment via Docker. Once the reader sees the value, I would then add the section of deployment for development where they deploy BE, FE and Phoenix. I was missing how to deploy Phoenix in this case
![Screenshot 2024-02-05 at 3 02 05 PM](https://github.com/Arize-ai/phoenix/assets/39070172/007a7ede-4813-458b-9a44-31f8938e49d7)

**Comment by fjcasti1** [comment]
Outputs of agents do not appear
![Screenshot 2024-02-05 at 3 08 32 PM](https://github.com/Arize-ai/phoenix/assets/39070172/032fcc0c-db3c-4ed5-9c3f-31609d15dcc2)
![Screenshot 2024-02-05 at 3 08 37 PM](https://github.com/Arize-ai/phoenix/assets/39070172/ea434574-d6e7-472b-9589-1fb5e50ca9f4)

**Comment by fjcasti1** [comment]
We should include in the documentation how to extract traces from Phoenix, regardless of how it is deployed
![Screenshot 2024-02-05 at 3 17 43 PM](https://github.com/Arize-ai/phoenix/assets/39070172/b069c1cd-c4ff-405b-ad88-bba99d5019a8)

**Comment by axiomofjoy** [comment]
- Makes examples in `openinference` repo more prominent.

**Comment by mikeldking** [comment]
> Outputs of agents do not appear ![Screenshot 2024-02-05 at 3 08 32 PM](https://private-user-images.githubusercontent.com/39070172/302452888-032fcc0c-db3c-4ed5-9c3f-31609d15dcc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzc3NTYsIm5iZiI6MTcwNzE3NzQ1NiwicGF0aCI6Ii8zOTA3MDE3Mi8zMDI0NTI4ODgtMDMyZmNjMGMtZGIzYy00ZWQ1LTljM2YtMzE2MDlkMTVkY2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDIzNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MDMzOTFhZjA1ZGUyOGM3NjU2OTEzN2IxODAzMzgwOWNkMTc4NGNiYzMwMDM1Mzc5NDFjZjRiMDY2MTlmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4gHRysnzWiF-wKMCOTsNLbZ0AfzKQFM82Q9eIXXpYTs) ![Screenshot 2024-02-05 at 3 08 37 PM](https://private-user-images.githubusercontent.com/39070172/302452892-ea434574-d6e7-472b-9589-1fb5e50ca9f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzc3NTYsIm5iZiI6MTcwNzE3NzQ1NiwicGF0aCI6Ii8zOTA3MDE3Mi8zMDI0NTI4OTItZWE0MzQ1NzQtZDZlNy00NzJiLTk1ODktMWZiNWU1MGNhOWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDIzNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYjliNDFhMzRmNzA2YTYwZTAxNzBkN2NkMDkzMzA4MjkyZGU0ZTlhZWQ2OTNmODdkOGUyN2JmMWFkNDIyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NXEjK8RKVijnKWaZQEmKTm7pqwHbZC-uQapTZQNwz0M)

Good catch. This is tracked via https://github.com/Arize-ai/openinference/issues/154

**Comment by mikeldking** [comment]
> Is there someway to distinguish between local Phoenix server and the hosted server?
> 
> I had Phoenix pointing to a hosted environment: ![Screenshot 2024-02-05 at 5 52 02 PM](https://private-user-images.githubusercontent.com/3803589/302450062-c43596b2-8213-4dcb-b565-b183a2f59102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzc3NTYsIm5iZiI6MTcwNzE3NzQ1NiwicGF0aCI6Ii8zODAzNTg5LzMwMjQ1MDA2Mi1jNDM1OTZiMi04MjEzLTRkY2ItYjU2NS1iMTgzYTJmNTkxMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMjM1NzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFlZTBjNWUzZTNmNjBkYTI4YzUwYmVkYmY0NGQzOTFlZjJhOWJhNTQ2ZDRhNDc0NDcwNDE3OTEyN2UyOWFkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KUmtdZqlWenC9uJ0wsM5YiLUx7XFr8SsXb_oJKJ5Vqc)
> 
> However it still pointed me to the local phoenix server. This didn't have the traces, and makes sense it was in the hosted one.
> 
> ![Screenshot 2024-02-05 at 5 51 23 PM](https://private-user-images.githubusercontent.com/3803589/302450158-64a15370-2fc6-4b74-9a44-e548f5e0da02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzc3NTYsIm5iZiI6MTcwNzE3NzQ1NiwicGF0aCI6Ii8zODAzNTg5LzMwMjQ1MDE1OC02NGExNTM3MC0yZmM2LTRiNzQtOWE0NC1lNTQ4ZjVlMGRhMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMjM1NzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE1NDI0YzJjMDg0NWJkZjVhNmI0MDhlNjliOGM3MmNkNjA3MTlkYzJmNmE3YTQ5ZWJjMWQ2NzdmOGQ2ZjE3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.egqK0k12WS8lP4LbLWsq6YGQDWgBqZfIlKagf_0PtcA)
> 
> Traces showed up in hosted: ![Screenshot 2024-02-05 at 5 53 26 PM](https://private-user-images.githubusercontent.com/3803589/302450359-beaf1142-9b11-407c-a9d6-a2b955c5977a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzc3NTYsIm5iZiI6MTcwNzE3NzQ1NiwicGF0aCI6Ii8zODAzNTg5LzMwMjQ1MDM1OS1iZWFmMTE0Mi05YjExLTQwN2MtYTlkNi1hMmI5NTVjNTk3N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMjM1NzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM1ZTFjODc3MmZiM2I4OTNjZGM5YzhmOTJkMjg3ZGQ0ZTc0ZTc2NTZjMDU2ODRkNjczY2IzYjc0ODRiZWU1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iZ_PuvOPHa9nHXilK9Yoom-96o9MjveV8BtQy5Smf3c)
