### ISSUE TITLE
[ENHANCEMENT] Showing relevance evaluations in the 'Evaluations' tab

### ISSUE THREAD

**Issue by duncankmckinnon** [Arize-ai/phoenix#1934]
**Is your feature request related to a problem? Please describe.**
In the UI for drilling into spans, some evaluations are shown separately in the Evaluations tab and others are shown in the info tab.  I'd suggest moving any evaluations, including for retrieval relevancy, to the Evaluations tab.

**Describe the solution you'd like**
For any trace that uses Evaluations, the results are shown in the Evaluations tab instead of in info.

**Additional context**
![Screenshot 2023-12-12 at 10 45 13 AM](https://github.com/Arize-ai/phoenix/assets/13010582/f477e013-42dc-4d43-b6e1-b3c26decf6ef)

**Comment by mikeldking** [comment]
Thanks @duncankmckinnon for the feedback! We're actually not done with our evaluations milestone so bear with us while we round out the edges.
