### ISSUE TITLE
[DOC] The link to the autogen notebook is broken

### ISSUE THREAD

**Issue by jeremi** [Arize-ai/phoenix#1944]
This doc link to a docbook on Google Collab, but the link is broken:
https://docs.arize.com/phoenix/quickstart/llm-traces/autogen-support
https://github.com/Arize-ai/phoenix/blob/052349d594fa2d25b827f5318e0b438f33bf165c/docs/quickstart/llm-traces/autogen-support.md

**Comment by axiomofjoy** [comment]
Thanks for flagging @jeremi, looking into it.
