### ISSUE TITLE
[ENHANCEMENT] phoenix as standalone server like skywalking, application send data to phoenix server, phoenix server persistent the data to database

### ISSUE THREAD

**Issue by jiangying000** [Arize-ai/phoenix#1976]
**Is your feature request related to a problem? Please describe.**
I want to use phoenix as standalone server like skywalking, applications send data to phoenix server, phoenix server persistents the data to database and serves query

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I am using fastapi as application server, the integration is easy, but can not seperate them

**Comment by axiomofjoy** [comment]
Hey @jiangying000, we are beginning work on persistence [here](https://github.com/Arize-ai/phoenix/issues/1689). Can you tell us more about what you like about the Apache Skywalker experience?

> I am using fastapi as application server, the integration is easy, but can not seperate them

Is the issue you are referring to that Phoenix must be running on the same server as your application?

**Comment by jiangying000** [comment]
> Hey @jiangying000, we are beginning work on persistence [here](https://github.com/Arize-ai/phoenix/issues/1689). Can you tell us more about what you like about the Apache Skywalker experience?
> 
> 
> 
> > I am using fastapi as application server, the integration is easy, but can not seperate them
> 
> 
> 
> Is the issue you are referring to that Phoenix must be running on the same server as your application?

I want to run them on different servers, one as application server, I have a cluster of application servers. the phoenix deployed on other machine as monitor or data collection server. cluster of application servers send data to phoenix

**Comment by axiomofjoy** [comment]
I followed up with @jiangying000. The relevant code snippet for LangChain in particular is:

```python
from phoenix.trace.langchain import LangChainInstrumentor, OpenInferenceTracer
from phoenix.trace.exporter import HttpExporter

exporter = HttpExporter(endpoint="http://127.0.0.1:6006")  # change this url
tracer = OpenInferenceTracer(exporter)
LangChainInstrumentor(tracer=tracer).instrument()
```

**Comment by axiomofjoy** [comment]
Persistence is in the works.

**Comment by mikeldking** [comment]
Persistance is live in 4.0.0!
