### ISSUE TITLE
[ENHANCEMENT] Get (timing) statistic of a specific api or llm call in a range of time

### ISSUE THREAD

**Issue by jiangying000** [Arize-ai/phoenix#1977]
**Is your feature request related to a problem? Please describe.**
I want statistic of time a specific api or llm call in a range of time, e.g. Time (and arriving time of first char in streaming) used to Call gpt-4 in intent detect procedure from 3:00 - 5:00 pm.

**Comment by axiomofjoy** [comment]
Hey @jiangying000, can you help me better understand your enhancement request?

It sounds like you are building an application using GPT-4 for intent detection and are interested in tracking your application over time.

Is your enhancement request for a temporal view of the following metrics?
- request volume per unit time (e.g., per minute)
- time-to-first-token

**Comment by jiangying000** [comment]
Yes it is

**Comment by axiomofjoy** [comment]
I followed up with @jiangying000 on a call. The metrics he cares about are temporal views of
- time-to-response
- time-to-first token
- total trace time

**Comment by axiomofjoy** [comment]
Noting here. Based on our conversation, the time-to-first-token @jiangying000 cares about is not the time from the LLM request being sent to receiving the first token, but the time from the start of the trace to the first token (including retrieval steps).
