### ISSUE TITLE
Eval Bug, where its repeating the sending of requests 11 times for each row

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#2011]
This runs an eval on a dataframe of 4 items. Yet it calls the API 11 times for each. Definitely an Eval bug.
https://colab.research.google.com/drive/1rsM8LjHFkOK09TNie1Ag7YSLGr-zeczr?usp=sharing

<img width="1993" alt="Screenshot 2023-12-27 at 3 08 28 PM" src="https://github.com/Arize-ai/phoenix/assets/15720601/ea1c2f53-3ea4-4e38-be12-4b720be93e3f">

**Comment by jlopatec** [comment]
Still getting issues:
I pushed a branch to my repository to reproduce.
https://github.com/jlopatec/phoenix/tree/api-connect-issue
If you run the file:
phoenix/scripts/rag/llama_index_w_evals_and_qa.py

**Comment by jlopatec** [comment]
Continue to get:
Failed attempt 1: raised APIConnectionError('Connection error.')

**Comment by mikeldking** [comment]
@jlopatec I think this issue is actually closed but I filed a follow-up in #2035
