### ISSUE TITLE
[ENHANCEMENT] Add visibility into tool output

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2031]
see issue here: https://github.com/Arize-ai/open-inference-spec/issues/37#issue-2061156395

**Comment by mikeldking** [comment]
@axiomofjoy look into what's available in the callbacks. If it doesn't exist, we will have to rely on opentelemetry manual span creation

**Comment by tslmy** [comment]
Just FYI, Llama Index uses `function_call_response` for this matter:

https://github.com/run-llama/llama_index/blob/e3a169b93b9e6014cb2c5bd731fc1f7467e3312e/llama_index/callbacks/schema.py#L61
