### ISSUE TITLE
[bug][evals] Gemini with high concurrency causes concurrency issues

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#2032]
I'm getting a host of errors with Gemini.
Notebook
https://colab.research.google.com/drive/1JlU0hL04RbC7HaVDf_xszvhy2ARdOXJI?usp=sharing

WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: metadata.google.internal. Connection pool size: 10
Exception in worker on attempt 1: raised ValueError('Content has no parts.')
Requeuing...
Exception in worker on attempt 1: raised ValueError('Content has no parts.')
Requeuing...
Exception in worker on attempt 1: raised ValueError('Content has no parts.')
Requeuing...
Exception in worker on attempt 1: raised ValueError('Content has no parts.')

------------------------------

tion in worker on attempt 3: raised InvalidArgument('Request contains an invalid argument.')                                             
Requeuing...                                                                                                                                  
Exception in worker on attempt 3: raised InvalidArgument('Request contains an invalid argument.')                                             
Requeuing...                                                                                                                                  
Exception in worker on attempt 3: raised InvalidArgument('Request contains an invalid argument.')                                             
Requeuing...                                                                                                                                  
Exception in worker on attempt 3: raised InvalidArgument('Request contains an invalid argument.')                                             
Requeuing...                                                                                                                                  
Exception in worker on attempt 3: raised InvalidArgument('Request contains an invalid argument.')                                             
Requeuing...                                                                                                                                  
Exception in worker on attempt 3: raised AttributeError("'list' object has no attribute 'lower'")                                             
Requeuing...                                                                                                                                  
Exception in worker on attempt 3: raised InvalidArgument('Request contains an invalid argument.')                                             
Requeuing...                                                                                                                                  
Exception in worker on attempt 3: raised InvalidArgument('Request contains an invalid argument.')                                             
Requeuing...

**Comment by mikeldking** [comment]
Assigning @anticorrelator to take a look and scheduling for this sprint

**Comment by anticorrelator** [comment]
Setting the concurrency <10 resolves connection pool issues. We may want to consider lowering the default.

More importantly, our evaluation prompts seem to not always work with `Gemini`, and we probably need to format them or make `Gemini`-specific prompts that work well.

```
test_string = """You are comparing a reference text to a question and trying to determine if the reference text
contains information relevant to answering the question. Here is the data:
    [BEGIN DATA]
    ************
    [Question]: what happened to the zodiac killer
    ************
    [Reference text]: The symbol used by the Zodiac Killer to sign his correspondence The Zodiac Killer was a serial killer who operated in Northern California in the late 1960s and early 1970s. The killer's identity remains unknown. The Zodiac murdered victims in Benicia , Vallejo , Lake Berryessa , and San Francisco between December 1968 and October 1969. Four men and three women between the ages of 16 and 29 were targeted. The killer originated the name "Zodiac" in a series of taunting letters sent to the local Bay Area press. These letters included four cryptograms (or ciphers ). Of the four cryptograms sent, only one has been definitively solved. Suspects have been named by law enforcement and amateur investigators, but no conclusive evidence has surfaced. In April 2004, the San Francisco Police Department marked the case "inactive", yet re-opened the case at some point prior to March 2007. The case also remains open in the city of Vallejo, as well as in Napa County and Solano County . The California Department of Justice has maintained an open case file on the Zodiac murders since 1969.
    ************
    [END DATA]
Compare the Question above to the Reference text. You must determine whether the Reference text
contains information that can answer the Question. Please focus on whether the very specific
question can be answered by the information in the Reference text.
Your response must be single word, either "relevant" or "irrelevant",
and should not contain any text or characters aside from that word.
"irrelevant" means that the reference text does not contain an answer to the Question.
"relevant" means the reference text contains an answer to the Question.
Exception in worker on attempt 1: ValueError: Content has no parts.
Retrying...

You are comparing a reference text to a question and trying to determine if the reference text
contains information relevant to answering the question. Here is the data:
    [BEGIN DATA]
    ************
    [Question]: what happened to the zodiac killer"""
    
model(test_string)
# > ValueError('Content has no parts.')
```

If we remove the newlines, the prompt works on my machine:

```
model(test_string.replace("\n", " "))
# > relevant
```

This procedure doesn't work for all inputs, so we probably need to figure out how we need to format the prompt to play nice.

**Comment by mikeldking** [comment]
Let's keep this around to track the connection pool issue. We shouldn't keep around workers that are just causing connection pool issues. They should gracefully ramp down.

**Comment by mikeldking** [comment]
de-prioritizing since there is a workaround  - simply lower the concurrency
