### ISSUE TITLE
[Bug] APIConnectionError('Connection error.') on OpenAI requests

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2035]
Continue to get:
Failed attempt 1: raised APIConnectionError('Connection error.')

_Originally posted by @jlopatec in https://github.com/Arize-ai/phoenix/issues/2011#issuecomment-1872302492_

**Comment by mikeldking** [comment]
I can re-create this pretty consistently. It's not clear why this is being outputted however - one thing I thought may be the case is that the concurrency is higher than the number of rows in the dataframe - however taking the min doesn't seem to fix this.

**Comment by jlopatec** [comment]
I'm still getting this as well in the VS code environment example above

**Comment by jlopatec** [comment]
It is related to sync versus async, actually running Async fixes it:
    import nest_asyncio

    nest_asyncio.apply()
    
    ----
    I still think its related to creating an exact duplicate request to OpenAI before they had time to return on the first request, OpenAI then fails the API call if they see duplicates. My running theory.
