### ISSUE TITLE
[docs] add how to run and log evals to phoenix

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2038]
- Add instrumentation to your app
- collect traces
- export / query for traces
- Run evals
- log evals
- Save evals? (to do)

**Comment by axiomofjoy** [comment]
@RogerHYang I think you handled this ticket already? Good to close?

**Comment by mikeldking** [comment]
Done for now - might shuffle around organization a bit to make a cohesive narrative
