### ISSUE TITLE
Llama Index Retriever Span Bug [BUG]

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#2047]
I think this might be a regression, the retriever spans for this particular example are no longer showing up for Llamaindex:

<img width="1267" alt="Screenshot 2024-01-05 at 9 25 33 AM" src="https://github.com/Arize-ai/phoenix/assets/15720601/dc4d5c92-905e-4b44-aa52-393d3b141907">

Colab to reproduce
https://colab.research.google.com/drive/1ijvtNQ8n-8sVfu0db3gkZR8GEOi2ID_l?usp=sharing

**Comment by RogerHYang** [comment]
@jlopatec This is caused by running the query under a query engine without an embedding model. In your notebook, the query engine got defined twice. See screenshot below. If you run the query again under the second definition of the query engine, the retriever span does show up (I checked).

<img width="853" alt="Screenshot 2024-01-05 at 10 28 59 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/c16bd7cb-4c96-4fad-8dbb-a0e3dd79c8f8">

**Comment by RogerHYang** [comment]
This may be an issue with LLamIndex. Below show the result from running the query again under the second query engine.

<img width="950" alt="Screenshot 2024-01-05 at 10 39 19 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/913feb6e-11c1-4662-ac96-f0ee36591477">

**Comment by RogerHYang** [comment]
This is definitely an issue with the callback system in LLamaIndex. With the first query engine the retrieve event never enters our tracer.

## First Engine
We don't see the retrieve event.

<img width="1025" alt="Screenshot 2024-01-05 at 11 02 33 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/e50ae101-086f-4c45-b18d-5c3ff26d392f">

## Second Engine
We now see the retrieve event.

<img width="1015" alt="Screenshot 2024-01-05 at 10 59 37 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/f24e5c49-5617-4ecf-848b-6027ab748abf">

**Comment by jlopatec** [comment]
It very well might be a LlamaIndex bug, it actually wasn't related to the embedding model. The fix was the following:

I added the service context to the index

index = load_index_from_storage(
    storage_context,
    service_context=service_context,
)

versus it was 


https://colab.research.google.com/drive/1ijvtNQ8n-8sVfu0db3gkZR8GEOi2ID_l?usp=sharing
