### ISSUE TITLE
[BUG] log_evaluations usability issue with nans

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2054]
If you log scores containing nan values, those scores will be accepted without error by `log_evaluations`, but Phoenix will break when loading the UI. We should either:
- fail the call to `log_evaluations` when a user attempts to log nans with an informative error message
- accept nans to `log_evaluations`, but filter them out so that the subsequent graphql query does not break
I'd vote for the latter option.

Note: This also seems to happen with explanations, although nans are less likely to occur in that scenario.

**Comment by axiomofjoy** [comment]
@RogerHYang Any thoughts on which approach to take here?

**Comment by RogerHYang** [comment]
will just fix the sender for now. will fix the receiver later
