### ISSUE TITLE
[ENHANCEMENT] Evals over token window Retries

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#2065]
We should not retry over token window API calls as they will not succeed when tried again. Instead it should, log the error, return a ERROR string for that item and move on.

**Comment by axiomofjoy** [comment]
@jlopatec Just to clarify, do you mean don't retry when the input text exceeds the context window?

**Comment by mikeldking** [comment]
@anticorrelator will take a look. Agree there is no need to retry a call that will fail.
