### ISSUE TITLE
[BUG] tracing doesn't work when port is manually entered (ex: port=6007)

### ISSUE THREAD

**Issue by kangeugine** [Arize-ai/phoenix#2083]
**Describe the bug**
Tracing doesn't work when port is manually entered through `px.launch_app`
The code below works fine when port is not manually entered (default=6006)

**To Reproduce**
```python
import phoenix as px

from dotenv import load_dotenv, find_dotenv

from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains import LLMChain
from phoenix.trace.langchain import OpenInferenceTracer, LangChainInstrumentor

load_dotenv(find_dotenv())
session = px.launch_app(port=6007) # HIGHLIGHT
tracer = OpenInferenceTracer()
LangChainInstrumentor(tracer).instrument()

llm = ChatOpenAI(temperature=0.9, model="gpt-3.5-turbo")
prompt = ChatPromptTemplate.from_template(
    "What is the best name to describe \
    a company that makes {product}?"
)
chain = LLMChain(llm=llm, prompt=prompt)
product = "Queen Size Sheet Set"
chain.run(product)

session.url
```
after running the above code, go to the url provided by `session.url`

**Expected behavior**
 I would expect trace to exist for the query, prompt, and output

**Screenshots**

**Environment (please complete the following information):**
 - OS: Apple M1 (macOS Ventura 13.5.1)
 - Browser: Chrome
 - pheonix version: 2.4.1
 - langchain version: 0.1.0

**Comment by RogerHYang** [comment]
@kangeugine Can you try setting it via [environment variable](https://docs.arize.com/phoenix/api/session#environment-variables) instead?
```python
import os

os.environ["PHOENIX_PORT"] = "6007"
```

**Comment by mikeldking** [comment]
soft deprecate params in launch_app and encourage everyone to use environment variables.
