### ISSUE TITLE
[BUG] Instruction is not a valid input to all models

### ISSUE THREAD

**Issue by anticorrelator** [Arize-ai/phoenix#2105]
**Describe the bug**
We always pass the `instruction` kwarg to model objects via `_generate` and `_async_generate`, and is an invalid keyword argument to some models. We should consider only passing this option in for models that support it, and do not leave it on the top level interface.

**Comment by axiomofjoy** [comment]
I almost wonder if we should change the name of this parameter to `system_message`. I have not heard any APIs or models that call this "instruction".
