### ISSUE TITLE
[BUG] cannot mount Phoenix in a lambda or any instance where the home directory is not writable

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2116]
**Describe the bug**

OK i figured out the issue… its trying to write to the homedirectory in the Lambda and its not writeable

Error importing phoenix: [Errno 30] Read-only file system: '/home/sbx_user1051'

It looks like this comes from config.py, is there a way to override this to a /var/task dir where Lambda can write ?

for path in (
    ROOT_DIR := Path.home().resolve() / ".phoenix",
    EXPORT_DIR := ROOT_DIR / "exports",
    DATASET_DIR := ROOT_DIR / "datasets",
    TRACE_DATASET_DIR := ROOT_DIR / "trace_datasets",
):
    path.mkdir(parents=True, exist_ok=True)

**Comment by denen99** [comment]
Force setting $HOME Env var in the Lambda environment to “/var/task” which is the only writeable directory worked to solve this issue, although not ideal.
