### ISSUE TITLE
[ENHANCEMENT] Support otlp-grpc

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2123]
**Is your feature request related to a problem? Please describe.**
There are actually more grpc downloads with python openTelemetry than http. Phoenix should support collecting spans over grpc to make the ergonomics simpler for end-users

**Describe the solution you'd like**
/v1/traces supports grpc as well

**Describe alternatives you've considered**
None

**Additional context**
GRPC has a default port - we might have to open this and this may cause additional complexity

**Comment by mikeldking** [comment]
Link to python proto exporter: https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py

**Comment by axiomofjoy** [comment]
Todo:
- Run gRPC server in a separate thread.
  - For `ProcessSession`, run as a daemon thread.
  - For `TheadSession`, run in the background.
- Investigate error handling.
  - For `ProcessSession`, run a health check (possibly via a flag or event in the thread) and exit if the thread is unhealthy. Use a timeout.
  - For `ThreadSession`, gracefully exit the service if `close_app` is called.

**Comment by axiomofjoy** [comment]
We've decided to deprioritize this issue until we have a concrete customer ask.
