### ISSUE TITLE
[BUG] Cannot save trace dataset that is exported from session

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2128]
**Describe the bug**
Export a trace dataset from an active session and try to call `save`. You will get the following.

```
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
[<ipython-input-23-ad2a893a11db>](https://localhost:8080/#) in <cell line: 1>()
----> 1 tds_path = tds.save()

9 frames
/usr/local/lib/python3.10/dist-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: ("Could not convert UUID('618796a0-0a8e-4dc5-8d7e-febaf13a58d5') with type UUID: did not recognize Python value type when inferring an Arrow data type", 'Conversion failed for column context.span_id with type object')
```
**To Reproduce**

**Expected behavior**
can save to disc.

**Screenshots**
<img width="2044" alt="Screenshot 2024-01-26 at 8 41 00 AM" src="https://github.com/Arize-ai/phoenix/assets/5640648/0d1f7b0c-4a28-4fbf-bc1b-9ddc4c0f1948">

**Environment (please complete the following information):**
 - Notebook Runtime colab
 - Version latest

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by RogerHYang** [comment]
This should have been resolved by https://github.com/Arize-ai/phoenix/pull/2143 since they're no longer UUIDs.
