### ISSUE TITLE
[ENHANCEMENT] Ability to store metadata and tags for langchain object

### ISSUE THREAD

**Issue by cryoff** [Arize-ai/phoenix#2163]
**Is your feature request related to a problem? Please describe.**
I am using `langchain` and `phoenix` is a great observability tool for it thanks to callback mechanism. However, I am not able to store the additional metadata and tags together with a trace.

**Describe the solution you'd like**
The `metadata` and `tags` are the fields supported by `Chain` class from `langchain` including `SequentialChain`.
I would like to see those fields being stored together with a trace.
Ideally, I would like to have additional columns in UI to see those (may be switched off by default) but at least to see them in the trace details.

**Describe alternatives you've considered**
I have tried `langfuse` that do support tracking of metadata and tags. The implementation of `langchain` callback there is easier, it is a direct extension of BaseCallback from `langchain`, it is not an instrumentation.
`mlflow` `langchain`-callback was another option however their implementation is too heavy-load for a local execution and UI is far from being optimal for such task (which is much more relevant for observability purpose not for experimentation)

**Additional context**
Given some assistance, I am ready to implement such a feature (only on backend side, not on UI side)

**Comment by RogerHYang** [comment]
adding a screenshot of langfuse UI and [link](https://github.com/langfuse/langfuse-python/blob/2efa05e1dba4e1e07df57935c2faf7437352180c/langfuse/callback.py#L704-L704) to source code

<img width="431" alt="Screenshot 2024-01-31 at 4 41 13 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/6b67a228-85d3-4c75-997c-fd8a5f70104c">

**Comment by mikeldking** [comment]
@cryoff we now support langchain metadata in the traces! Let us know if you need any assistance in community slack

**Comment by cryoff** [comment]
Thank you!!!
One more question @mikeldking  - does it also trace `tags`?

**Comment by mikeldking** [comment]
> Thank you!!!
> 
> One more question @mikeldking  - does it also trace `tags`?

Not yet but great callout. Will convert your comment to an issue
