### ISSUE TITLE
Save to disc issues on Windows

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2168]

**Comment by axiomofjoy** [comment]
Not able to reproduce this issue on Windows 11 with our LlamaIndex tracing tutorial.

**Comment by axiomofjoy** [comment]
I have reproduced an error with some user-sent data.

**Comment by RogerHYang** [comment]
same issue here https://github.com/Arize-ai/phoenix/issues/2184

**Comment by RogerHYang** [comment]
closing this as duplicate of https://github.com/Arize-ai/phoenix/issues/2184
