### ISSUE TITLE
[ENHANCEMENT] TraceDataset.save() should have an optional path to save the file

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2174]
As a user, I might want to save my trace outside of the working directory. It's also not clear what I'm supposed to do with the output ID. There should be `print` statements guiding the user as to how to use `load`

**Comment by axiomofjoy** [comment]
Sounds good. `save` and `load` already have an optional `directory` parameter that enables the user to save outside the default location. Is that what they were after?

**Comment by mikeldking** [comment]
Print statements added
