### ISSUE TITLE
[ENHANCEMENT] Add the ability to filter down spans when exporting by ID

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2183]
As an advanced user (@jlopatec ) I want to collect a set of spans of interest and grab them in a dataframe in one sweep. This could be accomplished via a filter DSL like

```python
context.span_id in [id1, id2, id3]
```

Something to this nature.

**Comment by RogerHYang** [comment]
this already works, but with a Tuple, and not with a List.
```python
span_id in ('7c3d88eaff224edf8463d219c008743c', 'aecc88712cd6450098f348f7de2fd09a')
```
<img width="1011" alt="Screenshot 2024-02-02 at 4 30 21 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/847aba58-8bb6-4fd4-bb48-d5e1112f36d8">

**Comment by RogerHYang** [comment]
actually, works with a List too.

<img width="574" alt="Screenshot 2024-02-02 at 4 33 34 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/ddc00a4e-5d06-41ec-92fb-0eb14434e092">

**Comment by mikeldking** [comment]
Nice one @RogerHYang ! Should have checked
