### ISSUE TITLE
[ENHANCEMENT] - Persist with name

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#2196]
The following issue might not be an issue when persistence roles out. Maybe once that rolls out we can relook at this to see if its still an issue.

I would like to Save off and Load a fixed name:
Currently workflow is like this:
tds = TraceDataset.load("4225ef64-4dce-4710-9cf0-62009505fe05")

Problem is its a GUID returned that comes from Phoenix versus something that comes from me. If I check in any code referencing the above, it won't work for anyone else.

I'd love something like the following:
trace_dataset = px.active_session().get_trace_dataset()
trace_dataset.save("jason-data-name")
session = px.launch_app(id="jason-data-name")
-- When I re-load
tds = TraceDataset.load("jason-data-name")
session = px.launch_app(trace=tds)

The issue I'm running into is I wanted to check in code for the tests that everyone can use to save and load automatically on their local machines. Yet because the GUID is my computer specific and not set in the code by me, each person needs to run the code and get their own GUID and edit it the code. Everyone is going to have to constantly edit the checked in code to make this all work.

**Comment by jlopatec** [comment]
My other issue, is even when I'm just using the 
save and load myself in my own notebook, I want to:

Load("GUID1")
run my session
Save()

Then load("GUID1) again next time
Save()

Yet GUID changes

**Comment by mikeldking** [comment]
@jlopatec can you work with these methods for now? We get you on the determinism aspect. Just need a bit of time to think it through

cc @axiomofjoy 
```python
   @classmethod
    def from_name(cls, name: str) -> "TraceDataset":
        """Retrieves a dataset by name from the file system"""
        directory = DATASET_DIR / name
        df = read_parquet(directory / cls._data_file_name)
        return cls(df, name)

    def to_disc(self) -> None:
        """writes the data to disc"""
        directory = DATASET_DIR / self.name
        directory.mkdir(parents=True, exist_ok=True)
        get_serializable_spans_dataframe(self.dataframe).to_parquet(
            directory / self._data_file_name,
            allow_truncated_timestamps=True,
            coerce_timestamps="ms",
        )
```

**Comment by jlopatec** [comment]
That worked thanks:
tds = px.Client().get_trace_dataset()
tds.name = "phoenix_local"
tds.to_disc()

## reload ##
TraceDataset.from_name("phoenix_local")
