### ISSUE TITLE
[BUG] LlamaIndex Tracing for llama.cpp advertised as gpt3.5 turbo

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2217]
Question 1: Our LLM is always erroneously called “gpt-3.5-turbo” as the model name in the Phoenix trace. Is there a parameter we can override to change it to an arbitrary name? It seems like using “model_name = “ in OpenAIModel might actual force an OpenAI model to be used, but I could be wrong here.
We define our LLM as follows:
llm=OpenAI(
           api_base=http://xxx.yyy.zzz.aaa//,
           )
service_context= ServiceContext.from_defaults(llm=llm)
Then we generate answers to the questions in our vector store, using the LLM:
vector_index = VectorStoreIndex(train_nodes, service_context=service_context)
query_engine = [vector_index.as](http://vector_index.as/)_query_engine(verbose=True)

We have verified that the answers are generated using llama2cpp, but the Phoenix trace reads:
{
"id": "chatcmpl-c2a035ab-488e-4e21-a6ac-dbc51a5397d3",
"choices": [
   {
     "finish_reason": "stop",
     "index": 0,
     "message": {
       "content": " <block of content printed here>",
       "role": "assistant"
     }
   }
],
"created": 1707240657,
"model": "gpt-3.5-turbo",
"object": "chat.completion",
"usage": {
   "completion_tokens": 236,
   "prompt_tokens": 833,
   "total_tokens": 1069
}
}
How can we change the “model” line highlighted above to reflect a user-defined name for our local LLM?

**Comment by mikeldking** [comment]
phoenix_host="127.0.0.1"
os.environ["PHOENIX_HOST"]=phoenix_host
phoenix_collector_endpoint="http://127.0.0.1:6006/"
os.environ["PHOENIX_COLLECTOR_ENDPOINT"]=phoenix_collector_endpoint
CODE BLOCK B:
px.close_app()
px.launch_app()
CODE BLOCK C:
import llama_index
set_global_handler("arize_phoenix")
llama_index.set_global_handler("arize_phoenix")
CODE BLOCK D :  (called inside my Q&A generation routine)
from openinference.instrumentation.openai import OpenAIInstrumentor
from opentelemetry import trace as trace_api
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace.export import SimpleSpanProcessor
resource = Resource(attributes={})
tracer_provider = trace_sdk.TracerProvider(resource=resource)
span_exporter = OTLPSpanExporter(endpoint="http://127.0.0.1:6006/v1/traces")
span_processor = SimpleSpanProcessor(span_exporter=span_exporter)
tracer_provider.add_span_processor(span_processor=span_processor)
trace_api.set_tracer_provider(tracer_provider=tracer_provider)
OpenAIInstrumentor().instrument()
A few observations:
GPT-3.5-turbo always works properly (from a Phoenix trace standpoint), whether or not I include A and/or C.  I get the "query chain" traces and subsequently the  get_retrieved_documents function works fine.
Local LLM does not return query chains if I omit A or C (but include B&D).  I still do get LLM spans, but get_retrieved_documents returns an empty dataframe.
Local LLM does return query chains if I include A, B, C, D.    Hooray!
So I think this is probably expected behavior, although I'm excited for the day when you can simplify the tracing code needed for non-OpenAI LLMs!

**Comment by mikeldking** [comment]
<img width="2038" alt="Screenshot 2024-02-06 at 5 47 37 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/e47e120a-ab92-4618-8a66-bafa345685c1">
I cannot reproduce the issue, though it does seem like there is some missing information in the traces. Will put up a notebook as draft and park this issue for now.

**Comment by RWayne93** [comment]
@mikeldking how are you getting the tokens for the llamacpp model? I am currently using the langchain libraries and instrumentor and my tokens always show up as 0.

**Comment by mikeldking** [comment]
> @mikeldking how are you getting the tokens for the llamacpp model? I am currently using the langchain libraries and instrumentor and my tokens always show up as 0. 
> 
> 
> 
> for example i have my imports 
> 
> 
> 
> import phoenix as px
> 
> from phoenix.trace.langchain import LangChainInstrumentor
> 
> session = px.launch_app()
> 
> phoenix_tracer = LangChainInstrumentor().instrument()
> 
> 

Right now we do have some gaps in token counts if the raw calls don't return the counts. We do have plans on actually counting the tokens via tokenizers if so configured. I'd need to do a bit more digging. Sorry for the non concrete answer. We will work on this in the near future

**Comment by mikeldking** [comment]
Closing as not planned for now. If needed we should re-open a ticket in OpenInference
