### ISSUE TITLE
[ENHANCEMENT] add the ability to pause tracing

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2228]
I am really happy with the new feature to trace and download spans from a remotely running phoenix instance using px.Client. Once the tracing is initialised it keeps tracing all steps in the chains by using LangChainInstrumentor().instrument() - thanks again for the great work!
If I am now done with a single run through my entire application, with every span traced as desired: Is there a way to stop the LangChainInstrumentor at the end of the script or to force a restart without shutting down the phoenix instance in the background?
Scenarios:
Imagine you are running the application several times, and you are not so much interested in tracing the same things again, then it would be quite nice to start with an empty span_df again, no?
Likewise, if there are calls that should be excluded from the tracing, it would be quite nice to interrupt the tracing and start it at a later stage in the script again.

**Comment by mikeldking** [comment]
An example of wanting to pause tracing:

> Likewise, if there are calls that should be excluded from the tracing, it would be quite nice to interrupt the tracing and start it at a later stage in the script again.
This is super interesting and can totally see this being needed. Can you highlight your use-case? What specifically would you like omitted?

> For example imagine you add some custom eval metrics (as another chain after the final chain part) that also might call an llm. However, you are only interested in the first part without the evaluation. This would become traced as well without the need to do so. Makes sense? (edited)

**Comment by mikeldking** [comment]
@RogerHYang can you link how to pause tracing?

**Comment by RogerHYang** [comment]
Below is how to suppress instrumentation using OTEL context.

```python
import openai
import opentelemetry.context as context_api
from openinference.instrumentation.openai import OpenAIInstrumentor
from opentelemetry import trace as trace_api
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor

tracer_provider = trace_sdk.TracerProvider()
tracer_provider.add_span_processor(SimpleSpanProcessor(ConsoleSpanExporter()))
trace_api.set_tracer_provider(tracer_provider)

OpenAIInstrumentor().instrument()


if __name__ == "__main__":
    client = openai.OpenAI()
    token = context_api.attach(
        context_api.set_value(
            context_api._SUPPRESS_INSTRUMENTATION_KEY,
            True,
        )
    )
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": "Write a haiku."}],
        max_tokens=20,
    )
    context_api.detach(token)
    print(response.choices[0].message.content)
```
