### ISSUE TITLE
[BUG] pyarrow can't handle all possible data combinations from pandas

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#2238]
This means `px.Client()` won't always work.

> pyarrow.lib.ArrowInvalid: ('cannot mix list and non-list, non-null values', 'Conversion failed for column attributes.llm.prompt_template.variables with type object')

One alternative is to send jsonl instead of pyarrow to `px.Client()`.

possible cause:
llama-index creates a mapping and langchain

**Comment by mikeldking** [comment]
Related to https://github.com/Arize-ai/openinference/issues/191

**Comment by mikeldking** [comment]
Bumping in priority to 1
