### ISSUE TITLE
[Bug] UUIDs for trace datasets change after re-load

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2253]
My other issue, is even when I'm just using the 
save and load myself in my own notebook, I want to:

Load("GUID1")
run my session
Save()

Then load("GUID1) again next time
Save()

Yet GUID changes

_Originally posted by @jlopatec in https://github.com/Arize-ai/phoenix/issues/2196#issuecomment-1936311339_

**Comment by mikeldking** [comment]
This I cannot repro. I'm gonna assume it's related to something different and close it out with #2254 
<img width="1433" alt="Screenshot 2024-02-09 at 12 10 38 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/c4bccbf3-c11b-4cc8-b398-279616c97b15">

**Comment by axiomofjoy** [comment]
If I am understanding, the issue is that the dataset is being ingested, mutated in Phoenix by collecting additional spans, and then saved again. Is the ask here to make the dataset ID consistent throughout that entire process?

**Comment by axiomofjoy** [comment]
We might want to sunset this API now that persistence is out.

**Comment by mikeldking** [comment]
Not planned
