### ISSUE TITLE
[ENHANCEMENT] Add ability to add LLM input and output token cost and add cost column

### ISSUE THREAD

**Issue by klangst-ETR** [Arize-ai/phoenix#2256]
While it is great to be able to view both input and output token counts, it would be very helpful to be able to add the input and output token costs (e.g. cents/1000 tokens) and have a column in the UI that calculates the cost of the LLM call.

**Comment by mikeldking** [comment]
@klangst-ETR good point. Will do some research. Do you know of a good registry of model costs by chance?

**Comment by klangst-ETR** [comment]
I don't know of a good registry. My initial thought was to allow the user to be able to configure with model name and input and output token costs (and be able to configure multiple models). That way the user could just configure it based on the models they use.

**Comment by tvpavan** [comment]
We could use [tokencost]( https://github.com/AgentOps-AI/tokencost ) as default and sure we can ask the user to override or provide their costs.

**Comment by mikeldking** [comment]
@tvpavan thanks so much for the link!
