### ISSUE TITLE
[App] Filter on Langchain metadata attributes

### ISSUE THREAD

**Issue by amank94** [Arize-ai/phoenix#2266]
Problem: 
"how do I search the LLMChain metadata ("category":"jokes") which is not part of the input, I guess in one of the earlier meeting, your team may have showed some expression targeting to filter by attributes. Is that so?"

Code example

```if __name__ == "__main__":
    prompt_template = "Tell me a {adjective} joke"
    prompt = PromptTemplate(input_variables=["adjective"], template=prompt_template)
    llm = LLMChain(llm=llm_model, prompt=prompt, metadata={"category": "jokes"})
    completion = llm.predict(adjective="funny", metadata={"variant": "funny"})
    print(completion)```



![Image](https://github.com/Arize-ai/phoenix/assets/12501961/0999e6fd-385e-4dbf-9897-f476afe14f73)
![Image](https://github.com/Arize-ai/phoenix/assets/12501961/030ebca7-e5cd-4e7e-9e2e-9f9c51045f8a)

**Comment by RogerHYang** [comment]
This not currently supported because filters don't extend inside attribute values, i.e. for "metadata" the value is a dictionary `{"category": "jokes"}` and our filter doesn't extend into the dictionary because it's a attribute value
