### ISSUE TITLE
differentiate llama-index 0.10.0 from 0.9.x in llama-index callback handler

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#2267]
needs to check version [here](https://github.com/Arize-ai/phoenix/blob/0e1edb541cd7f4669421e31d9840efe016ee0229/src/phoenix/trace/llama_index/callback.py#L36) to differentiate llama-index 0.10.0 from 0.9.x, so that users can install the correct version

**Comment by mikeldking** [comment]
Makes sense, taking
