### ISSUE TITLE
[BUG] LangChain LLM calls detached from chain with RAGAS

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2282]
**Describe the bug**
<img width="1229" alt="Screenshot 2024-02-14 at 11 38 15 AM" src="https://github.com/Arize-ai/phoenix/assets/5640648/bfc2f532-8e70-4e42-b702-3d311d6637ec">

**To Reproduce**
https://colab.research.google.com/github/axiomofjoy/ragas/blob/notebook/docs/howtos/integrations/ragas-arize.ipynb

**Comment by RogerHYang** [comment]
i ran 10 and did not reproduce.

<img width="541" alt="Screenshot 2024-02-14 at 4 47 46 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/2c6c93da-912b-4bbd-b09f-8fbac6000e77">
