### ISSUE TITLE
[BUG] NaN in output string crashes UI

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#2290]
<img width="1288" alt="Screenshot 2024-02-14 at 4 55 47 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/bc8ef6a8-d7b8-4aa3-b90e-d8553eb9a5a4">
<img width="592" alt="Screenshot 2024-02-14 at 4 56 42 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/d4566b18-d431-4683-a3aa-178982a3644f">

**Comment by mikeldking** [comment]
Note: `nan` is not valid JSON so the crash is a bit expected. However maybe I can make it a bit more safe...
