### ISSUE TITLE
[ENHANCEMENT] Metadata Attributes potentially not being fully captured in Phoenix UI

### ISSUE THREAD

**Issue by amank94** [Arize-ai/phoenix#2296]
**Describe the bug**
There is a potential bug where some metadata attributes (that are being correct traced) are not being fully visualized in Phoenix UI

**Comment by axiomofjoy** [comment]
I've converted this issue from a bug to an enhancement request. The desired metadata was included in the attributes field, but we'll add some opinionated UI around it to make it more prominent.
