### ISSUE TITLE
[ENHANCEMENT] Display Metadata in the table view for traces and spans

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2305]
As a user I would like to view metadata in the traces and spans table. This is already possible in other platforms. E.x.
<img width="341" alt="Screenshot 2024-02-15 at 4 09 15 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/1832daab-76f4-4064-ba56-f81ad1fc93af">

**Comment by msropp** [comment]
@axiomofjoy why has this been closed when part of @mikeldking original's request was to have the attributes displayable as columns in the UI, which @mikeldking clearly states in his merged PR (https://github.com/Arize-ai/phoenix/pull/2304).    Should I request this in a separate enhancement request if still desired?
