### ISSUE TITLE
[BUG] notebook_environment incorrectly infers sagemaker environment

### ISSUE THREAD

**Issue by austinmw** [Arize-ai/phoenix#2332]
**Describe the bug**
The notebook environment incorrectly selects `sagemaker` by default when running a notebook in VSCode from an EC2 instance. This then errors due to missing sagemaker related files.

**To Reproduce**

Connect VSCode Remote Explorer to an EC2 instance, open a Jupyter notebook, and run:

```python
import phoenix as px

px.launch_app()
```

**Environment (please complete the following information):**
 - VSCode connected to EC2, using a notebook
 - Version `arize-phoenix>=3.0.3`

**Comment by axiomofjoy** [comment]
Thanks for the bug report @austinmw, we'll look into it.

**Comment by mikeldking** [comment]
Hinge the feature detection to be `sagemaker` module only but we should try to parse the metadata and see if it's actually a sagemaker instance. https://github.com/Arize-ai/phoenix/blame/54a28349ee81ef83caab3e1823b43a913cf218bf/src/phoenix/session/session.py#L559
