### ISSUE TITLE
🗺️ tracing projects

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2340]
As a user, I want to scale Phoenix to host multiple projects:

Use-cases include:
- Separate out testing and production
- Two different applications
- logging evaluation runs vs actual application runs

Possible use-cases

Have different parts of the application run in different traces
```python
from phoenix.trace import tracing_enabled

with tracing_enabled(project_name="My Project"):
    chain.run("How many people live in canada as of 2023?")

```
### OpenInfernce
- [x] #2381
- [x] #2377

### Phoenix Server
- [x] #2348
- [x] #2379
- [x] #2382
- [x] #2383
- [x] #2448
- [x] #2447
- [x] #2476
- [x] #2349
- [x] #2472
- [x] #2473
- [x] #2474
- [x] #2454
- [x] #2483
- [x] #2495
- [x] #2498
- [x] #2505
- [x] #2521
- [x] #2536
- [ ] #2539

## Phoenix UI
- [x] #2351
- [x] #2446
- [x] #2449
- [x] #2450
- [x] #2487
- [x] #2453
- [x] #2455
- [x] #2486
- [x] #2507
- [x] #2457
- [x] #2497
- [x] #2535
- [x] #2541
- [x] #2595

## Phoenix Client
- [x] #2451
- [x] #2452
- [x] #2510
- [x] #2566
- [x] #2567

## Phoenix Utils
- [x] #2378

## Documentation
- [x] #2511
- [x] #2545

## Dogfooding
- [x] #2544

## Discussion points
 - How to make traces land in different projects using OTEL

**Comment by RogerHYang** [comment]
One option is to put it in the attributes of the [Resource](https://github.com/open-telemetry/opentelemetry-proto/blob/9d139c87b52669a3e2825b835dd828b57a455a55/opentelemetry/proto/trace/v1/trace.proto#L53) portion of the request payload.

<img width="870" alt="Screenshot 2024-02-21 at 1 52 12 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/7bedf9bc-5b42-485a-9bb4-d19c388cf86f">

<img width="678" alt="Screenshot 2024-02-21 at 1 50 56 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/5189108a-4484-469d-8734-c4e7cdf1ebe7">

**Comment by mikeldking** [comment]
Done 🎂
