### ISSUE TITLE
[core] projects with pointers to the traces (fallback to default)

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2348]
We need to re-organize core to work with projects. 

<img width="909" alt="Screenshot 2024-02-21 at 3 58 53 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/80ba5fcb-1e5a-422c-8a42-4661490c2c8d">

**Comment by RogerHYang** [comment]
resolved by #2433
