### ISSUE TITLE
[ENHANCEMENT]Add a way to mark important traces

### ISSUE THREAD

**Issue by arizedatngo** [Arize-ai/phoenix#2352]
<img width="1725" alt="image" src="https://github.com/Arize-ai/phoenix/assets/97070834/edffd904-770f-48b9-8938-dc6ed077497d">

Similar to GMAIL's Starred / Not Starred, I noticed that there were certain traces that I wanted to mark and find later in my phoenix instance. It hard to distinguish them today. We will need them in Arize as well

Super useful to users as the debug. Maybe we implement something to that effect
![image](https://github.com/Arize-ai/phoenix/assets/97070834/1ffeea9d-7a82-4a1c-b72b-fd229fe1864d)

**Comment by mikeldking** [comment]
This will be superseded by human annotations. Closing
