### ISSUE TITLE
Tracing don't work  with Hugging face LLm

### ISSUE THREAD

**Issue by kareemalkoul** [Arize-ai/phoenix#2401]
I used phoiex with `HuggingfaceLLM` and tracing don't track any query of the LLM
all the code in this notebook
https://colab.research.google.com/drive/1va0qeWMohwq7MS38BqRj-pmb9VaEuUMc?usp=sharing

**Comment by RogerHYang** [comment]
Hi @kareemalkoul. I was not able to reproduce this issue from the notebook. My screenshot below shows the llm span. Can you post a screenshot of what you're seeing on your end?

<img width="988" alt="Screenshot 2024-02-29 at 9 40 27 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/187fe33e-c502-41a9-b8fe-1e26af38fdd6">

**Comment by kareemalkoul** [comment]
Yes, now it is works.
I think there is an update on the libraries fixed the bug that happened with me.
Thank you for your time.🙌
