### ISSUE TITLE
[BUG] Scrollbar for detail view

### ISSUE THREAD

**Issue by franperezlopez** [Arize-ai/phoenix#2402]
**Describe the bug**
When the tree is too large, we can't scroll down. 

**Expected behavior**
I want to see the full tree using an scrollbar

**Screenshots**
![image](https://github.com/Arize-ai/phoenix/assets/1222398/3017a677-aefc-4db3-8cc8-e163da3c8258)

**Environment (please complete the following information):**
 - OS: linux ubuntu
 - Notebook Runtime Jupyter
 - Browser: Chrome
 - Version: 121.0.6167.189

**Comment by mikeldking** [comment]
Hi @franperezlopez ! Thanks for the report! This will be fixed in the release `arize-phoenix==3.4.0`
