### ISSUE TITLE
llm_generate does not preserve the index of the input dataframe, unlike llm_classify

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#2434]
unlike llm_classify, generate [does not](https://github.com/Arize-ai/phoenix/blob/79267f1547265b99be551aa03339ef1e6be8182f/packages/phoenix-evals/src/phoenix/evals/generate.py#L137-L137) preserve the index of the input dataframe

**Comment by AparnaDhinakaran** [comment]
Re-opening this issue - just ran into this again.

**Comment by arizedatngo** [comment]
closing, need new imports
