### ISSUE TITLE
[ENHANCEMENT] - Long Prompt Variables in Long Prompts

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#2464]
As Prompt Variables grow in size, it can be hard to visualize the structure of the prompt. It would great to have an option to see either the concatenated prompt variables (limit chars) or the full prompt variables.  Once large prompt variables are inserted in whole to the prompt it can be hard to visualize, by showing them but in concatenated form, it can give a better view of the structure.

**Comment by mikeldking** [comment]
@jlopatec can you add a screenshot?
