### ISSUE TITLE
[BUG] langchain_tracing_tutorial not work

### ISSUE THREAD

**Issue by pJahad** [Arize-ai/phoenix#2479]
**Describe the bug**
I ran this langchain_tracing_tutorial notebook from the top on google colab, but I got an error called anyio.WouldBlock with AttributeError: 'TraceEndpoint' object has no attribute 'traces' at the chain.invoke(query) part and could not execute it.
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/langchain_tracing_tutorial.ipynb

**Comment by RogerHYang** [comment]
Hi @pJahad. Sorry for the inconvenience. This is fixed in the latest release v3.7.0
