### ISSUE TITLE
[BUG] Import error using `llama-index-core`

### ISSUE THREAD

**Issue by JohnCHarrington** [Arize-ai/phoenix#2509]
**Describe the bug**
Import error occurs when `llama-index` package is missing, even when `llama-index-core` and `llama-index-callbacks-arize-phoenix` are present. 

It appears that `phoenix.llama_index.callback._check_instrumentation_compatibility` checks for `version("llama-index")`, which raises an import error if llama index was installed using the modular `llama-index-core` package only.

**To Reproduce**
1. Install `llama-index-core` and `llama-index-callbacks-arize-phoenix`
2. Run phoenix and use `llama-index.core.set_global_handler("arize_phoenix")` 

**Expected behavior**
It should work as normal when llama-index is installed in this minimal modular way.

**Screenshots**
![Screenshot_2024-03-08-09-46-10_2880x1800%0A3440x1440](https://github.com/Arize-ai/phoenix/assets/1857365/ad9b93a3-5383-4822-ac81-0c085f618bb3)

**Environment (please complete the following information):**
 - OS: Docker, debian bullseye
 - Notebook Runtime [e.g. Jupyter, Colab]: In script
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 0.0.1]: 3.9.0

**Comment by mikeldking** [comment]
@JohnCHarrington thanks so much for the bug report. Makes sense! We will fix asap.

**Comment by axiomofjoy** [comment]
@JohnCHarrington This issue is resolved in 3.10.0. Thanks!
