### ISSUE TITLE
[ENHANCEMENT] include the project_name in the trace dataset export

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2517]
This might be a good idea for a few reasons:
- reconstruction of projects when re-ingesting
- the ability to mount multiple projects back to a running session.

**Comment by mikeldking** [comment]
@MartinoMensio thanks for your feedback! We actually have first class persistence coming and I think this will be your ideal solution. We have some utilities to latently log trace datasets back to projects but that will probably be a lot of heavy lifting for you. Thanks for your patience and let us know if we can help in any way in the meantime

**Comment by MartinoMensio** [comment]
Thank you @mikeldking !
Looking forward for the first class persistence! Can you share something about the utilities to bring back trace datasets to projects? I could give it a look while the persistence is still being developed

**Comment by anticorrelator** [comment]
hi @MartinoMensio, while we're still wrapping up the persistence work for Phoenix, the most recent release includes a `log_traces` method on the Phoenix client! With this you can load a `TraceDataset` into Phoenix after you've started the app as well as specify the `project_name` e.g.:

```python
import phoenix as px

client = px.Client()
client.log_traces(trace_dataset, project_name="my-project")
```

Hope that helps!

**Comment by MartinoMensio** [comment]
Thank you @anticorrelator ! The solution works perfectly. I had also some evaluations and I load them now with this code:

```python
client.log_traces(trace_dataset, project_name=project_name)
for eval in trace_dataset.evaluations:
    client.log_evaluations(eval, project_name=project_name)
```
