### ISSUE TITLE
[BUG] Can't scroll down the list of columns in Phoenix

### ISSUE THREAD

**Issue by camyoung93** [Arize-ai/phoenix#2526]
**Describe the bug**
If there's too many evals or columns in the Phoenix app, it was to scroll down the list of spans or traces instead of scrolling down the list of additional evals.

**To Reproduce**
1. Generate many evals
2. Start a phoenix instance and ingest the evals
3. Try to add more columns in the phoenix UI

**Expected behavior**
Be able to scroll down to see more options to add as more columns.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://us02web.zoom.us/clips/share/8veRWnZAP51QNA9aCMNWRmz_FpMPdR7xu95bVG7K1ySoDuMQPAKKMmEKyDrVHrv4erwRjpvP3M0pX090hWrXeprj.vWqNncya5lbyS-ZV)

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime Colab
 - Browser Chrome
 - Version 3.10.0

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by mikeldking** [comment]
@camyoung93 fixed in 3.13.1
