### ISSUE TITLE
[projects] dogfood scoping

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2544]
https://docs.google.com/document/d/1vHEUteisiA6lc4ofXhbd2fppBcYkuOHUThLF7nnPFPg/edit#heading=h.9714qaipo2ez

**Comment by Parker-Stafford** [comment]
My notes from dogfooding

- initially was confused that phoenix is both the exporter and the collector
- little hard to find the environment variables to update collector endpoint and project (search works well but wouldn't have foudn it in the nav)
- project docs are a little thin right now
- learned i can export with a notebook phoenix to remote phoenix
- not clear that phoenix would do the exporting for me behind the scenes
- wanted to use dustins remote phoenix for both
- slight confusion on when a phoenix server in a notebook actually gets created, thought that there would be a phoenix server in my n otebook

**Comment by anticorrelator** [comment]
Completed 2024-03-18
