### ISSUE TITLE
[ENHANCEMENT]Autoinstrument phoenix traces for llm_classify and llm_generate

### ISSUE THREAD

**Issue by arizedatngo** [Arize-ai/phoenix#2551]
When Running llm_classify or llm_generate have phoenix_trace Boolean field to auto instrument the traces into phoenix for these functions. 

Reason, it's so much easier to have a flag to see the traces for these specific functions 

evals = llm_classify(
    dataframe=location_df,
    template= user_interest_hallucination_location_template,
    model=model,
    rails = list(["aligned", "misaligned"]),
    concurrency=20,
    provide_explanation=True
    phoenix_trace = True # <------ Make this Possible or something to that affect
)

**Comment by arizedatngo** [comment]
possibly log the eval to the existing traces instead of calling log_evaluations

**Comment by mikeldking** [comment]
Assigning to @axiomofjoy - we are going to scope it as PhoenixEvalsInstrumentor so that we can de-couple tracing from evals and contextually mount the instrumentation as needed.
