### ISSUE TITLE
[BUG] Some spans landing in the wrong project

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2570]
RAGAs notebook yields strange projects.

For example below I never logged to the default project but it still got spans.
<img width="1714" alt="Screenshot 2024-03-13 at 8 22 10 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/ddbd45f8-5ace-4ff9-a47d-81a5c5bbe73d">
<img width="1729" alt="Screenshot 2024-03-13 at 8 21 28 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/220fe07c-418e-4701-b8fa-a898b6970856">
<img width="1726" alt="Screenshot 2024-03-13 at 8 20 17 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/b793c90d-5be4-4f02-be25-ef9ff9d26df7">

**Comment by RogerHYang** [comment]
i'm not able to reproduce

<img width="1380" alt="Screenshot 2024-03-13 at 8 43 44 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/e47833ec-b1c8-4cbb-966a-b08f6c8f1c2d">

**Comment by mikeldking** [comment]
It could be that the spans in langchain (via ragas) were created after `with using_project()`, making it land on the default project.

**Comment by mikeldking** [comment]
Worked the second time. It must happen when ragas fails.
<img width="1519" alt="Screenshot 2024-03-14 at 1 12 25 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/80a2fa69-f4ae-42bd-a84a-f216e889e29f">

**Comment by mikeldking** [comment]
I can reproduce when the notebook uses llama-index 0.10.0 

https://colab.research.google.com/drive/1xUPOTaFDwRATayz6vTkq4MGSYu6dummP

**Comment by mikeldking** [comment]
This is difficult to fix for now, closing
