### ISSUE TITLE
[ENHANCEMENT] New Evals for Natural Language queries to SQL tasks

### ISSUE THREAD

**Issue by singhmanas1** [Arize-ai/phoenix#2592]
**Is your feature request related to a problem? Please describe.**
Currently, Phoenix doesn't have an eval that can evaluate accuracy of LLMs that generates SQL query based on Natural Language questions from the user (Top 3 restaurants in NYC?). Current methods focus on using external LLMs as judges for the output of the LLMs under test as described in the `LLMEvaluatorClass` [here](https://github.com/Arize-ai/phoenix/blob/9eebb00ea63529ad9b12f2a4aad6716fe1088c05/packages/phoenix-evals/src/phoenix/evals/evaluators.py#L23).

Using LLM as a judge doesn't work for SQL generation tasks because it is expensive, slow, and non-deterministic. 

I also considered using GPT-4 to evaluate the correctness of generated SQL, especially since GPT-4 for self-grading in some form of a actor-critic loop seems to a commonplace solution (e.g. [LangChain’s benchmarks](https://blog.langchain.dev/benchmarking-question-answering-over-csv-data/)).

However, the [rate limits](https://platform.openai.com/docs/guides/rate-limits/overview) of the API, cost (each complete eval run could cost 3 digits excluding inference), potential for [model drift](https://www.scientificamerican.com/article/yes-ai-models-can-get-worse-over-time/) and the decreasing marginal information added in the [information loop](https://arstechnica.com/information-technology/2023/04/hype-grows-over-autonomous-ai-agents-that-loop-gpt-4-outputs/) (using GPT4 to generate queries + using GPT4 to evaluate its own responses) became deal-breakers that failed my first and foremost criterion: reproducibility.

**Describe the solution you'd like**
The following eval framework works quite well for SQL generation tasks-
1. **Populating SQL Databases**:  We can create a first draft of the dataset using GPT. Similar to [WikiSQL](https://github.com/salesforce/WikiSQL), we can generate a dozen or more rows that were semantically meaningful and related, and edit the generated data to incorporate various constraints (e.g. join keys, specific names and substrings we wanted to incorporate in our queries).
2. **Creating Question / Query Pairs** (See example [HERE](https://github.com/singhmanas1/sql-eval/blob/main/data/questions_gen_postgres.csv)) - We generate a set of question and “gold” query pairs, where the “gold” query would produce the desired results. In contrast to other benchmarks which use string/token-based matching (eg [ROUGE](https://aclanthology.org/W04-1013/)), we care more about the results generated, not the exact SQL string. 
Ex. 
The gold query for the top 3 restaurants in New York can now be concisely represented as `SELECT {id,name}, AVG(rating) FROM restaurants ORDER BY 2 DESC LIMIT 3` Here {id,name} stands for two distinct queries with id or name with the SELECT keyword. Because both these queries answer the same question - both count as ground truth queries. This is to account for the fact that multiple SQL queries can be correct.

3. **Evaluation Method** - 

- We start by expanding the braces in the gold query to generate every possible combination of the columns within. This gives us the following 2^2 - 1 (no empty set) combinations: `SELECT uid, likes_movies FROM users` `SELECT name, likes_movies FROM users` `SELECT uid, name, likes_movies FROM users`

- Given the results of running the acceptable “gold” queries and our generated query, for each result of an acceptable gold query, we compare and see if the result of the given gold query matches the result of generated query. If there is an exact match of the dataframes’ contents (ignoring data types), the result is immediately marked as correct. The function responsible for this is [compare_df](https://github.com/singhmanas1/sql-eval/blob/673a2d072bc5a62232ff21ee993f7b53bdcb5725/eval/eval.py#L225). Comparing the result of the generated query df_generated with each of the dataframe’s in dfs_gold, only the first df should match as both dataframes contain the exact same columns (id,likes_movies) containing the exact same values

- However, we might also want to do approximate matching (See implementation [HERE](https://github.com/singhmanas1/sql-eval/blob/673a2d072bc5a62232ff21ee993f7b53bdcb5725/eval/eval.py#L250)) - For each column in df1, we check to see if the same column of values exists in df2. We ignore data types, column names (since these could be [aliased](https://www.w3schools.com/sql/sql_alias.asp)) and row order while doing so. After picking out the relevant columns from df2, renaming them with the names from df1, we check that the overall dataframe matches df1. This is to ensure that we don’t accidentally match on shuffled data columns (which is quite common for column data types with low cardinality like booleans or enums) with the same unordered list of values but from the wrong column.

**Describe alternatives you've considered**
Studied the following alternate frameworks for this evaluation-

**Spider**
This [dataset + evaluation framework](https://github.com/taoyds/spider) was released by the [Lily Lab](https://yale-lily.github.io/spider) from Stanford back in 2018, and has seen multiple iterations on top of its original question/dataset, like [SParC](https://yale-lily.github.io/sparc) for more conversational benchmarks. In its raw form, the spider dataset comprises a bunch of sqlite files describing 8 different databases, together with question/query pairs.

They were the first to release [evaluation code](https://github.com/taoyds/test-suite-sql-eval) which ran the queries alongside the data provided, instead of just performing sql string / AST matching, which would result in a lot of false negatives. I really liked the complexity of the database schema ([atis](https://paperswithcode.com/dataset/atis) has 131 columns) and the way each query was classified with its own “difficulty” score based on the parsed expected SQL.

**WikiSQL**
This dataset was released by Salesforce and encompasses a wide variety of question contexts, owing to its curation method (tables from wikipedia). It was used to develop and benchmark [Seq2SQL](https://github.com/tiwarikajal/Seq2SQL--Natural-Language-sentences-to-SQL-Queries), one of our predecessors and state-of-the-art models for text-to-SQL generation.

I liked the wide variety of question contexts, but the SQL to be generated was often quite simple, given how most questions’ context involved not more than a dozen columns and seldom more than a table.

**SQL-Create-Context**
This was created on top of Spider + WikiSQL, using [sqlglot](https://github.com/tobymao/sqlglot) to parse and clean the queries. Its structure and content take more closely to WikiSQL, with a helpful addition of the context column containing the actual SQL DDL (CREATE TABLE …), which I found to be very useful for actually testing and running the queries.

**Comment by jlopatec** [comment]
@singhmanas1 
We've been working on a SQL Evals with LLM as a judge. It works pretty well. 

What could be fun here is a bit of a SQL Eval research where we test the approach above vs the SQL evals, and do a bit of community write up on it. 

We could make a call on what to augment or add based no the results. 

Maybe I'll send a note directly to you in community.

**Comment by mikeldking** [comment]
this was completed as LLM evals in #2861
