### ISSUE TITLE
[BUG] arize-phoenix won't launch : Error fetching GraphQL query 'TracingHomePageQuery' with variables '{}'

### ISSUE THREAD

**Issue by Aigle-2** [Arize-ai/phoenix#2612]
**Describe the bug**
When lauching the web tracing app (version 3.16.0), it crashes at launch with the following error :

![image](https://github.com/Arize-ai/phoenix/assets/70283408/7c32b47b-aa1f-40dc-abe0-3e3396c56c66)

Snippet used : 

import phoenix as px
from phoenix.trace.langchain import LangChainInstrumentor
session = px.launch_app()
callback_handler = LangChainInstrumentor().instrument()
px.active_session().url

**Comment by RogerHYang** [comment]
@Aigle-2 Can you clear your browser cache and try again? Looks like the cached app using an outdated query.

**Comment by mikeldking** [comment]
@Aigle-2 this is undoubtably a caching issue and we've eliminated caching for now to unblock this. For now we believe this is fixed but you may have to clear your cache in the browser for now. Sorry for the inconvenience.
