### ISSUE TITLE
[projects] Dogfooding feedback

### ISSUE THREAD

**Issue by anticorrelator** [Arize-ai/phoenix#2613]
Feedback from internal dogfooding sessions:
- Confusion about when to use phoenix instrumentors vs openinference instrumentors
- distinction between phoenix components is unclear
  - [x] Concept docs about Phoenix server/collector vs clientside code
- Unclear in documentation that configuration is achieved primarily through env vars
  - [x] Concept documentation for configuration
  - [x] Update notebooks with configuration cells up top with explanation
- configuration environment variables are hard to discover
  - [x] Make an enum to help users discover configuration: e.g. `os.environ[px.env.DEFAULT_PROJECT] = 'XYZ'`

**Comment by mikeldking** [comment]
> Confusion about when to use phoenix instrumentors vs openinference instrumentors
resolved via documentation: https://docs.arize.com/phoenix/tracing/how-to-tracing/trace-a-deployed-app

> distinction between phoenix components is unclear
same as above

> Unclear in documentation that configuration is achieved primarily through env vars

https://docs.arize.com/phoenix/setup/configuration
