### ISSUE TITLE
[BUG] fix intellisense for evaluators

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2638]
Evaluators such as `HallucinationEvaluator` and `ToxicityEvaluator` currently give type errors when instantiated because they have been typed as `LLMEvaluators` even though they do not share the `__init__` signature with the base class.

![Screenshot 2024-03-19 at 4 29 26 PM](https://github.com/Arize-ai/phoenix/assets/15664869/f4cc9a42-7a27-4219-84c5-9cea6023cd5c)

**Comment by mikeldking** [comment]
We should fix this probably soon. Scheduling
