### ISSUE TITLE
Update API reference documentation for `get_qa_with_reference` and `get_retrieved_documents`

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2647]
Update API reference documentation for `get_qa_with_reference` and `get_retrieved_documents` to reflect the addition of `start_time` and `end_time` arguments.

Originally posted by @axiomofjoy in https://github.com/Arize-ai/phoenix/issues/2645#issuecomment-2008548483

**Comment by axiomofjoy** [comment]
Turns out we don't have API reference docs for these functions. Going to punt, we should add when we transition to Sphinx or mkdocs.

**Comment by snagrecha** [comment]
get_qa_with_reference is always None where as get_retrieved_documents works fine.
Always get No spans found.
File "C:\anaconda3\Lib\site-packages\phoenix\evals\classify.py", line 354, in run_evals
    total_records = len(dataframe)
                    ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

Anyone else facing the same issue?

**Comment by axiomofjoy** [comment]
@snagrecha Thanks for reporting. What version of Phoenix are you using? Also, are you able to post a snippet of the code that generated the traces you're looking at to repro?

**Comment by snagrecha** [comment]
> [<img alt="@axiomofjoy" width="20" height="20" src="https://avatars.githubusercontent.com/u/15664869?s=40&amp;u=ca9ef539e7fe76fa54ca63684c0459bc5d8bc6df&amp;v=4">](/axiomofjoy) [axiomofjoy](/axiomofjoy) mentioned this issue [ Jun 7, 2024 ](#ref-issue-2340843723)


Hi, Heres the code being used. (It is a single query to the RAG pipeline which fetches a response. The query is generated via user input on console.)

```
def run_simple_rag():
    app = create_simple_rag_workflow()
    question = input("Enter query: ")
    state = {"question": question}
    response = app.invoke(state)
    print(response['generation'])
    span_df = px.Client().get_spans_dataframe()
    queries_df = get_qa_with_reference(px.Client())
    retrieved_documents_df = get_retrieved_documents(px.Client())

    print('spans_df: \n', span_df)
    print('queries_df: \n', queries_df)
    print('retrieved_documents_df: \n', retrieved_documents_df)
```

Following is the output:

> C:\Users\anaconda3\Lib\site-packages\phoenix\trace\dsl\query.py:746: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
>   df_attributes = pd.DataFrame.from_records(
> No spans found.

> 
> spans_df: 
>                                                                 name  ...           attributes.llm.prompt_template.variables
> context.span_id                                                      ...                                                   
> 5b2d9bc299a7a78b                                          __start__  ...                                               None
> 432d42b97f1f14db                                          Retriever  ...                                               None
> de05635eecefab29  ChannelWrite<retrieve,question,generation,docu...  ...                                               None
> 3f5030063de0cb6a                                           retrieve  ...                                               None
> 5b3d4f2558f82e95                                     PromptTemplate  ...                                               None
> 97cea28505636399                                         ChatOllama  ...                                               None
> d6b33aeba66a6019                                    StrOutputParser  ...                                               None
> b9abcf17de11fdbd                                   RunnableSequence  ...  {'context': ['page_content='RAG-FUSION: A NEW ...
> 
> [8 rows x 23 columns]
> 
> queries_df: 
>  None
> 
> retrieved_documents_df: 
>                                                      context.trace_id  ...                                          reference
> context.span_id  document_position                                    ...                                                   
> 432d42b97f1f14db 0                  3c9587db7dfa3e83ba0959701964783e  ...  RAG-FUSION: A NEW TAKE ON RETRIEVAL-AUGMENTED\...
>                  1                  3c9587db7dfa3e83ba0959701964783e  ...  RAG-Fusion: a New Take on Retrieval-Augmented ...
>                  2                  3c9587db7dfa3e83ba0959701964783e  ...  RAG-Fusion: a New Take on Retrieval-Augmented ...
>                  3                  3c9587db7dfa3e83ba0959701964783e  ...  RAG-Fusion: a New Take on Retrieval-Augmented ...
> 
> [4 rows x 3 columns]
> 

And here is the phoenix output:
![phoenix](https://github.com/Arize-ai/phoenix/assets/65003978/c418acca-59a7-4c7f-9a2b-b4fa5808f103)
