### ISSUE TITLE
[Question] How to get an LLM dashboard?

### ISSUE THREAD

**Issue by hypernovas** [Arize-ai/phoenix#2670]
Hi guys, I just started to explore Phoenix, this is really looking awesome!

I was following the tutorial [notebook](https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb#scrollTo=xEleyLj2xVMh ), and I could not find a good way to go beyond having simple tracing for each RAG based query in llama-index. For instance, the LLM dashboard in this [post](https://arize.com/blog/anyscale-endpoints-code-along/). 

I am curious, if that is just for paid user to get these aggregated tabs?

Thanks!

**Comment by mikeldking** [comment]
hey @hypernovas the tutorial notebook is for [arize-phoenix](https://github.com/Arize-ai/phoenix) - this repo and the blog post is for [Arize the SAAS platform](https://docs.arize.com/arize). Arize also offers tracing and has dashboards and monitor alerts. Phoenix **DEOS NOT** have any paid features, it's all open-source and free to use. Hope that helps!

Thanks for trying Phoenix! Let us know if you have any feature requests like dashbords ;)

**Comment by hypernovas** [comment]
> hey @hypernovas the tutorial notebook is for [arize-phoenix](https://github.com/Arize-ai/phoenix) - this repo and the blog post is for [Arize the SAAS platform](https://docs.arize.com/arize). Arize also offers tracing and has dashboards and monitor alerts. Phoenix **DEOS NOT** have any paid features, it's all open-source and free to use. Hope that helps!
> 
> Thanks for trying Phoenix! Let us know if you have any feature requests like dashbords ;)

Really appreciate it! I will open another issue for such requests.
