### ISSUE TITLE
[ENHANCEMENT] Add eval template text as a field in addition to name, label, score, explanation

### ISSUE THREAD

**Issue by gabe0912** [Arize-ai/phoenix#2685]
**Is your feature request related to a problem? Please describe.**
When I run evals and log them to phoenix, it would be nice to see what the eval template associated with the eval was used

**Describe the solution you'd like**
![Screenshot 2024-03-22 at 6 09 44 PM](https://github.com/Arize-ai/phoenix/assets/4672962/bfa41b44-1b76-43a3-b6d3-fbf6859ead0d)

**Comment by mikeldking** [comment]
Hey @gabe0912 thanks for the issue! Makes sense from a visibility perspective however there are a few things data model wise that this ultimately may not make sense as we are adding tracing for evals eminently. In this case the eval could link to the trace that generated it, which ultimately would help you debug evaluation runs.

Another thing we will be working on is adding metadata about a run. That could ultimately contain the model config and template
