### ISSUE TITLE
Stable version of phoenix

### ISSUE THREAD

**Issue by rajabhupati** [Arize-ai/phoenix#2694]
Do you have a stable version flag for releases? We observed inconsistencies while running through versions?

**Comment by mikeldking** [comment]
@rajabhupati sorry that you were experiencing inconsistencies. Can you describe the stability issues you've been dealing with? In general, we follow, semantic, versioning. However, if inconsistencies occur, it can be due to external factors such as LLM orchestration layers and providers. Let us know.

**Comment by gourav1298** [comment]
Hi, we used the image versions till 3.12.0 and they were not running on EKS deployment and were always giving some type of issue. We were only able to use the image 3.4.1 which is running perfectly fine right now but its doesn't show to token count and other things that it was showing earlier.

**Comment by axiomofjoy** [comment]
@gourav1298 Thanks for the report. If you hit any further issues with the Docker image, please let us know. Can you also tell us, which instrumentation are you using that you don't see token counts for?

**Comment by arizedatngo** [comment]
@mikeldking speaking to @rajabhupati right now

Docs / Code should be aligned and stable. @mikeldking will speak later today on this with you

**Comment by mikeldking** [comment]
@rajabhupati I think I get what you mean by stable in terms of docs. Right now we only have mechanisms by which to have our docs be sync'd with our releases so it always represents the latest but you can always download the docs for a previous version via our releases. https://github.com/Arize-ai/phoenix/releases

**Comment by gourav1298** [comment]
Hi @mikeldking as I stated earlier I was using the version 3.4.1, in which the token count is not showing and we are mainly using Langchain Instrumenter right now, also we tried for newer versions till 3.12.0 but that was giving the following error 
"Cannot query field 'streamingLastUpdatedAt' on type 'Query'".
The current deployment is running in EKS and exposed via a route53 endpoint backed by a load balancer.

Also just wanted to have an idea whether arize-phoenix has a storage backend that we can declare for storing all the traces.

**Comment by mikeldking** [comment]
@gourav1298 

> "Cannot query field 'streamingLastUpdatedAt' on type 'Query'".
This is just a caching miss on our end from what I can tell. We have this fixed in later versions. Can you try resetting your browser cache for phoenix? https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop

> Also just wanted to have an idea whether arize-phoenix has a storage backend that we can declare for storing all the traces.
Yes, it's coming and is top priority for us. We need a bit more time however so right now we recommend downloading and storing your data periodically.

**Comment by gourav1298** [comment]
hi @mikeldking, Can you specify which is the latest version that I can deploy for my use?

**Comment by mikeldking** [comment]
@gourav1298 all git tags correspond to a release (both python and containers):
https://github.com/Arize-ai/phoenix/releases
https://hub.docker.com/r/arizephoenix/phoenix/tags

**Comment by gourav1298** [comment]
Hi @mikeldking, the latest image is running but the token count is still not showing. 
![image](https://github.com/Arize-ai/phoenix/assets/61861138/6d3f0038-3f1d-45f6-a040-fd8d920cc8a4)

**Comment by mikeldking** [comment]
Hey @gourav1298 this is probably un-related to the version of phoenix but rather that not all LLM providers expose tokens when streaming OR in general. We are in the process of building a token counting registry to address this ( https://github.com/Arize-ai/phoenix/issues/2519)

Can you tell us a bit more about the LLM you are using? We may be able to unblock you depending on your deployment.

**Comment by gourav1298** [comment]
We are using databricks serving endpoint.

**Comment by mikeldking** [comment]
> We are using databricks serving endpoint.

Gotcha. We will have to investigate. Thanks for the info.
