### ISSUE TITLE
[ENHANCEMENT] Manual Instrumentation page in documentation is lacking information on how to setup a tracer

### ISSUE THREAD

**Issue by remiconnesson** [Arize-ai/phoenix#2696]
People new to monitoring and who don't use one of the "chosen" framework will most likely fail to manually instrument their code just using the documentation.

https://docs.arize.com/phoenix/tracing/how-to-tracing/custom-spans#acquire-tracer

![image](https://github.com/Arize-ai/phoenix/assets/28846642/169b4c5d-2411-436b-89c8-fe03f2b4918f)

A starter code about how to setup this tracer (for example for a notebook environement) would go a long way in helping people new to monitoring to use `phoenix`

**Comment by mikeldking** [comment]
@remiconnesson love this idea and agree. We will get something in place

**Comment by axiomofjoy** [comment]
@remiconnesson We've added a small example project [here](https://github.com/Arize-ai/phoenix/tree/main/examples/manually-instrumented-chatbot).

**Comment by axiomofjoy** [comment]
@remiconnesson We've updated our documentation using your snippet. Thank you for helping us make docs better!
