### ISSUE TITLE
document recommended practices for running phoenix from the command line

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2711]
New users are hitting issues running `px.launch_app` in a script. We should ensure that the documentation is clear that when running a script, it's recommended to launch Phoenix from the command line.

_Originally posted by @rossdanlm in https://github.com/Arize-ai/phoenix/issues/2710#issuecomment-2025679793_

**Comment by mikeldking** [comment]
This is documented via environments: https://docs.arize.com/phoenix/setup/environments

Any enhancement is welcome! Closing for now @rossdanlm
