### ISSUE TITLE
Add Prometheus environment variable

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2712]
- [x] add environment variable
- [ ] add deprecation warning for command line argument
- [ ] create ticket to remove command line argument in an upcoming sprint
- [x] change the `CMD` in the `Dockerfile`
- [ ] change the `CMD` in the Arize deployment of Phoenix
- [ ] do a full-text search for `--enable-prometheus` to make sure we go everything

_Originally posted by @mikeldking in https://github.com/Arize-ai/phoenix/pull/2708#discussion_r1543063546_

**Comment by axiomofjoy** [comment]
@mikeldking Can you clarify the details of this ticket? Do you want to remove the `--enable-prometheus` command line argument and have an environment variable instead?

**Comment by mikeldking** [comment]
> @mikeldking Can you clarify the details of this ticket? Do you want to remove the `--enable-prometheus` command line argument and have an environment variable instead?

I think this can be an opt-in feature via env-vars. Not every person that deploys phoenix needs prometheus metrics. To make the integration seamless we should just control it via environment variables rather than a launch command

**Comment by axiomofjoy** [comment]
If I understand correctly, the user should be able to decide whether to run the container with Prometheus at runtime, e.g.,

```
docker run -it -e "ENABLE_PROMETHEUS=TRUE" arizephoenix/phoenix:latest
```

**Comment by mikeldking** [comment]
Bumping back in priority.

**Comment by axiomofjoy** [comment]
Fully deprecate prometheus environment variable.
