### ISSUE TITLE
[container] sqlite install

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2721]
sqllite ships with python but not sure if we can more closely control the version in the container. Worth investigating if we can control the version.

**Comment by axiomofjoy** [comment]
I think this issue affects more than just containers. We want to use features from SQLite 3.45, but some versions of Python 3.8 ship with older versions of the SQLite database engine.

```
Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:11:32)
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.43.0'
```

**Comment by axiomofjoy** [comment]
This also affects the current container image, which ships with SQLite v3.40.1. We're going to need to install a custom version of SQLite, either via a third-party library or by packaging SQLite binaries into our own wheels.

**Comment by axiomofjoy** [comment]
I think we need to add [apsw](https://github.com/rogerbinns/apsw/) as a dependency.

- ships with [each version of SQLite](https://github.com/rogerbinns/apsw/releases) contained inside as an isolated dependency
- [supports wheels](https://pypi.org/project/apsw/#files) for the mac, linux, windows
- Unlocks 
- on [Conda Forge](https://github.com/conda-forge/apsw-feedstock)
- no dependencies

**Comment by axiomofjoy** [comment]
Looks like it's been a few years since the Conda feedstock had a release.

https://github.com/conda-forge/apsw-feedstock/issues/48

**Comment by mikeldking** [comment]
Need to determine if JSON binary is worth it
How to get JSON extension installed

**Comment by mikeldking** [comment]
too much work
