### ISSUE TITLE
[BUG] Issue in evaluate_QA_classifications.ipynb

### ISSUE THREAD

**Issue by terry07** [Arize-ai/phoenix#2733]
When I tried to run the evaluate_QA_classifications.ipynb in **Colab**, I get an error trying to execute the next import:

**import phoenix.evals.templates.default_templates as templates**

before downloading benchmark dataset.

Any help here?

Thank you.

**Comment by mikeldking** [comment]
hey @terry07 thanks so much for your report! We shuffled a few things around recently and may have just missed a spot in our notebooks. Will take a look.

**Comment by mikeldking** [comment]
Will be fixed once https://github.com/Arize-ai/phoenix/pull/2736 is merged

**Comment by terry07** [comment]
Thanks for the prompt response and fix.
