### ISSUE TITLE
maybe a [composite](https://docs.sqlalchemy.org/en/20/orm/composites.html) column

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2752]
maybe a [composite](https://docs.sqlalchemy.org/en/20/orm/composites.html) column

_Originally posted by @RogerHYang in https://github.com/Arize-ai/phoenix/pull/2748#discussion_r1551808751_

**Comment by RogerHYang** [comment]
composite column turns out to be not very useful. closing
