### ISSUE TITLE
[sessions][docs] how-to

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2758]

**Comment by axiomofjoy** [comment]
Needs scoping for sessions, users, metadata, tags.

**Comment by axiomofjoy** [comment]
Another question we have here is whether the new context managers should be imported and aliased into `phoenix.trace`. This affects where we plan to put this documentation. @mikeldking

**Comment by mikeldking** [comment]
> Another question we have here is whether the new context managers should be imported and aliased into `phoenix.trace`. This affects where we plan to put this documentation. @mikeldking 
> 
> 
> 
> I.e., do we want the following?
> 
> 
> 
> ```
> 
> from phoenix.trace import using_session, using_user
> 
> ```

Probably not, as sessions are not really a notebook thing
