### ISSUE TITLE
[persistence][spike] Target Postgres as a persistence db

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2793]

**Comment by mikeldking** [comment]
The connections now work using pip install -e .[pg]

connections such as postgresql://@localhost:5432/postgres?user=postgres&password=mysecretpassword

are accepted.

You can spin up an instance via:

```
docker run --name postgres_container -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 -v postgres_data:/var/lib/postgresql/data postgres:15.6
```

**Comment by mikeldking** [comment]
closing since the connection side of things is done.

**Comment by axiomofjoy** [comment]
@mikeldking Did you mean to close this issue?
