### ISSUE TITLE
[BUG] phoenix only loads last trace and crashes on retriever and llm span. 

### ISSUE THREAD

**Issue by MaxOng94** [Arize-ai/phoenix#2804]
**Describe the bug**

Followed the documentation for saving and loading traces in specified directory in the documentation, but during loading of traces only the last query is displayed, and crash when clicking on retreiver and llm span. 
Error details below

**To Reproduce**
```
import os

# Specify and Create the Directory for Trace Dataset

# in current directory 
directory = './my_saved_traces'
os.makedirs(directory, exist_ok=True)

# Save the Trace Dataset
my_traces = px.Client().get_trace_dataset().save(directory=directory)

px.launch_app(trace=px.TraceDataset.load(my_traces, directory="./my_saved_traces/"))
```

**Expected behavior**
All traces executed previously to be loaded

**Screenshots**

Error for retriever span
![error screen shot](https://github.com/Arize-ai/phoenix/assets/52341959/7abd1e10-1331-45ac-af3a-047c897de1f6)

Error for llm span
![image](https://github.com/Arize-ai/phoenix/assets/52341959/2839dd73-43aa-46d0-8db0-fd5d7859b264)

**Environment (please complete the following information):**
 - OS: Windows 11 Home
 - Notebook Runtime [Jupyter notebook]
 - Browser: Chrome
 - Version: '3.15.0'

**Comment by RogerHYang** [comment]
Hi @MaxOng94 can you try upgrading to our latest release: v3.19.4? I believe this was resolved a while back. (Make sure to clear your browser cache after upgrade.)
