### ISSUE TITLE
[ENHANCEMENT] Add explanations as a column in trace view

### ISSUE THREAD

**Issue by camyoung93** [Arize-ai/phoenix#2827]
**Is your feature request related to a problem? Please describe.**
It takes 4 clicks to review a single eval on the LLM span. This becomes very annoying when I'm developing an eval to make sure that its working as expected across many traces.

**Describe the solution you'd like**
I would like to be able to setup a view where I have my prompt, response and eval explanation all in a single table view so I can see all the relevant data without clicking around.

**Describe alternatives you've considered**
I currently merge the spans + eval df to have a custom view like below:

![Screenshot 2024-04-09 at 11 01 38 AM](https://github.com/Arize-ai/phoenix/assets/12156032/92d04245-6ecb-41ef-b822-70738878a5c8)

**Comment by axiomofjoy** [comment]
Thanks for the feedback @camyoung93. Makes sense.
