### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by arianpasquali** [Arize-ai/phoenix#2872]
**Describe the bug**
Follownig the steps on [llama_index_search_and_retrieval_tutorial notebook](https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/llama_index_search_and_retrieval_tutorial.ipynb#scrollTo=epu7BaHEDmf1) it fails at px.Inferences.from_open_inference.

Following 
**To Reproduce**
1. Go to ['...'](https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/llama_index_search_and_retrieval_tutorial.ipynb#scrollTo=epu7BaHEDmf1)
2. Execute all the cells
3. At cell `query_ds = px.Inferences.from_open_inference(query_df)` it fails

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-27-7a9a65c55b9c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 query_ds = px.Inferences.from_open_inference(query_df)

AttributeError: type object 'Inferences' has no attribute 'from_open_inference'
```

**Environment (please complete the following information):**
 - Notebook Runtime : Google Colab

**Comment by axiomofjoy** [comment]
Thanks for flagging @arianpasquali
