### ISSUE TITLE
[ENHANCEMENT] Support for Multi-Modal RAG Tracing and Evaluation

### ISSUE THREAD

**Issue by hakantekgul** [Arize-ai/phoenix#2895]
It would be great if Phoenix supported Multi-Modal applications, such as a Multi-Modal RAG. There are a couple of features to consider in order to fully support this: 

MM RAG Tracing: 
- It would be very helpful if images were rendered on Phoenix UI, whether the image exists in a response, context, or response. Given image paths, rendering the images would provide a lot of visibility. 
- I think this is already supported but testing the whole framework against LMMs such as GPT-4V would be helpful. 
Example screenshot from Phoenix: 

![Screenshot 2024-04-15 at 3 51 08 PM](https://github.com/Arize-ai/phoenix/assets/14350521/3cf9729a-c378-44c3-9a56-577e63381dd8)

MM RAG Evaluation: 
- Having Multi-Modal evaluators using LMMs as a Judge could be very helpful. Given image_paths, reference text etc, having MultiModalRelevancy and MultiModalHallucination evals etc. under Phoenix evals could bring a lot of value. 
- Right now, LlamaIndex provides MM Evals: 

![Screenshot 2024-04-15 at 3 51 27 PM](https://github.com/Arize-ai/phoenix/assets/14350521/7f910ef0-6df4-4313-a4f3-d1aff08ef9c5)

**Comment by axiomofjoy** [comment]
Thanks @hakantekgul

**Comment by mikeldking** [comment]
Hey @hakantekgul appreciate the feedback. We probably have a bit too much on our plate right now to tackle at the current moment but keep us honest on the priority of this.

**Comment by stefanadelbert** [comment]
Adding support for working with multimodal models would be a huge step forward, e.g. being able to visualise images in prompt inputs (base64 encoded PNG or JPEG) in the Phoenix UI Trace Details. rather than seeing the base64 encoded text as shown in this screenshot.

![image](https://github.com/user-attachments/assets/29548a2c-9e44-4f57-b757-44d04db431d7)

**Comment by mikeldking** [comment]
> Adding support for working with multimodal models would be a huge step forward, e.g. being able to visualise images in prompt inputs (base64 encoded PNG or JPEG) in the Phoenix UI Trace Details. rather than seeing the base64 encoded text as shown in this screenshot.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/29548a2c-9e44-4f57-b757-44d04db431d7)

Soon:)
