### ISSUE TITLE
[BUG] Blank dashboard when loading via notebook or terminal

### ISSUE THREAD

**Issue by GeorgeDoughty** [Arize-ai/phoenix#2912]
**Describe the bug**
Cannot visualise the Phoenix dashboard when loading via script, notebook or terminal. The link exists but just loads blank.

I have tried changing the port but this doesn't fix it either.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `python -m phoenix.server.main serve`
2. Load http://localhost:6006
3. Blank page

**Expected behavior**
A dashboard to load. This is not changed by logging traces either.

**Screenshots**
Terminal:
![image](https://github.com/Arize-ai/phoenix/assets/74251029/6f85f125-d98c-4530-890c-2471308d9ca2)

Dashboard:
![image](https://github.com/Arize-ai/phoenix/assets/74251029/47714df2-dd2d-48d8-89b9-f125a9c8193b)

**Environment (please complete the following information):**
 - OS: Windows
 - Python Version: 3.11.5
 - Browser chrome
 - Version 3.19.4

**Additional context**
<details>
  <summary>pip freeze output</summary>

```
aiohttp==3.9.3
aiosignal==1.3.1
alembic==1.13.1
altair==5.3.0
annotated-types==0.6.0
anyio==4.3.0
arize-phoenix==3.19.4
arize-phoenix-evals==0.6.1
asgiref==3.8.1
attrs==23.2.0
azure-core==1.30.1
azure-storage-blob==12.19.1
backoff==2.2.1
bcrypt==4.1.2
black==24.3.0
blinker==1.7.0
build==1.2.1
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
chroma-hnswlib==0.7.3
chromadb==0.4.22
click==8.1.7
cloudpickle==3.0.0
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.2.1
cryptography==42.0.5
cycler==0.12.1
Cython==0.29.37
dataclasses-json==0.6.4
Deprecated==1.2.14
distro==1.9.0
docker==7.0.0
entrypoints==0.4
fastapi==0.109.1
filelock==3.13.4
Flask==3.0.3
flatbuffers==24.3.25
fonttools==4.51.0
frozenlist==1.4.1
fsspec==2024.3.1
gitdb==4.0.11
GitPython==3.1.43
google-auth==2.29.0
googleapis-common-protos==1.63.0
graphql-core==3.2.3
greenlet==3.0.3
grpcio==1.62.1
h11==0.14.0
hdbscan==0.8.33
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
huggingface-hub==0.22.2
humanfriendly==10.0
idna==3.6
importlib-metadata==7.0.0
importlib_resources==6.4.0
iniconfig==2.0.0
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.3
joblib==1.4.0
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
kubernetes==29.0.0
langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.23
langchain-openai==0.0.6
langsmith==0.0.87
lark==1.1.9
llvmlite==0.42.0
loguru==0.7.2
Mako==1.3.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.1
matplotlib==3.8.4
mdurl==0.1.2
mlflow==2.10.2
mmh3==4.1.0
monotonic==1.6
mpmath==1.3.0
multidict==6.0.5
mypy-extensions==1.0.0
networkx==3.3
nltk==3.8.1
numba==0.59.1
numpy==1.26.4
oauthlib==3.2.2
onnxruntime==1.17.1
openai==1.16.2
openinference-instrumentation==0.1.1
openinference-instrumentation-langchain==0.1.14
openinference-instrumentation-llama-index==1.2.1
openinference-instrumentation-openai==0.1.4
openinference-semantic-conventions==0.1.5
opentelemetry-api==1.24.0
opentelemetry-exporter-otlp==1.24.0
opentelemetry-exporter-otlp-proto-common==1.24.0
opentelemetry-exporter-otlp-proto-grpc==1.24.0
opentelemetry-exporter-otlp-proto-http==1.24.0
opentelemetry-instrumentation==0.45b0
opentelemetry-instrumentation-asgi==0.45b0
opentelemetry-instrumentation-fastapi==0.45b0
opentelemetry-proto==1.24.0
opentelemetry-sdk==1.24.0
opentelemetry-semantic-conventions==0.45b0
opentelemetry-util-http==0.45b0
overrides==7.7.0
packaging==23.2
pandas==2.2.0
pathspec==0.12.1
pillow==10.3.0
platformdirs==4.2.0
pluggy==1.4.0
posthog==3.5.0
protobuf==4.25.3
psutil==5.9.8
pulsar-client==3.4.0
pyarrow==15.0.2
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydantic==2.6.4
pydantic_core==2.16.3
pydeck==0.8.1b0
Pygments==2.17.2
pynndescent==0.5.12
pyparsing==3.1.2
PyPika==0.48.9
pyproject_hooks==1.0.0
pyreadline3==3.4.1
pytest==8.0.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2023.4
pywin32==306
PyYAML==6.0.1
querystring-parser==1.2.4
referencing==0.34.0
regex==2023.12.25
requests==2.31.0
requests-oauthlib==2.0.0
rich==13.7.1
rpds-py==0.18.0
rsa==4.9
safetensors==0.4.2
scikit-learn==1.4.2
scipy==1.13.0
sentence-transformers==2.2.2
sentencepiece==0.2.0
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
sortedcontainers==2.4.0
SQLAlchemy==2.0.29
sqlparse==0.4.4
starlette==0.35.1
strawberry-graphql==0.208.2
streamlit==1.31.1
sympy==1.12
tenacity==8.2.3
threadpoolctl==3.4.0
tiktoken==0.6.0
tokenizers==0.15.2
toml==0.10.2
toolz==0.12.1
torch==2.2.2
torchvision==0.17.2
tornado==6.4
tqdm==4.66.2
transformers==4.39.3
typer==0.12.3
typing-inspect==0.9.0
typing_extensions==4.11.0
tzdata==2024.1
tzlocal==5.2
umap-learn==0.5.6
urllib3==2.2.1
uvicorn==0.27.1
validators==0.28.0
waitress==2.1.2
watchdog==4.0.0
watchfiles==0.21.0
websocket-client==1.7.0
websockets==12.0
Werkzeug==3.0.2
win32-setctime==1.1.0
wrapt==1.16.0
yarl==1.9.4
zipp==3.18.1 
```

</details>

**Comment by axiomofjoy** [comment]
Hey @GeorgeDoughty, can you try clearing your browser cache?

**Comment by mikeldking** [comment]
@GeorgeDoughty interesting, thanks for the issue. Since I don't have a native windows machine it's a bit difficult for me to troubleshoot. Would it be possible for you to send some screenshots or logs from your browser? Right click and say "inspect" - there may be errors there that might help us understand why you are not getting web content.

P.S. there's an alternate way of running the server just via a container. That might yield better results? https://docs.arize.com/phoenix/setup/environments#container

**Comment by GeorgeDoughty** [comment]
> Hey @GeorgeDoughty, can you try clearing your browser cache?

@axiomofjoy tried this but still get the blank dashboard.

> @GeorgeDoughty interesting, thanks for the issue. Since I don't have a native windows machine it's a bit difficult for me to troubleshoot. Would it be possible for you to send some screenshots or logs from your browser? Right click and say "inspect" - there may be errors there that might help us understand why you are not getting web content.

@mikeldking here are some screenshots. Please let me know if you need any more detail.

![image](https://github.com/Arize-ai/phoenix/assets/74251029/07a4ecc0-5e15-42d1-8953-3d4db625341d)
![image](https://github.com/Arize-ai/phoenix/assets/74251029/2de33029-51b5-49aa-90a2-ba14ce8b4ccc)
![image](https://github.com/Arize-ai/phoenix/assets/74251029/da4738a2-7aa8-4349-a93f-29d960fc0a3c)

> P.S. there's an alternate way of running the server just via a container. That might yield better results? https://docs.arize.com/phoenix/setup/environments#container

Using the docker container works! Thanks both for your help on this!

![image](https://github.com/Arize-ai/phoenix/assets/74251029/55b205df-4778-45b3-a428-39ef664bf2fd)

**Comment by mikeldking** [comment]
@GeorgeDoughty so glad you are unblocked! 

Very strange - it appears as though you don't have "compiled" js bundles and the server is responding with plain HTML. Wondering if you had compiled phoenix from source? If so I think the JS bundles may have not been compiled (which flags that this step is now missing in our https://github.com/Arize-ai/phoenix/blob/main/DEVELOPMENT.md). In any case thanks so much for the screenshots. Super helpful.
