### ISSUE TITLE
create an `arize-phoenix-client` package

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2914]
Some users want to be able to programmatically pull spans and traces from Phoenix without having the entire `arize-phoenix` package installed with all its dependencies. To support these users, it would be helpful to break out the client into its own `arize-phoenix-client` package.

**Comment by mikeldking** [comment]
moving to the #2017 project

**Comment by mikeldking** [comment]
Note that since most of the API should be OpenAPI compliant - we should strive to auto-generate as much of the client as possible

**Comment by axiomofjoy** [comment]
Looks interesting https://github.com/openapi-generators/openapi-python-client

**Comment by mikeldking** [comment]
Ideally this would track the same version as the server

**Comment by axiomofjoy** [comment]
investigate generating python client off of openapi spec

**Comment by axiomofjoy** [comment]
investigate stainless api

**Comment by axiomofjoy** [comment]
https://github.com/openapi-generators/openapi-python-client

**Comment by axiomofjoy** [comment]
collect data on semver ranges for major llm providers to see if there are any compatibility issues

**Comment by axiomofjoy** [comment]
investigate how to prevent pydantic version collisions

**Comment by axiomofjoy** [comment]
Punting on this issue for now.
