### ISSUE TITLE
Add Env Parameter for Prefix for the app

### ISSUE THREAD

**Issue by Townsheriff** [Arize-ai/phoenix#2918]
**Is your feature request related to a problem? 
When trying to run phoenix behind load balancer with routing using endpoints it is impossible to do so.

For example web app: www.app.com having auth layer and then underlying services under routes /backend /phoenix and /* for frontend. It is not possible to change Phoenix routing path.

**Describe the solution you'd like**
Using env variable for example ROUTE_PREFIX or BASE_URL we could set to "/phoenix" and the all requests would go towards it, for example www.app.com/phoenix/graphql would point to phoenix backend or www.app.com/phoenix would point towards phoenix frontend.

**Describe alternatives you've considered**
Running phoenix service under separate domain name.

PS

Nothing to do with app.com, its just an example domain.

**Comment by axiomofjoy** [comment]
Thanks @Townsheriff for the issue. @mikeldking Any thoughts here?

**Comment by Townsheriff** [comment]
Thank you will take a look!

**Comment by sbachstein** [comment]
Has there been an effort to introduce the root path parameter, already?

**Comment by axiomofjoy** [comment]
@sbachstein Not yet, but please feel free to upvote the issue.

**Comment by sbachstein** [comment]
I will give it a go then and will come up with a PR soon.

**Comment by mikeldking** [comment]
thanks @sbachstein ! 
cc @anticorrelator who will help you get it merged!
