### ISSUE TITLE
improve error messages for `/v1/traces`

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#2950]
When users attempt to manually instrument their applications and provide an incorrect semantic convention, the client receives an obscure error message:

```
Transient error Internal Server Error encountered while exporting span batch, retrying in 1s.
```

We should ensure that a more helpful error message is returned to the client, e.g.,

```
ValueError: 'OPENINFERENCESPANKINDVALUES.CHAIN' is not a valid SpanKind
```

**Comment by mikeldking** [comment]
I think this got relaxed as per @RogerHYang - can we confirm?

**Comment by mikeldking** [comment]
Bump, still an issue @RogerHYang ?

**Comment by RogerHYang** [comment]
no longer an issue

<img width="530" alt="Screenshot 2024-05-14 at 10 34 25 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/cdfeb281-47d1-44d3-ac6b-9f2b21c922a0">
