### ISSUE TITLE
[BUG] get_spans start and end times are in user timezones whereas in phoenix the filtering is done in UTC

### ISSUE THREAD

**Issue by gabe0912** [Arize-ai/phoenix#3024]
start_time and end_time filter on get_spans() transforms to iso_time which is in the user's timezone. The Phoenix UI also shows it on the users timezone, however, the filtering uses UTC by the looks of it.

**Comment by axiomofjoy** [comment]
@gabe0912 I assume we're talking about the `get_spans_dataframe` method on `phoenix.Client`?

**Comment by gabe0912** [comment]
@axiomofjoy https://github.com/Arize-ai/phoenix/blob/main/src/phoenix/session/client.py#L63 would be the root
