### ISSUE TITLE
[BUG] can't run phoenix on a remote machine for tracing as well as viewing. 

### ISSUE THREAD

**Issue by btebbutt** [Arize-ai/phoenix#3067]
I'm wanting to host a phoenix app using fly.io so that the tracing and viewing is handled separately. I forked the phoenix repo , and then ran fly launch inside the phoenix dir , which automatically picks up the dockerfile and deploys it making sure the exposed port is 6060 : 

[http_service]
  internal_port = 6006
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

the deployed site works and I can see the UI . 

Then in my Jupyter notebook I set this env variable : 

os.environ["PHOENIX_COLLECTOR_ENDPOINT"] = "https://host-address:6006"

When I run : 

```
endpoint = "http://127.0.0.1:6006/v1/traces"
resource = Resource(attributes={})
tracer_provider = trace_sdk.TracerProvider(resource=resource)
span_otlp_exporter = OTLPSpanExporter(endpoint=endpoint)
tracer_provider.add_span_processor(
    SimpleSpanProcessor(span_exporter=span_otlp_exporter)
)

trace_api.set_tracer_provider(tracer_provider=tracer_provider)
DSPyInstrumentor().instrument()
```

I can see the UI on the local address. But When I run :

```
endpoint = "http://host-address:6006/v1/traces"
resource = Resource(attributes={})
tracer_provider = trace_sdk.TracerProvider(resource=resource)
span_otlp_exporter = OTLPSpanExporter(endpoint=endpoint)
tracer_provider.add_span_processor(
    SimpleSpanProcessor(span_exporter=span_otlp_exporter)
)

trace_api.set_tracer_provider(tracer_provider=tracer_provider)
DSPyInstrumentor().instrument()
```

the traces are not sent to the remote machine.

**Comment by btebbutt** [comment]
No luck unfortunately with all the environment settings . 

Unless I need to change anything explicitly in these 3 files : 

[src/phoenix/trace/exporter.py](https://github.com/Arize-ai/phoenix/blob/main/src/phoenix/trace/exporter.py)
[src/phoenix/trace/otel.py](https://github.com/Arize-ai/phoenix/blob/main/src/phoenix/trace/otel.py)
[src/phoenix/server/api/routers/trace_handler.py](https://github.com/Arize-ai/phoenix/blob/main/src/phoenix/server/api/routers/trace_handler.py)

**Comment by mikeldking** [comment]
Hi @btebbutt ! Thanks for trying out the project! It's a bit difficult for me to tell what's going on from the above but wanted to link you to working examples that we have:

Using containers:
https://github.com/Arize-ai/openinference/tree/main/python/examples/dspy-rag-fastapi

Using a notebook:
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/dspy_tracing_tutorial.ipynb

The docs for DSPy can be found here.
https://docs.arize.com/phoenix/tracing/how-to-tracing/instrumentation/auto-instrument-python/dspy

Do you see any error logs when running your code?

**Comment by btebbutt** [comment]
hi @mikeldking thanks for replying and helping me out. Basically just trying to host a phoenix app which runs the front end , as well as tracing the llm logic from my local machine. 

So far I am simply using the dockerfile from the phoenix repo which is exposing port 6006 . 

Then with my fly.io toml file i set these params : 

[http_service]
  internal_port = 6006
  force_https = False
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

this gives me a a host name : https://phoenix-holy-meadow-7464.fly.dev

which is displaying the front end correctly. 

I can change my ip address and domain later, so happy to share this information while I am getting it to work. 

then in my local notebook , I set my environment variables : 

![image](https://github.com/Arize-ai/phoenix/assets/55270549/27e49939-6796-42ae-96d7-d0905c39e941)

then I run this code 

![image](https://github.com/Arize-ai/phoenix/assets/55270549/cd30a5b0-4f10-424f-a3da-566a945fe422)

which causes this error : 


`⚠️ PHOENIX_COLLECTOR_ENDPOINT is set to https://66.241.125.152:6006/.
⚠️ This means that traces will be sent to the collector endpoint and not this app.
⚠️ If you would like to use this app to view traces, please unset this environmentvariable via e.g. `del os.environ['PHOENIX_COLLECTOR_ENDPOINT']` 
⚠️ You will need to restart your notebook to apply this change.
ERROR:    [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/uvicorn/server.py", line 162, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/base_events.py", line 1491, in create_server
    infos = await tasks.gather(*fs)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/base_events.py", line 1423, in _create_server_getaddrinfo
    infos = await self._ensure_resolved((host, port), family=family,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/base_events.py", line 1419, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 761, in run_closure
    _threading_Thread_run(self)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/uvicorn/server.py", line 84, in _serve
    await self.startup(sockets=sockets)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/uvicorn/server.py", line 172, in startup
    sys.exit(1)
SystemExit: 1
💥 Phoenix failed to start. Please try again (making sure that port 6060 is not occupied by another process) or file an issue with us at https://github.com/Arize-ai/phoenix
Overriding of current TracerProvider is not allowed
Attempting to instrument while already instrumented`


Thanks again for your help.

**Comment by mikeldking** [comment]
@btebbutt looking at your setup you should set 
```python
OTLPSpanExporter(endpoint="https://phoenix-holy-meadow-7464.fly.dev/v1/traces")
# or
OTLPSpanExporter(endpoint="https://66.241.125.152:6006/v1/traces") # I cannot verify this
```

Note that you do not have to call `launch_app` from within your notebook if phoenix is running remotely

Let me know if either of the above work out!

**Comment by btebbutt** [comment]
@mikeldking  yes, i actually just noticed the v1 trace missing also .

right now running the block like this: 

 
![image](https://github.com/Arize-ai/phoenix/assets/55270549/5fd02681-26b2-448c-ae60-41f7a1787ec8)


runs with no error, but unfortunately no traces are seen on the hosted site after I run some llm code that I is traced properly when I run it locally. 

Thanks!

**Comment by mikeldking** [comment]
@btebbutt were you able to try `https://phoenix-holy-meadow-7464.fly.dev/v1/traces`? Looks like you may have taken it down? Inside your fly.io network it might not have https?

>  I run some llm code that I is traced properly when I run it locally.

Just wanted to make sure you are running `dspy` code as part of this step? Note that you need to run the instrumentation code BEFORE initializing any of your dspy code is initialized

If you join our slack community I may be able to help you more easily. (https://join.slack.com/t/arize-ai/shared_invite/zt-1px8dcmlf-fmThhDFD_V_48oU7ALan4Q)

**Comment by btebbutt** [comment]
@mikeldking  Hi , yes I was experimenting with some of the config on the deployment side to see if it was an error on that end, but I don't think it is. 

yeh I am , and I have already got the traces working perfectly with the same code using the local addresses, so It's not an issue with the LLM code. 

Ok , I'll join the slack and we can discuss further. Cheers.

**Comment by axiomofjoy** [comment]
This issue was resolved, solution below. Thanks for using Phoenix @btebbutt!

> I managed to get it working by making the collector end point the host name address directly rather than using the ip address. Not sure why that was the cause, but I appreciate your help anyway .

**Comment by sraibagiwith100x** [comment]
@axiomofjoy 
We are having the same issue all of a sudden since a few days ago 
Posted about it here in the community 
https://arize-ai.slack.com/archives/C04R3GXC8HK/p1715797220460109
![CleanShot 2024-05-15 at 20 46 50](https://github.com/Arize-ai/phoenix/assets/163024508/9baa8e43-7010-4f50-8e22-ef79e14ee4b9)

**Comment by axiomofjoy** [comment]
Thanks @sraibagiwith100x, we'll follow up with you in Slack.

**Comment by sraibagiwith100x** [comment]
The solution for us was : 

> Making the setup of the instrumentation, the very first import we make solved this issue and we're seeing traces now!
