### ISSUE TITLE
[BUG] auto-naming of unique index in sqlite still doesn't follow `target_metadata`

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#3092]
<img width="270" alt="Screenshot 2024-05-06 at 6 31 10 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/def67c1e-f790-4b10-a53c-e7809c4f4297">

**Comment by axiomofjoy** [comment]
The index does not follow naming conventions in SQLite, but the constraint does, I think.

![Screenshot 2024-05-06 at 8 47 43 AM](https://github.com/Arize-ai/phoenix/assets/15664869/b54e8587-d8fa-4355-9d48-9b05bd371393)

**Comment by axiomofjoy** [comment]
see [this comment](https://sqlite.org/forum/forumpost/9e98da54f1f3b997)

**Comment by RogerHYang** [comment]
OK thanks. Maybe we should rename it manually then? So that the names are consistent with postgres, which does adhere to the auto-naming.

<img width="305" alt="Screenshot 2024-05-06 at 9 07 06 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/4fda9016-ed76-4617-a72d-7fb970ab5d62">
