### ISSUE TITLE
[ENHANCEMENT] Provide a Non-root Container Image

### ISSUE THREAD

**Issue by sbachstein** [Arize-ai/phoenix#3094]
**Is your feature request related to a problem? Please describe.**
Running container images as a non-root user is considered best practice in order to avoid security vulnerabilities. Also, a Kubernetes cluster with the "restricted" policy enabled actually requires running containers as a non-root user. This is not possible at the moment since there are filesystem areas in the container filesystem that are only writeable by the root user.
For a restricted Kubernetes cluster, therefore, the official image cannot be used and must be modified instead.

**Describe the solution you'd like**
The official container image should run as a non-root user by default.

**Describe alternatives you've considered**
Only alternative is modifying the Dockerfile and building an own container image.

**Additional context**
As far as I can see, running the Phoenix container image as root is not required and switching to a non-root user should, therefore, be preferred for security reasons.

**Comment by axiomofjoy** [comment]
@sbachstein Thanks for flagging.

**Comment by axiomofjoy** [comment]
@sbachstein Can you try out `arize-phoenix==3.25.0` and let us know if that works?

**Comment by sbachstein** [comment]
@axiomofjoy Works like a charm, thank you!

**Comment by axiomofjoy** [comment]
@sbachstein Starting in `version-4.2.0`, the default image of Phoenix will run as root. We will also be offering a `nonroot`. This will be out soon, stay tuned.
