### ISSUE TITLE
[BUG] Incorrect input layout for langchain ChatOllama LLM

### ISSUE THREAD

**Issue by feishen** [Arize-ai/phoenix#3106]
**Describe the bug**
I use langchain ChatOllama with a system message and a human message. However, the input of the LLM mixed them together, instead of displaying separate sections for each message. 
![image](https://github.com/Arize-ai/phoenix/assets/654845/a73aff2b-84da-40f0-90c9-f6f3b4ea068e)

langchain version: 0.1.17
arize-phoenix version: 3.24.0
llama-index-callbacks-arize-phoenix version: 0.1.5

code sample:

LangChainInstrumentor().instrument()

llm = ChatOllama(model="mistral:v0.2")
messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=routing_prompt.format(input=prompt))
    ]

result = llm.invoke(messages).content

**Comment by mikeldking** [comment]
Hey @feishen thanks for the ticket! LangChain combines the system and user templates into a single prompt sometimes for some reason - we'll look to make this more user friendly in the future. Thanks for the feedback!

**Comment by feishen** [comment]
thank you. @mikeldking looking forward to get it fixed.
