### ISSUE TITLE
[BUG] Error while installing "llama-index-callbacks-arize-phoenix>1.3.0"

### ISSUE THREAD

**Issue by pavanjava** [Arize-ai/phoenix#3117]
**Describe the bug**
As per the documentation in order to integrate the llamaindex with arize-phoenix we have install 
`llama-index-callbacks-arize-phoenix>1.3.0`, but ultimately, we end up in the 
![Screenshot 2024-05-08 at 1 01 54 PM](https://github.com/Arize-ai/phoenix/assets/25398886/7929525e-a45f-4865-831a-f5087b37e02a)

`ERROR: Could not find a version that satisfies the requirement llama-index-callbacks-arize-phoenix>1.3.0 (from versions: 0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)
ERROR: No matching distribution found for llama-index-callbacks-arize-phoenix>1.3.0
`
**To Reproduce**
1. create a simple project with independent venv with below dependency in requirements.txt
2. `llama-index-callbacks-arize-phoenix>1.3.0`
3. run `pip install -r requirements.txt`

<img width="1337" alt="Screenshot 2024-05-08 at 1 10 13 PM" src="https://github.com/Arize-ai/phoenix/assets/25398886/1dbd0c0e-6c6d-45c4-9a1a-6967285607a4">
error as below

**Expected behavior**
Expected no error and the dependency should be installed

**Screenshots**
Attached are the screenshots for your reference

**Environment (please complete the following information):**

 - OS: MacOS v14.1.1
 - Python 3.11 

**Additional context**
I think the version it self is wrongly mention in documentation infact it should be `>0.1.3` instead of `>1.3.0`
![Screenshot 2024-05-08 at 1 02 40 PM](https://github.com/Arize-ai/phoenix/assets/25398886/932e9ad0-944e-4d37-a67f-f196c740e699)

**Comment by axiomofjoy** [comment]
@pavanjava Thanks for flagging. You're right, there was an error in the documentation. We have fixed.
