### ISSUE TITLE
Hello, i found a bug about port and one issue for langchain with langserve

### ISSUE THREAD

**Issue by 1100111GTH** [Arize-ai/phoenix#3118]
**Describe the bug**
I'm deploying langchian with langchain serve command and it's not working, the webui show nothing, the cli tell me failed to export. another problem is the env PHOENIX_PORT also not working, I tried os.environment on python, it's tell me expect str not int, and I make int type to str, then start langServe, the port still be 6006.

**To Reproduce**
1. start your xx.py using langchain serve command
2. talk to your llm with gradio webui
3. see your phoenix webui page
4. nothing happend

**Expected behavior**
Tracing.

**Screenshots**
![CleanShot 2024-05-08 at 16 42 11](https://github.com/Arize-ai/phoenix/assets/154310050/2f4035e6-0835-4af5-88ab-849f121b38fe)

**Environment (please complete the following information):**
 - ubuntu 20.04
 - Chrome
 - lastest Version

**Comment by 1100111GTH** [comment]
```
session = px.launch_app(port=7007)
from phoenix.trace.langchain import LangChainInstrumentor
LangChainInstrumentor().instrument()
```

This this the code what i using with langchian script. i'm not sure what i missing.

**Comment by 1100111GTH** [comment]
i'm using langserve to provide api for gradio

**Comment by axiomofjoy** [comment]
> sorry about this bug report, i find something with opentelemetry can be work through. by the way, i think your doc is kind be difficult to read, few samily things shows many times. but i need thank you guy's project fixed what i need ( if i can use opentelemetry to save data localy will be better )

@1100111GTH Thanks for the feedback.

We are days away from releasing persistence of trace data to SQLite or PostgreSQL backends. Please check back soon.
