### ISSUE TITLE
[Question] Canonical way to keep app alive

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [Arize-ai/phoenix#3153]
Hi Phoenix,

I have a rather simple question. Is there a canonical way to keep the Phoenix app alive once my Python script is finished running?

This is my current approach which is a bit hacky:

```python
px.launch_app()
# ...
# do stuff
# ...
try:
    while True:
        time.sleep(1)
except (KeyboardInterrupt, asyncio.exceptions.CancelledError):
    print("\nExiting loop.")
```

I feel like there should be a better way, since the Phoenix app is the whole point of this repository.

Thanks!

**Comment by axiomofjoy** [comment]
@DamianB-BitFlipper We usually recommend people run Phoenix from the command line via `python -m phoenix.server.main serve`.

**Comment by DamianB-BitFlipper** [comment]
Thanks!
