### ISSUE TITLE
[BUG] - GPT-4o OpenInference Tracer Error

### ISSUE THREAD

**Issue by hakantekgul** [Arize-ai/phoenix#3191]
Hi, we've started testing the new Open AI model, GPT-4o, and seem to have this error occur on each input. All other models we use via Langchain seem completely fine except for this one.

`Error in OpenInferenceTracer.on_chain_error callback: TracerException('No indexed run ID b3ea8d32-1c2e-4817-b510-c441faffd09c.')`

The traces are still coming up in Arize and this isn't a blocker for us, but it would be nice to get rid of this warning to keep our logs clean. Would you mind looking into this? Please let me know if you need any additional information from our side.

**Comment by axiomofjoy** [comment]
@hakantekgul Can you send a snippet to reproduce?

**Comment by hakantekgul** [comment]
Hi 
, just a heads up, we were able to resolve the issue. It was a Langchain dependency issue. GPT-4o requires a new version of the Tiktoken package to support a new BPE encoding. Bumping the Tiktoken version from 0.6.0 -> 0.7.0 fixed the issu
