### ISSUE TITLE
[BUG] env don't refresh intime

### ISSUE THREAD

**Issue by arthur-kuo** [Arize-ai/phoenix#3207]
I have two project "A" and "B" in test environment, when I set PHOENIX_PROJECT_NAME = A and send request,  Traces dashboard of phoenix shows that project A got a new flow.

But when I change PHOENIX_PROJECT_NAME into "B" and send request  immediately, the dashboard shows that project A got a new flow again.

After like 10 min, I  send request again , then it will successfully record this flow into project B.

It's like latency of receiving new env argument, maybe it's because some object is holding the elder env argument in the current connection? connection pool? 

Sorry, it's my first time to ask something on github.

**Comment by anticorrelator** [comment]
Hi @arthur-kuo! Thank you so much for trying out Phoenix. We don't support dynamically changing the project after it's been set, except if you're running in a Notebook environment. In those cases we provide the `using_project` context manager that can make it easy to separate different pieces of your notebook into different projects.

**Comment by arthur-kuo** [comment]
Got it, thank you so much.
