### ISSUE TITLE
[BUG] Log the failing LLM trace when call fails due to APITimeout error.

### ISSUE THREAD

**Issue by sraibagiwith100x** [Arize-ai/phoenix#3226]
**Is your feature request related to a problem? Please describe.**
Log the failing LLM trace when call fails due to APITimeout error. 

**Describe the solution you'd like**
Currently using llama index instrumentor, i'm noticing that when an LLM call (even after retries) fails with API Timeout, the offending LLM call doesn't show up in phoenix 
![CleanShot 2024-05-17 at 08 51 05@2x](https://github.com/Arize-ai/phoenix/assets/163024508/d7c591e1-97a4-4bc6-a051-c7c90c6b93b2)

in the above screenshot there was a 3rd LLM call that actually caused this error.
ignore the duplicate LLM spans (those are cache misses) 

**Describe alternatives you've considered**
Production logs instrumentation

**Comment by RogerHYang** [comment]
> @RogerHYang Is this issue resolved in the new instrumentation?

@axiomofjoy No I don't think so.

**Comment by RogerHYang** [comment]
This should be fixed in llama-index [v0.10.44](https://pypi.org/project/llama-index/0.10.44/). Let us know if it's still a problem. Thanks!
