### ISSUE TITLE
[ENHANCEMENT] Vercel AI SDK Autoinstrumentor

### ISSUE THREAD

**Issue by trevor-laviale-arize** [Arize-ai/phoenix#3265]
**Is your feature request related to a problem? Please describe.**
For teams using the Vercel AI SDK in their GenAI apps, we need to use the manual instrumentation for tracing. 

**Describe the solution you'd like**
It would be nice to have an autoinstrumentor for the [Vercel AI SDK](https://sdk.vercel.ai/docs/ai-sdk-core) rather than needing to manually instrument these use cases. 

**Describe alternatives you've considered**
Manual instrumentation

**Comment by mikeldking** [comment]
Hey @trevor-laviale-arize good to see you. This might be a ticket better suited for https://github.com/Arize-ai/openinference

But will leave this here for visibility!

**Comment by trevor-laviale-arize** [comment]
Ahh will create a ticket there as well :)

**Comment by mikeldking** [comment]
Tracking in https://github.com/Arize-ai/openinference/issues/533
