### ISSUE TITLE
Use locally deployed Llm for evaluation.

### ISSUE THREAD

**Issue by Talhamuhammadali** [Arize-ai/phoenix#3269]
I need to use locally deployed LLMs for evaluation within my current setup. While setting up LLM monitoring using Phoenix, I require evaluations with the traces, I am only able to find [evaluation llms](https://docs.arize.com/phoenix/evaluation/evaluation-models) with apis such as openai etc.

If not, support for locally deployed LLMs for evaluation should be added. This would allow for evaluations and monitoring in a local environment, particularly with Nvidia Triton inference server integrated with LlamaIndex. Using external LLMs for evaluation are better but my requirement is of data privacy and ofcourse minimizing the cost.

I am using Nvidia Triton for running an inference server, which is the used with the [llamaIndex integration for Nvidia triton](https://docs.llamaindex.ai/en/stable/examples/llm/nvidia_triton/). If this is already possible kindly point in the right direction.

**Comment by mikeldking** [comment]
Hi @Talhamuhammadali we support LiteLLM for pointing to local LLMs right now. Does this work for your use? https://docs.arize.com/phoenix/api/evaluation-models#litellmmodel

**Comment by Talhamuhammadali** [comment]
Thanks for the response, they do have [support for it](https://docs.litellm.ai/docs/providers/triton-inference-server) for embedding models will explore if this works
