### ISSUE TITLE
Feature request: add authentication

### ISSUE THREAD

**Issue by ootkin** [Arize-ai/phoenix#3289]
Hi all,

I just deployed on a remote server phoenix via Docker.

It would be awesome if we can specify an authentication layer (e.g. oauth or even a basic authentication).

**Comment by monuminu** [comment]
+1

**Comment by sarthakmp0** [comment]
+1

**Comment by rafaelpierre** [comment]
I'd be willing to contribute to this feature, but would this ever be considered/approved, given that SSO is one of the addons of Phonix' managed version?

**Comment by mikeldking** [comment]
This is actually already shipped in 5.0 https://docs.arize.com/phoenix/setup/authentication

Sorry for not closing this out!
