### ISSUE TITLE
[BUG] Can't load data with TraceDataset from the eval quickstart using a locally running Pheonix

### ISSUE THREAD

**Issue by heyalistair** [Arize-ai/phoenix#3294]
**Describe the bug**
I'm following the instructions from the quickstart here: https://docs.arize.com/phoenix/evaluation/evals

I'm expecting to see something like the screenshot on the page above. But instead my pheonix instances is empty.

![Screenshot 2024-05-23 at 19 59 51](https://github.com/Arize-ai/phoenix/assets/1237855/d280e225-dc4b-42b4-8a02-f4e6bf0bef81)

**To Reproduce**

I'm `pip3 install`ing these packages in a virtual environment:

```
arize-phoenix[evals]==4.2.0
IPython==8.24.0
```

And then I'm running the quickstart as described:

```
import phoenix as px
from urllib.request import urlopen
from phoenix.trace.trace_dataset import TraceDataset
from phoenix.trace.utils import json_lines_to_df

# Replace with the URL to your trace data
traces_url = "https://storage.googleapis.com/arize-assets/phoenix/datasets/unstructured/llm/context-retrieval/trace.jsonl"
with urlopen(traces_url) as response:
    lines = [line.decode("utf-8") for line in response.readlines()]
trace_ds = TraceDataset(json_lines_to_df(lines))

session = px.launch_app(trace=trace_ds)
session.view()

# To prevent the script from exiting immediately
input("Press enter to continue: ")
```

**Expected behavior**

I was hoping to see this: https://docs.arize.com/~gitbook/image?url=https%3A%2F%2Fstorage.googleapis.com%2Farize-assets%2Fphoenix%2Fassets%2Fdocs%2Fnotebooks%2Fevals%2Ftraces_without_evaluation_annotations.png&width=768&dpr=1&quality=100&sign=16734d5562c9a967b05e8c2fc8fa37668777f56bd66ea6f85bf300fd59e21da9

As described on the tutorial.

**Environment (please complete the following information):**
 - OS: macOS 14.2
 - Notebook Runtime [e.g. Jupyter, Colab]: Just native python 3.11.5
 - Browser [e.g. chrome, safari]: Firefox

**Comment by RogerHYang** [comment]
@heyalistair Can you try changing the menu on the upper right hand corner from "Last 7 days" to "All Time" ?

**Comment by heyalistair** [comment]
Wow, that worked, of course!

So obvious and yet so not obvious at the same time. :)

Thanks.
