### ISSUE TITLE
[BUG] Langchain tutorials - ModuleNotFoundError

### ISSUE THREAD

**Issue by trevor-laviale-arize** [Arize-ai/phoenix#3317]
**Describe the bug**
Getting `ModuleNotFound` errors (`ModuleNotFoundError: No module named 'langchain_community'`) when trying to run the below langchain tutorials:

- https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
- https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
- https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
- https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/langchain_tracing_tutorial.ipynb 

**To Reproduce**
1. Go to above tutorials and attempt to run all cells

**Expected behavior**
Tutorials do not throw a ModuleNotFound error 

**Screenshots**
![Screenshot 2024-05-28 at 9 33 47 AM](https://github.com/Arize-ai/phoenix/assets/116120725/ef629e80-91a3-4070-adf3-c91905bf9317)

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Colab
 - Browser: Chrome

**Comment by mikeldking** [comment]
Thanks for the flag. Will take a look!

**Comment by mikeldking** [comment]
Not a crazy rush but can I hand this off to you @axiomofjoy ? I'm out for the next few days.

**Comment by RogerHYang** [comment]
it's in separate package now
```python
from langchain_openai import ChatOpenAI
```
