### ISSUE TITLE
LangGraph Example

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3328]
Provide a LangGraph example for reference

**Comment by Jgilhuly** [comment]
Added these a while, but failed to update the ticket, cleaning up now:
- https://docs.arize.com/phoenix/tracing/integrations-tracing/langgraph
- https://github.com/Arize-ai/phoenix/blob/main/tutorials/tracing/langgraph_agent_tracing_tutorial.ipynb
