### ISSUE TITLE
[ENHANCEMENT] How to securely connect with the container

### ISSUE THREAD

**Issue by HeatherFlux** [Arize-ai/phoenix#3346]
**Is your feature request related to a problem? Please describe.**
Hey I'm working on setting up a container for this and would like to create some security for it be it mTLS or auth. I can't find what is currently available and supported

**Describe the solution you'd like**
Docs on securing the container or tooling

**Describe alternatives you've considered**
Building everything myself

**Additional context**

**Comment by mikeldking** [comment]
Hey @HeatherFlux thanks for reaching out - right now phoenix doesn't have built-in auth or security of this kind -  this will come later this year. Right now we recommend using phoenix in local computers, vpcs, behind VPNs etc for the time being. But do let us know if there's anything we can help with in the meantime. Thanks again!

**Comment by mikeldking** [comment]
Auth has shipped! Please give it a try and let us know how it goes
