### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shashank-v-gowda** [Arize-ai/phoenix#3384]
**Describe the bug**
I'm unable to access the phoenix UI in browser. It is throwing the below errors:
Error fetching GraphQL query 'TracingHomePageQuery' with variables '{}': [{"message":"Cannot query field 'spanEvaluationNames' on type 'Query'.","locations":[{"line":9,"column":3}]},{"message":"Cannot query field 'spans' on type 'Query'.","locations":[{"line":14,"column":3}]},{"message":"Cannot query field 'streamingLastUpdatedAt' on type 'Query'.","locations":[{"line":62,"column":3}]},{"message":"Cannot query field 'spans' on type 'Query'.","locations":[{"line":67,"column":3}]},{"message":"Cannot query field 'spans' on type 'Query'.","locations":[{"line":146,"column":3}]},{"message":"Cannot query field 'traceDatasetInfo' on type 'Query'.","locations":[{"line":151,"column":3}]},{"message":"Cannot query field 'spanEvaluationNames' on type 'Query'.","locations":[{"line":158,"column":3}]},{"message":"Cannot query field 'documentEvaluationNames' on type 'Query'.","locations":[{"line":159,"column":3}]}]

**To Reproduce**

**Expected behavior**
I expected to view the phoenix dashboard.

**Screenshots**
![image](https://github.com/Arize-ai/phoenix/assets/155565082/3ac679cf-1948-4c76-a111-f557d0fc583b)

**Environment (please complete the following information):**
 - OS: Linux
 - Notebook Runtime FastAPI endpoint using uvicorn
 - Browser Edge
 - Version Latest

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)
It was working fine earlier, but since I added the parameter use_temp_dir = False to the function launch_app() to persist the data into the directory at PHOENIX_WORKING_DIR, I've been facing this issue. I've verified that the data is getting persisted in the specified directory, but I encounter the issue when trying to view the dashboard.

**Comment by RogerHYang** [comment]
I think this is browser cache being out of date, so clearing the cache should fix this.

**Comment by axiomofjoy** [comment]
@shashank-v-gowda Can you see if the issue persists after confirming you are on version 4.2.4 and clearing your browser cache?

**Comment by shashank-v-gowda** [comment]
@RogerHYang / @axiomofjoy The issue got resolved after clearing the browser cache. Thanks for resolving the issue.

**Comment by shashank-v-gowda** [comment]
@RogerHYang  / @axiomofjoy  The issue got resolved after clearing the browser cache. Thanks for the help.
