### ISSUE TITLE
[BUG] AttributeError: module 'phoenix' has no attribute 'Dataset'

### ISSUE THREAD

**Issue by lolpro11** [Arize-ai/phoenix#3395]
**Describe the bug**
AttributeError: module 'phoenix' has no attribute 'Dataset'

**To Reproduce**
```python
import phoenix as px
print(px.Dataset())

```

**Expected behavior**
I expected px to have `Dataset`

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Notebook Runtime python
 - Browser N/A
 - Version most recent

**Comment by axiomofjoy** [comment]
Hi @lolpro11, `Dataset` was refactored to `Inferences`. Please see the [migration guide](https://github.com/Arize-ai/phoenix/blob/main/MIGRATION.md#migrating-from-legacy-phoenixdataset-to-phoenixinferences) for more information.

**Comment by anthropoleo** [comment]
> migration guide

Do you know why the UI still indicates the old method as of 28/10/2025?


<img width="437" height="563" alt="Image" src="https://github.com/user-attachments/assets/8da9f69d-c729-4114-8276-363b8c470ed0" />


same with official Docs:

<img width="832" height="632" alt="Image" src="https://github.com/user-attachments/assets/95f699c6-ecfb-4783-b3cc-23f707858fc6" />
