### ISSUE TITLE
[ENHANCEMENT] - Simplify Data Sending with Inline Call Back Support 

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#3397]
This notebook shows how to create a no boiler plate setup of Phoenix that supports inline (optional) call back. Also would suggest having a default callaback like one included here that teams can start with for retrieval.

Could we include cleaned up versions of:
- PhoenixEvalSpanProcessorExporter
- EvalSpanProcessor
- process_eval_hallu_qa

It would hugely help with getting started with lower friction. 

https://colab.research.google.com/drive/1_lGqhHz-V_SQ6Cs5iKLmkKYxJjrEySc1?authuser=2#scrollTo=PjtKA7ujZlWt

#################################################
#################################################

PhoenixEvalSpanProcessorExporter(project="llamaindex-llm-tracing", px_endpoint="http://localhost:6006/v1/traces", eval_callback=process_eval_hallu_qa)
LlamaIndexInstrumentor().instrument()

-------------
https://colab.research.google.com/drive/1_lGqhHz-V_SQ6Cs5iKLmkKYxJjrEySc1?authuser=2#scrollTo=PjtKA7ujZlWt

**Comment by mikeldking** [comment]
@jlopatec notebook link is broken. Can you fix?
