### ISSUE TITLE
[documentation] document the query DSL for spans

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3414]
We need a section both in the UI and also in the platform on how to query for containment as well as metadata

**Comment by RogerHYang** [comment]
Completed by https://github.com/Arize-ai/phoenix/pull/3451.

Also updated docs:

<img width="300" src="https://github.com/Arize-ai/phoenix/assets/80478925/57b71ef2-26fe-47cf-b90a-bc8f49a0e1d8">
<img width="300" src="https://github.com/Arize-ai/phoenix/assets/80478925/0ce1e9dc-aa7f-42d7-bbea-dff5ed10c871">
