### ISSUE TITLE
🗺️ Authentication Support

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3433]
Phoenix has evolved from a notebook tool to an application backed by a database and deployed as an OCI container. Since building persistence into Phoenix, the most common ask from end users has been the ability to deploy Phoenix with authorization. While it's currently possible to secure an instance of Phoenix by deploying it behind a reverse-proxy and implementing custom authentication, this requires significant effort and expertise on the part of the user. Not only are spans, traces, and datasets potentially private, but certain planned features such as prompt playground require the storage of API keys. Building auth will allow users to easily and securely store sensitive data in deployed instances of Phoenix and will unlock development on a new set of features.

Our goal is to enable users to deploy authenticated instances of Phoenix in a straightforward and secure way.

👓 [Tech spec](https://github.com/Arize-ai/phoenix/wiki/Auth-Tech-Spec)

## Preliminaries

- [x] #3855 
- [x] #4013
- [x] #3741
- [x] #4021
- [x] #4266

### Database

- [x] #4043
- [x] #4012
- [x] #4057
- [x] #4368
- [x] #4231
- [x] #4185
- [x] #4497
- [x] #4607

### Server

- [x] #4192
- [x] #4041
- [x] #3728
- [x] #4193
- [x] #4042
- [x] #4177
- [x] #4277
- [x] #4540
- [x] #4584
- [x] #4683 

### Client

- [x] #4056
- [x] #4613

### UI

- [x] #4047
- [x] #4048
- [x] #4199
- [x] #4223
- [x] #4454
- [x] #4269
- [x] #4278
- [x] #4311
- [x] #4360
- [x] #4361
- [x] #4273
- [x] #4362
- [x] #4483
- [x] #4484
- [x] #4492
- [x] #4552
- [x] #4553
- [x] #4564
- [x] #4576
- [x] #4605
- [x] #4612

### GraphQL API

- [x] #4040
- [x] #4063
- [x] #4050
- [x] #4051
- [x] #4062
- [x] #4037
- [x] #4220
- [x] #4049
- [x] #4421
- [x] #4038
- [x] #4039
- [x] #4052
- [x] #4061
- [x] #4058
- [x] #4059
- [x] #4233
- [x] #4234
- [x] #4272
- [x] #4227
- [x] #4222
- [x] #4326
- [x] #4335
- [x] #4344
- [x] #4363
- [x] #4364
- [x] #4366
- [x] #4367
- [x] #4452
- [x] #4448
- [x] #4491
- [x] #4507
- [x] #4513
- [x] #4561

### REST API

- [x] #4045
- [x] #4453
- [x] #4433
- [x] #4064
- [x] #4065
- [x] #4275
- [x] #4588

### gRPC API

- [x] #4274

### CI

- [x] #4515
- [ ] #4516

### Testing

- [x] #4179
- [x] #4493
- [ ] #4539
- [x] #4541

### Documentation

- [ ] #4542
- [ ] #4022
- [ ] #4568
- [x] #4567
- [x] #4582
- [x] #4569
- [x] #4577
- [x] #4583
- [ ] #4660
- [x] #4661

### Cleanup

- [x] #4184
- [x] #4551
- [x] #4183
- [x] #4586
- [x] #4594
- [x] #4676
- [x] #4677
- [x] #4691
- [ ] #4727
- [x] #4733
- [x] #4736
- [x] #4743
- [x] #4747
- [ ] #4761

### Punt

- [ ] #4678
- [ ] #4679

## Second Milestone (SMTP Integration)
- [x] #4602
- [x] #4659

### Server

- [x] #4054
- [x] #4055

## Third Milestone (OAuth2 support)

- [x] #4649
- [x] #4650
- [ ] #4651
- [x] #4652
- [x] #4653
- [x] #4654
- [x] #4657
- [x] #4675
- [x] #4685
- [x] #4686
- [x] #4687
- [x] #4688
- [x] #4690
- [x] #4712
- [x] #4550

**Comment by monuminu** [comment]
when are we planning to do this?

**Comment by mikeldking** [comment]
> when are we planning to do this?

We will start in the coming month.

**Comment by xwang-otterai** [comment]
Thank you for planning this! This would be very helpful!

**Comment by anandsainath** [comment]
Would be amazing to see this in the product! Commenting to follow progress.

**Comment by mikeldking** [comment]
Marking this milestone closed as Auth and RBAC is shipped in 5.0. Please feel free to file enhancement requests and we will triage them as follow-ups!
