### ISSUE TITLE
[datasets][sdk] allow renaming of fields when uploading from pandas/csv

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#3545]
The current usability is very awkward because it's can't be exported for openai finetuning.

Users would have to edit each example individually.

<img width="290" alt="Screenshot 2024-06-17 at 12 05 21 PM" src="https://github.com/Arize-ai/phoenix/assets/80478925/fbb7f2a3-1ac7-4a19-adbe-e047bf98ba21">

**Comment by mikeldking** [comment]
superseded by upload_examples
