### ISSUE TITLE
[experiments][gql] error rate on experiments

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3560]
As a user I want to know the error rate (e.g. the percentage error) of an experiment and display it on the dataset

**Comment by axiomofjoy** [comment]
@mikeldking Do you think this should be added as a resolver on `Experiment` or as part of the `ExperimentAnnotationSummary`?

**Comment by mikeldking** [comment]
> @mikeldking Do you think this should be added as a resolver on `Experiment` or as part of the `ExperimentAnnotationSummary`?

It's the number of errors for the runs so it belongs on the experiment
