### ISSUE TITLE
Unable to initialize GeminiModel class for evaluations

### ISSUE THREAD

**Issue by shashank-v-gowda** [Arize-ai/phoenix#3592]
How to use GeminiModel class for evaluations?
I'm trying with the below line of code, but it's throwing the following error.
Code:
eval_model = GeminiModel()

Error:
Retries exhausted after 11 attempts: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"                                                             
domain: "googleapis.com"
metadata {
  key: "service"
  value: "aiplatform.googleapis.com"
}
metadata {
  key: "method"
  value: "google.cloud.aiplatform.v1beta1.PredictionService.GenerateContent"
}
]

I don't see any way I can authenticate the API, should I use GOOGLE_API_KEY or service account file?
If yes, how should I pass them to the GeminiModel class? I don't see any documentation on how to authenticate the request.

**Comment by RogerHYang** [comment]
Using Colab with this notebook has worked for me. Would you like to try it? It's easier if it's on Colab.

**Comment by shashank-v-gowda** [comment]
@RogerHYang The above method only works for google-colab. I'm running the code on a GCP VM.

**Comment by RogerHYang** [comment]
Oh that's more complicated and I'm not familiar with it. Let me see if I can find someone who can help you.

**Comment by shashank-v-gowda** [comment]
@RogerHYang I've added a code change which resolves this issue from my alt account. Please review the changes.
https://github.com/Arize-ai/phoenix/pull/3662
