### ISSUE TITLE
[ENHANCEMENT] Add toggle to collapse child spans of a parent span on the side panel

### ISSUE THREAD

**Issue by sraibagiwith100x** [Arize-ai/phoenix#3597]
**Is your feature request related to a problem? Please describe.**
My traces can become really long but we've created top level custom spans that encapsulate sets of child spans within a trace.

These spans can become tough to view when it's a long trace. 

**Describe the solution you'd like**
This FR is to add a toggle to collapse / open child spans of a parent span  

**Describe alternatives you've considered**
We have some toggling on the traces tab but it's not enough because it goes from all closed -> open each vs what would be good is all open (on side panel) -> close what ever i want 

**Additional context**
![CleanShot 2024-06-21 at 08 30 20@2x](https://github.com/Arize-ai/phoenix/assets/163024508/ae165ec7-8a3e-4e42-94ad-dfddd39017eb)

**Comment by mikeldking** [comment]
This toggle has been added in the latest!
<img width="472" alt="Screenshot 2024-08-15 at 8 14 03 PM" src="https://github.com/user-attachments/assets/08b42659-3196-402d-86e4-d250bb276bab">
