### ISSUE TITLE
[experiments] docstring

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3602]

**Comment by RogerHYang** [comment]
sqlalchemy [docs](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column) and [docstrings](https://github.com/sqlalchemy/sqlalchemy/blob/2607262110bdc5c5dc96fc19ddca895a15a58e4e/lib/sqlalchemy/sql/schema.py#L1543) are outstanding
