### ISSUE TITLE
[ENHANCEMENT] ARM builds via CI

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3636]
create images for ARM

**Comment by pandego** [comment]
Would it be feasible to change the base image to `ARG BASE_IMAGE=python:3.11-slim`? This would mean changing the command to `CMD ["python", "-m", "phoenix.server.main", "serve"]`.

**Comment by mikeldking** [comment]
Hey @pandego - we actually switched from that base image for both image size and security. Probably not in the cards at this current juncture since we gained a lot from switching over.

**Comment by axiomofjoy** [comment]
arm64 is supported in the docker image as of `arize-phoenix==4.29.0`
