### ISSUE TITLE
[BUG] qr code on standing sign sent me to dead end

### ISSUE THREAD

**Issue by jessicalhammond** [Arize-ai/phoenix#3650]
**Describe the bug**
A dead end from phoenix powered by arise standing sign

**To Reproduce**
1. Use phone cámara 
2. Point at QR code on sign
3. Tap open in chrome 
4. See dead end and link to file big 

**Expected behavior**
🤷🏻‍♀️

**Screenshots**
See attached 
![image](https://github.com/Arize-ai/phoenix/assets/25573121/85aac21a-15a5-4907-9d0a-3bc4d0d87e84)
![IMG_4616](https://github.com/Arize-ai/phoenix/assets/25573121/b90c5810-43ff-4cee-ba6a-b5288e9383e5)

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - Notebook Runtime [e.g. Jupyter, Colab]
 - Version [e.g. 0.0.1]

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by mikeldking** [comment]
@jessicalhammond good looking out. Thank you. I'll alert the team
