### ISSUE TITLE
🗺 API Documentation

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3691]
As a developer, I'd like code level API docs published and versioned

### Spike
- [x] #3695
- [x] #3707 

### Docstrings
- [x] #3692
- [x] #3725
- [x] [api-docs] docstrings for experiments

### API Reference (Sphinx)
- [x] #3730 
- [x] #3722
- [x] #3724
- [x] #3787 
- [x] #3871 
- [x] #3936 
- [x] [api-docs] provide examples in phoenix-eval

### Other
- [x] #3854

**Comment by cjunkin** [comment]
- [ ] [api-docs] sphinx -> readthedocs setup
