### ISSUE TITLE
[ENHANCEMENT] Scrollable Project Page

### ISSUE THREAD

**Issue by sideef5ect** [Arize-ai/phoenix#3694]
**Is your feature request related to a problem? Please describe.**
If there are more than 16 projects in database, the UI can not fully display them all, and the page is not scrllable.
<img width="1374" alt="image" src="https://github.com/Arize-ai/phoenix/assets/33738071/43ea5b64-b6a7-40c4-a69c-c8132736acc8">

**Describe the solution you'd like**

More friendly UI for the project page.

**Describe alternatives you've considered**

**Additional context**

**Comment by axiomofjoy** [comment]
@sideef5ect Thanks! We'll get this one prioritized.
