### ISSUE TITLE
[sessions][js] startSession and endSession in openinference Core

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3810]
Make sure the ergonomics of starting and ending a session via open-inference is simple and easy to use (e.g. 1 line to start, 1 line to close). Should consider non-nested (e.g. imparative) and nested (context propagation).

**Comment by mikeldking** [comment]
This might be partially done but might need to be better documented? Putting in a future sprint to make sure

**Comment by Parker-Stafford** [comment]
the nested context propagation version of this has been completed and documented, closing for now until we need a different interface
