### ISSUE TITLE
[BUG] Phoenix.evals.OpenAIModel doesn't recognize Azure Active Directory Authentication

### ISSUE THREAD

**Issue by Jgilhuly** [Arize-ai/phoenix#3813]
**Describe the bug**
Azure has an option for active directory authentication which allows you to log in via CLI instead of supplying API keys. The initializer for our OpenAIModel class requires an api_key as a parameter, and so throws an error if it is missing - even though it is not needed if this active directory approach is being used.

**To Reproduce**
```
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from phoenix.evals import OpenAIModel

token_provider = get_bearer_token_provider(
    DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
)

client = OpenAIModel(
    api_version="2024-02-15-preview",
    azure_endpoint=<endpoint>,
    azure_ad_token_provider= token_provider,
    model=<deployment_name>,
)

response = client('Does Azure OpenAI support customer managed keys?')
print(response)
```

**Expected behavior**
Ideally we should recognize the active directory key and allow initialization without a key in this case.

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Jupyter
 - azure-identity==1.17.1, openai==1.35.9, arize-phoenix[evals]==4.6.2

**Workaround**
Can add a random api_key to the OpenAIModel initialization call and it will be overridden by the active directory value.

**Comment by axiomofjoy** [comment]
Thanks @Jgilhuly, I'll take a look tomorrow.
