### ISSUE TITLE
[BUG] Anthropic tokens spent not being shown in the UI via langchain instrumentor. 

### ISSUE THREAD

**Issue by antoni0z** [Arize-ai/phoenix#3814]
# Bug Report: Missing Token Count for Anthropic Models in Phoenix Dashboard

## Issue Description

When using Anthropic models through LangChain, the token usage (total, input, and output tokens) is not displayed correctly in the Arize Phoenix dashboard. This occurs despite the token information being present in the response message.

![Phoenix Dashboard showing missing token count](https://github.com/Arize-ai/phoenix/assets/121305966/61a8db1e-5598-440d-9ed6-8289c9d77a1d)

![Response message with token information](https://github.com/Arize-ai/phoenix/assets/121305966/e90fd678-46c6-4893-adb4-e06c7da224f3)

## Steps to Reproduce

1. Set up Phoenix as a service in docker-compose:
   ```yaml
   phoenix:
     image: arizephoenix/phoenix:latest 
     ports:
       - 6006:6006
       - 4317:4317
     environment:
       - PHOENIX_WORKING_DIR=/mnt/data
     volumes:
       - phoenix_data:/mnt/data
     user: "${UID}:${GID}"
   ```

2. Install the following dependencies:
   ```
   openinference-instrumentation-langchain==0.1.20
   openinference-instrumentation-openai==0.1.6
   openinference-semantic-conventions==0.1.9
   langchain-core==0.2.10
   langchain-anthropic>=0.1.19
   langchain-openai>=0.1.12
   langchain-text-splitters>=0.2.2
   langchain>=0.2.6
   anthropic==0.28.0
   ```

3. Configure and run instrumentation:
   ```python
   def instrument(self):
       try:
           resource = Resource(attributes={
               ResourceAttributes.PROJECT_NAME: self._project_name
           })
           tracer_provider = trace_sdk.TracerProvider(resource=resource)
           phoenix_collector_endpoint = os.getenv("PHOENIX_COLLECTOR_ENDPOINT")
           if not phoenix_collector_endpoint:
               raise ValueError("PHOENIX_COLLECTOR_ENDPOINT environment variable is not set.")
           span_exporter = OTLPSpanExporter(endpoint=phoenix_collector_endpoint)
           span_processor = SimpleSpanProcessor(span_exporter=span_exporter)
           tracer_provider.add_span_processor(span_processor=span_processor)
           trace_api.set_tracer_provider(tracer_provider=tracer_provider)
           LangChainInstrumentor().instrument()
           print("Instrument successful")
       except Exception as e:
           print(f"An error has occurred while instrumenting: {e}")
   ```

4. Make a request using an Anthropic LLM.

5. Check the Phoenix dashboard - total tokens are not displayed.

## Expected Behavior

The Phoenix dashboard should accurately display the total, input, and output token counts for Anthropic models.

## Environment

- Server: Docker image `arizephoenix/phoenix:latest` (version 4.6.2)
- Client: Python 3.11.7 (slim-bullseye Docker image)

## Additional Notes

The issue may be related to LangChain, Arize Phoenix, or a specific version of either. Further investigation is needed to determine the root cause.

**Comment by gurusinghPr** [comment]
Same issue with langchain +gemini

**Comment by axiomofjoy** [comment]
Thanks for reporting. We'll take a look.

**Comment by axiomofjoy** [comment]
@gurusinghPr Which LangChain model are you using that you encounter this error?

**Comment by axiomofjoy** [comment]
@antoni0z Thanks for your patience. This issue is resolved in `openinference-instrumentation-langchain==0.1.23`.

**Comment by antoni0z** [comment]
Now its working alright, thanks for the good work!
