### ISSUE TITLE
[feedback] filter on Annotations using DSL

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3815]
Add the appropriate DSL to search "human" annotations via the UI

One possible syntax would be
```python
Annotations["pass"].label == "true"
Annotations["thumbs_up"].label == "up"
```

**Comment by fozziethebeat** [comment]
Will the docker images be rolled out with this fix soon? I was trying to do this on MacOS and found this feature to still be missing when launching via docker.

**Comment by mikeldking** [comment]
> Will the docker images be rolled out with this fix soon? I was trying to do this on MacOS and found this feature to still be missing when launching via docker.

Hmm strange. It should definitely be in the latest images. Let us know if you have any issues. Apologies for the late reply.
