### ISSUE TITLE
Tokens are not captured for Bedrock Models

### ISSUE THREAD

**Issue by chaitanya-nit** [Arize-ai/phoenix#3851]
**Describe the bug**
I have run the tutorial https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb 
Here total tokens for each span are not captured.

**To Reproduce**
1. Go to 'https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb'
2. See the spans at http://localhost.com:6006/ 

**Expected behavior**
Expected to see token counts.

**Screenshots**
<img width="660" alt="image" src="https://github.com/Arize-ai/phoenix/assets/34399825/11a8b78a-d034-4f4b-b0bf-eeee89e5b9c9">

Tokens are visible in the output of LLM
<img width="464" alt="image" src="https://github.com/Arize-ai/phoenix/assets/34399825/f2edd8c6-44e1-409f-b785-53d0aaeba5e0">

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Notebook Runtime : Colab
 - Browser:  Chrome

**Comment by axiomofjoy** [comment]
@chaitanya-nit Thanks for reporting. I am re-labeling as an enhancement request.

**Comment by mikeldking** [comment]
This may still be an issue but there's a proprietary bedrock instrumentor that has token counts. I'm gonna de-prioritize this and un-link from phoenix itself. If this is still causing an issue, please file an issue with the openinference project.

Thanks for the note!
