### ISSUE TITLE
[BUG] Phoenix container get's bad PHOENIX_PORT by default in k8 but not docker compose. 

### ISSUE THREAD

**Issue by chrishart0** [Arize-ai/phoenix#3899]
**Describe the bug**

Deploying the phoenix via k8 works for some amount of time and then always fails with this error. Container dies and then will not come back up. 

```
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/phoenix/env/phoenix/server/main.py", line 206, in <module>
    port = args.port or get_env_port()
                        ^^^^^^^^^^^^^^
  File "/phoenix/env/phoenix/config.py", line 176, in get_env_port
    raise ValueError(
ValueError: Invalid value for environment variable PHOENIX_PORT: tcp://172.20.120.186:6006. Value must be an integer.
```

Setting this `PHOENIX_PORT` env var on the container resolves the issue, so this suggests to me the issue is somewhere baked into the container. I'm running the same version of Phoenix via docker compose without setting that env var with no issue. 

**To Reproduce**
1. Spin up a phoenix container in k8
2. Try to store trace data via llama_index

**Expected behavior**
I expect this to work with defaults values for `PHOENIX_PORT`

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Phoenix container `arizephoenix/phoenix:version-4.8.1`
 - Version 4.8.1

**Comment by mikeldking** [comment]
@chrishart0 that is super strange. Thanks for reporting. I can't think of a reason this is happening right now but will have some engineers take a look to see if it rings a bell.

**Comment by mikeldking** [comment]
We having a hard time reproducing this. This is still on our radar but need to push off for another few weeeks.

**Comment by danieleh11** [comment]
Workaround that worked for me adding the value as env to the deployment manual. 
            - name: PHOENIX_PORT
              value: "6006"

**Comment by axiomofjoy** [comment]
When deploying Phoenix with Kubernetes using a service named "phoenix," Kubernetes automatically generates an environment variable called PHOENIX_PORT in the form of "tcp://<IP>:<PORT>." However, this format is not the integer format that Phoenix expects. To address this issue, you should explicitly set the PHOENIX_PORT environment variable to an integer value in your Kubernetes deployment configuration.

We've added an error message to help users resolve the issue when it happens.
