### ISSUE TITLE
[ENHANCEMENT] - Adding Attributes for Auto-instrumentation 

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#3935]
The auto-instrumentation is great for LLM spans.

We really would like to be able to add attributes to these spans in a easy way without editing the chat.completion call itself. 
OpenAIInstrumentor().instrument()

 # Set the context variables 
 #Ideally these can be set in the thread anywhere (different file if needed) but if your lucky you can set right before the function  

prompt_template_var.set("Hello, {name}. How can I assist you with your {task} today?")  
prompt_vars_var.set({"name": "Alice", "task": "homework"})
response = openai.ChatCompletion.create( model="gpt-3.5-turbo", messages=[{"role": "user", "content": prompt}] )

Assumption is these work like maybe the ContextVar import and are picked up by the instrumentation calls:
from contextvars import ContextVar # Define the context variables 
prompt_template_var = ContextVar('prompt_template') 
prompt_vars_var = ContextVar('prompt_vars')

I think this is in the standard library so might not need to import something new.
https://docs.python.org/3/library/contextvars.html

Might be ways to set these more generally:
prompt_template_var.set({
"name":attributes.prompt_template.prompt_var", 
"value":"Hello, {name}. How can I assist you with your {task} today?"
})

equivalent to:

  span.set_attribute("attributes.prompt_template.prompt_var", "Hello, {name}. How can I assist you with your {task} today?")

**Comment by mikeldking** [comment]
This is actually supported via `openinference.instrumentation` as a decorator or a context var

https://docs.arize.com/phoenix/tracing/how-to-tracing/customize-spans#specifying-the-prompt-template
