### ISSUE TITLE
[ENHANCEMENT] Add Authentication support

### ISSUE THREAD

**Issue by manjunathshiva** [Arize-ai/phoenix#3945]
**Is your feature request related to a problem? Please describe.**
Any one who knows the IP address or a port can access the Dashboard! Need Admin access / Authentication support so only Admin can access the dashboard

**Describe the solution you'd like**
Login access like Grafana or Kibana dashboard.

**Describe alternatives you've considered**
NA

**Additional context**
We wo not want users to access the Dashboard. Only Admins .

**Comment by axiomofjoy** [comment]
Thanks @manjunathshiva. This issue is in progress [here](https://github.com/Arize-ai/phoenix/issues/3433).
