### ISSUE TITLE
[BUG] I get a a white page when I set PHOENIX_HOST_ROOT_PATH 

### ISSUE THREAD

**Issue by firetix** [Arize-ai/phoenix#3961]
**Describe the bug**
If you set PHOENIX_HOST_ROOT_PATH to any value, and run phoenix it will show an empty scree

**To Reproduce**
1.  Set PHOENIX_HOST_ROOT_PATH="Test"
2. Run serve `python3 -m phoenix.server.main --host 0.0.0.0 --port 7442 serve`

**Expected behavior**
A running UI

**Screenshots**
<img width="2041" alt="image" src="https://github.com/user-attachments/assets/f0ecae13-8a70-4bad-84b5-db49f3b500f0">
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/c10e8b42-a665-404a-983e-c016ffcc9b3b">

**Comment by RogerHYang** [comment]
This is intended to work in conjunction with a proxy. For example, you can try it locally with `traefik` by following the instructions [here](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#testing-locally-with-traefik). See screenshot below.

![image](https://github.com/user-attachments/assets/23416ca4-ed47-45c2-ad91-e58451c22e0b)

**Comment by axiomofjoy** [comment]
@firetix Please see https://github.com/Arize-ai/phoenix/tree/main/examples/proxy for an example.
