### ISSUE TITLE
[BUG] Specifying a value of -1 for max_tokens when initializing openai model results in 400 error from openai

### ISSUE THREAD

**Issue by trevor-laviale-arize** [Arize-ai/phoenix#3964]
**Describe the bug**
I tried setting the [max_tokens to -1 based on the argument description](https://github.com/Arize-ai/phoenix/blob/ef7cf612ef97ce0548afb3e49ba14cc83cbb407c/packages/phoenix-evals/src/phoenix/evals/models/openai.py#L76) since the default of 256 wasn't enough, but it looks like that value is just passed directly to openai and they don't accept -1 as a value. 

**To Reproduce**
```
eval_model = OpenAIModel(
    model="gpt-4o",
    temperature=0.0,
    max_tokens=-1,
)
eval_model("Hello world, this is a test if you are working?")
```

**Expected behavior**
Not sure if "-1" is supposed to work here? 

**Screenshots**
![Screenshot 2024-07-22 at 9 50 51 PM](https://github.com/user-attachments/assets/322fa5f3-e141-49ac-873b-a2bc6ec54ff6)

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Colab
 - Browser: Chrome
 - Version: 4.12.0

**Comment by mikeldking** [comment]
@anticorrelator I think this docstring may have come from you? I'm not sure -1 or 256 are valid bounds for this param.
