### ISSUE TITLE
[BUG] Unexpected end of JSON input (Response size was too large) - using cloud run and gcs

### ISSUE THREAD

**Issue by Freezaa9** [Arize-ai/phoenix#3984]
**Describe the bug**
Hi and thanks you to help me on this. 
We are running phoenix on GCP Cloud run with default docker hub image: arizephoenix/phoenix:version-4.9.0
The PHOENIX_WORKING_DIR env variable is set to /mnt/volume where a GCS bucket is mounted.

Basically we have another cloud run running the LLM app using langgraph pushing the trace to the pheonix cloud run.
We didn't have any issue, but recently we encounter an **Unexpected end of JSON input** error. 
![image](https://github.com/user-attachments/assets/65c4d265-b185-46b7-a452-00fda589c684)

and in the phoenix cloud run log I can find:
![image](https://github.com/user-attachments/assets/b84ac757-92a5-461e-9429-afa407986d46)
![image](https://github.com/user-attachments/assets/df6dd9cc-d410-4c8b-8b16-ac7b1fd3fe64)

Deleting the database and rerunning the cloud run fix the issue, and we are able to receive few trace until this happen again. 

My first thought that using Postgres as database might fix the issue, but I want your advice on that before processing because it is not easy to set up a Postgres in my organization.

Thanks !

**Comment by mikeldking** [comment]
@Freezaa9 Thanks for filing the issue and providing us feedback. Apologize for the delay in response back back to you as soon as I can on a corrective action or advice. thank you for using Phoenix!

**Comment by Freezaa9** [comment]
UPDATE: after redeploying the cloud run without deleting the DB from GCS it is working again. No alert since, but we didn't collect a lot of trace lately, so I don't exclude the issue to happen again. Please continue to look for a corrective action, and I'm of course available if you need.

**Comment by mikeldking** [comment]
Closing for now, please let us know if it crops up again!
