### ISSUE TITLE
🗺️ Phoenix Onboarding

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4003]
As a first time user of phoenix, it can be daunting to know how to get started, particularly if you are starting from the UI. You are placed in a default project. Pain points include:

- [x] #4004
- [x] #4285 
- [x] #4240
- [x] #4245
- [x] [onboarding] example project with traces and evals
- [x] #4007
- [x] [onboarding] UI guidelines on how to setup projects
- [x] #4244
- [x] #4198
- [x] #4248
- [x] #4247
- [x] #4357
- [x] #4268
- [x] #4352

## Phoenix.Otel

- [x] #4351
- [ ] #4350
- [x] #4358

**Comment by exiao** [comment]
Here's a mockup to help with empty state when people don't know how to send in traces.
![image](https://github.com/user-attachments/assets/e525985a-dd8f-4629-85c1-3e473d561449)
https://www.figma.com/design/ZIxEyoANv3NqoPFirAot6k/LlamaTrace?node-id=469-3971&t=tYAStP8iV8fn7xOH-0

**Comment by mikeldking** [comment]
https://link.excalidraw.com/l/AtcpXqHEPnG/7JogMWyRTVo

**Comment by mikeldking** [comment]
Closing out as all that is remaining is notebook conversion
