### ISSUE TITLE
[BUG] evals['qa_evaluator'].label is None is not the opposite of evals['qa_evaluator'].label is not None

### ISSUE THREAD

**Issue by firetix** [Arize-ai/phoenix#4017]
**Describe the bug**
I'm unable to pull the spans that never been evaluated from Phoenix. In the UI or python if I filter by evals['qa_evaluator'].label is not None it will return the one that are **correctly** evaluated, but if I do evals['qa_evaluator'].label is None it doesn't return the spans that are not evaluated.  How can I retrieve the spans that have never been evaluated, I currently can only retrieve the one that have been evaluated, I could do a script filtering but that won't be optimal. 

Thanks for looking at this

**To Reproduce**
1. Add a few examples of QAConversation chain 
2. Log evaluation for some of them 
3. Try to filter by `evals['qa_evaluator'].label is None`
`px.Client().get_spans_dataframe("evals['qa_evaluator'].label is None ")`

**Expected behavior**
Return the spans that never been evaluated.

**Screenshots**
<img width="1995" alt="image" src="https://github.com/user-attachments/assets/41a4c2a7-18ab-499f-98db-24da69a00f5e">
<img width="2004" alt="image" src="https://github.com/user-attachments/assets/9019baff-f44c-427f-8330-adccc9f54ca1">
<img width="2004" alt="image" src="https://github.com/user-attachments/assets/a358c796-7165-4ed9-ad33-43db41bee31f">

**Comment by mikeldking** [comment]
Thanks for the issue @firetix ! Totally understand this usecase and we will address this. Appreciate you bringing it to our attention.
