### ISSUE TITLE
[BUG] `client.get_spans_dataframe` is too slow

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4083]
From testing by @hamelsmu:

```
1. client.get_spans_dataframe 22s
2. downloading the SQL Lite DB and reading that into pandas: 1.6s
Here is a notebook comparing both https://gist.github.com/hamelsmu/2ce7636935b6d55c3852e25a445926c8
```

The remote compute on my local home network.  But that shouldn’t matter because in the comparison i’m running scp to download the entire postgres db

**Comment by RogerHYang** [comment]
[fwiw](https://github.com/Arize-ai/phoenix/blob/849fa8b13ed003f3c4b1bdb326ac739d7aa8c87e/src/phoenix/trace/dsl/query.py#L771)
