### ISSUE TITLE
[ENHANCEMENT] add the ability to filter spans by document evaluations

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4089]
Users debugging RAG want to filter their spans to know whether the fault lies with the retriever or the LLM. We need a way for the user to filter document evaluations using our query DSL so they can write filters such as:

```
document_evals["relevance"].label == "relevant" and evals["qa_correctness"].label == "incorrect"
```

https://arize-ai.slack.com/archives/C04R3GXC8HK/p1722442515198979?thread_ts=1722436956.324489&cid=C04R3GXC8HK

**Comment by RogerHYang** [comment]
Because span and doc evals are on different spans, this is blocked unless we can apply a filter for evals on the root span and still include sub-spans in the calculation document evaluations.
