### ISSUE TITLE
Function Tool Call Definition Instrumentation 

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#4096]
We need to capture the JSON definition (input) of the function tool call as part of our semantic conventions. This would be on the LLM spans and not the message field.  This is different than the function call already defined in the message portion of the instrumentation.

The tool call field looks like the below:
<img width="762" alt="Screenshot 2024-07-31 at 5 51 06 PM" src="https://github.com/user-attachments/assets/e39ef42f-e108-440c-b52e-aaa9abbd3616">

This is typically an input to chat completion using a separate tool field. 
<img width="598" alt="Screenshot 2024-07-31 at 5 51 12 PM" src="https://github.com/user-attachments/assets/f8b57a8e-9ce7-4296-96a2-6dfa4c478ca2">

Link to Function Calling PRD on Prompt Playground side: https://arizeai.atlassian.net/wiki/spaces/PROD/pages/627769350/Function+Calling+in+Prompt+Playground

**Comment by jlopatec** [comment]
To be really clear this is different than the "tool.*" conventions that are used on the tool spans.

These are the function input descriptions used on the router spans as input data to the LLM defining what tools are available.

Possible naming:
tooldescription
functiontooldescription 

I don't think we should put a "tool." in front of it as it won't be "on" a tool span but a router span. It would be on the same span that has message.tools (the output)

**Comment by mikeldking** [comment]
@harrisonchu subscribing. Can you keep me in the loop on this one? We need this to be cross LLM compatible - not just OpenAI and it will have to decipher what a common syntax is here across LLMs.

@jlopatec wrong repo but we get the idea ;)

**Comment by mikeldking** [comment]
closing in favor of https://github.com/Arize-ai/openinference/issues/689
