### ISSUE TITLE
Updated user-guide

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4097]
The user guide needs to be re-fined to include:

- datasets
- experiments
- template tracking

**Comment by Jgilhuly** [comment]
Added some extra experiments info: https://app.gitbook.com/o/-MB4weB2E-qpBe07nmSL/s/ShR775Rt7OzHRfy5j2Ks/~/changes/814/user-guide

This is more of an iterative improvement. I can do a ground up rewrite instead if we prefer

**Comment by Jgilhuly** [comment]
Closing as duplicative of #5395
