### ISSUE TITLE
Display not only token count but cost

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4102]
Users want to see not only the number of tokens their trace consumed, but also the cost. They want to be able to understand how that cost would change if they were to switch to another model.

> And, while I'm at it, it would be awesome to include the pricing tables for the different models so we could see (as some other tracing tools do) how much it cost to run each trace (using different models).

_Originally posted by @dsporcaro in https://github.com/Arize-ai/phoenix/issues/3119#issuecomment-2261333006_

**Comment by fret423** [comment]
Yes this is relevant - it is still very helpful to see the cost per call

**Comment by axiomofjoy** [comment]
We'll be adding cost as part of our upcoming milestone: https://github.com/Arize-ai/phoenix/issues/6731
