### ISSUE TITLE
[docs] global quickstart

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4105]
information on how to launch phoenix and get started is fragmented and too deeply nested https://arize-ai.slack.com/archives/C04R3GXC8HK/p1722534335071179

**Comment by Jgilhuly** [comment]
@axiomofjoy - took a stab here: https://app.gitbook.com/o/-MB4weB2E-qpBe07nmSL/s/ShR775Rt7OzHRfy5j2Ks/~/changes/777/quickstart

This feels redundant with the docs homepage. Is there more info that you think we should add in here?

**Comment by mikeldking** [comment]
I've PR'd with JavaScript and gRPC changes. Maybe this is not ideal - https://app.gitbook.com/o/-MB4weB2E-qpBe07nmSL/s/ShR775Rt7OzHRfy5j2Ks/~/changes/785/quickstart

But we should consider adding sections for these

**Comment by mikeldking** [comment]
The problem withe the new quickstart is that it only really covers getting started with tracing - I'm not sure if this really is the only thing needed
