### ISSUE TITLE
[BUG] LlamaIndex integration seems broken

### ISSUE THREAD

**Issue by kun432** [Arize-ai/phoenix#4112]
**Describe the bug**

Trying on llamaindex integration on Google Colaboratory, returns 

`ERROR [opentelemetry.instrumentation.instrumentor] DependencyConflict: requested: "llama-index-core >= 0.10.43" but found: "tenacity 9.0.0"`

 and Phoenix app does not start.

seems dependency conflics but not sure if this comes from Phoenix or LlamaIndex.

**To Reproduce**

```
!pip install llama-index arize-phoenix
```

```
import phoenix as px
from openinference.instrumentation.llama_index import LlamaIndexInstrumentor

px.launch_app()
LlamaIndexInstrumentor().instrument()
```

```
🌍 To view the Phoenix app in your browser, visit https://XXXXXXXXXXXXXXXXXXXX-colab.googleusercontent.com/
📖 For more information on how to use Phoenix, check out https://docs.arize.com/phoenix
ERROR [opentelemetry.instrumentation.instrumentor] DependencyConflict: requested: "llama-index-core >= 0.10.43" but found: "tenacity 9.0.0"
```

The URL does not work.

**Expected behavior**

no error and enable to use Phoenix app and tracing.

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Google Colaboratory
 - Browser: Chrome
 - Version:
```
arize-phoenix==4.16.1
arize-phoenix-evals==0.14.1
llama-cloud==0.0.11
llama-index==0.10.59
llama-index-agent-openai==0.2.9
llama-index-cli==0.1.13
llama-index-core==0.10.59
llama-index-embeddings-openai==0.1.11
llama-index-indices-managed-llama-cloud==0.2.7
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.27
llama-index-multi-modal-llms-openai==0.1.8
llama-index-program-openai==0.1.7
llama-index-question-gen-openai==0.1.3
llama-index-readers-file==0.1.32
llama-index-readers-llama-parse==0.1.6
llama-parse==0.4.9
openinference-instrumentation-llama-index==2.2.1
tenacity==8.5.0
```

**Additional context**

Also, LlamaTrace integration returns the same error.

```
import llama_index.core
import os
from google.colab import userdata

PHOENIX_API_KEY = userdata.get('PHOENIX_API_KEY')
os.environ["OTEL_EXPORTER_OTLP_HEADERS"] = f"api_key={PHOENIX_API_KEY}"
llama_index.core.set_global_handler(
    "arize_phoenix", endpoint="https://llamatrace.com/v1/traces"
)
```

**Comment by axiomofjoy** [comment]
@kun432 Thanks for reporting, will take a look.

**Comment by RogerHYang** [comment]
This is a known issue with Colab: it should go away if you restart the session (don't delete).

**Comment by axiomofjoy** [comment]
@kun432 Closing this issue for now as it seems to be a Colab issue, but please feel free to re-open if the issue persists.

**Comment by kun432** [comment]
@axiomofjoy @RogerHYang confirmed. yep, this seems colab issue.

Also, currently Colab seems to have other proxy port issue and `px.launch_app()` does not work. will wait for being fixed by Colab.

Thank you.
