### ISSUE TITLE
[BUG][Client] get_dataset is ommitting part of the path in the URL

### ISSUE THREAD

**Issue by carlosmagan** [Arize-ai/phoenix#4129]
**Describe the bug**
There is a behavioural difference on how to access the URLs in client.get_dataset, client._get_dataset_id_by_name and client.get_dataset_versions, specifically the step where the url is generated.

In get_dataset we have
`urljoin(self._base_url, f"/v1/datasets/{quote(id)}/examples")`

In _get_dataset_id_by_name we have
`urljoin(self._base_url, "/v1/datasets")`

In get_dataset_versions we have
`url = urljoin(self._base_url, f"v1/datasets/{dataset_id}/versions")`

The correct one is the one in get_dataset_versions.

The '/' before v1 implies that the relative url is absolute and must follow the domain at a root level. This is a problem when the base url is something on the line of `https://base_domain.com/phoenix` because the /phoenix is removed resulting in a final url like `https://base_domain.com/v1/datasets/example_id/examples` instead of the correct one `https://base_domain.com/phoenix/v1/datasets/example_id/examples`

**To Reproduce**
1. Deploy phoenix on an endpoint whose url has some kind of path after the domain
2. Upload a dataset
3. Instantiate a phoenix client in a notebook 
4. query the dataset  with the get_dataset method

**Expected behavior**
The path for get_dataset should include the complete base_path
**Screenshots**
![image](https://github.com/user-attachments/assets/67bcdf7e-1752-4bda-8188-94ae5e97f05a)

**Comment by axiomofjoy** [comment]
@carlosmagan Thanks for reporting and good find, we'll take a look.

**Comment by axiomofjoy** [comment]
Great catch @carlosmagan, thanks for the detailed explanation.

**Comment by axiomofjoy** [comment]
This is resolved in `arize-phoenix 4.20.0`

**Comment by carlosmagan** [comment]
Thanks a lot for the quick fix
