### ISSUE TITLE
Authentication and SAML Integration

### ISSUE THREAD

**Issue by Townsheriff** [Arize-ai/phoenix#4130]
**Is your feature request related to a problem?

Host phoenix app on public internet. How do we protect it.

**Describe the solution you'd like**

I think easy and elegant solution would be a SAML integration, that would open a lot of doors starting from AD and Cognito.

**Describe alternatives you've considered**

* Hosting under VPN
* Adding NGINX proxy with auth
* oauth2-proxy that connect with SAML

**Additional context**

I think there should be a guide/solution on how to securely host phoenix app on public internet.

**Comment by axiomofjoy** [comment]
@Townsheriff Thanks for the feedback. We hear you on the need for authentication and are beginning work on [this](https://github.com/Arize-ai/phoenix/issues/3433). Our initial plan is to build a local auth server and support for OAuth2, but the request for SAML is noted ✍️

> I think there should be a guide/solution on how to securely host phoenix app on public internet.

I agree 100%
