### ISSUE TITLE
Error fetching GraphQL query 'homeLoaderQuery' with variables '{}': [{"message":"disk I/O error","locations":[{"line":2,"column":3}],"path":["functionality"]}]

### ISSUE THREAD

**Issue by poojasunkara20** [Arize-ai/phoenix#4132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - Notebook Runtime [e.g. Jupyter, Colab]
 - Version [e.g. 0.0.1]

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by axiomofjoy** [comment]
@poojasunkara20 Thanks for using Phoenix. Can you send a screenshot to clarify which page your are on and which UI element you are interacting with?

**Comment by poojasunkara20** [comment]
I am trying to execute in google collab, This what I can see
<img width="892" alt="image" src="https://github.com/user-attachments/assets/20b9b9a5-6af7-4d2d-a698-f098def43a31">

**Comment by poojasunkara20** [comment]
After restarting, I can now see the page thank you..I have another query, To view the phoenix, After clicking that generated link for the app, I am getting 403 error, May I know why this is occuring?
<img width="809" alt="image" src="https://github.com/user-attachments/assets/fdd23a48-332c-4178-af9f-e550e9953120">

**Comment by axiomofjoy** [comment]
Hey @poojasunkara20 thanks for following up. Not sure what the cause of the issue was, but glad it is resolved.

Chrome's latest update unfortunately makes it so we can't use those links in Colab. You can still use `session.view()` in Colab, or you can run the notebook locally.
