### ISSUE TITLE
[BUG] annotations not propagating to dataset metadata

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4167]
Seems like annotations are not propagating to the dataset when a single span is exported to a dataset. See steps below.

https://github.com/user-attachments/assets/359f902d-d932-426f-83d4-45ff34936ed5

**Comment by anticorrelator** [comment]
Following up on this: is the single-span-insertion using the `add_spans_to_dataset` mutation?

**Comment by mikeldking** [comment]
> Following up on this: is the single-span-insertion using the `add_spans_to_dataset` mutation?

The Frontend first creates a preview. That preview lacks the annotations
