### ISSUE TITLE
[auth] add validation checks for `PHOENIX_SECRET` to ensure a strong symmetric key is used

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4177]
E.g., ensure the users passes in a 256-bit symmetric key.

**Comment by mikeldking** [comment]
Maybe just a warning?

**Comment by axiomofjoy** [comment]
Maybe a length check as well.

**Comment by mikeldking** [comment]
I think the error message could still be a bit clearer
