### ISSUE TITLE
[BUG] CrewAI Instrumentation Bugs

### ISSUE THREAD

**Issue by Jgilhuly** [Arize-ai/phoenix#4200]
**Describe the bug**
Did some dogfooding of crewai integration. Collecting a few bugs found here:

1. Base crew functions have span_kind = unknown. These should be CHAIN instead
<img width="486" alt="Screenshot 2024-08-09 at 9 07 48 AM" src="https://github.com/user-attachments/assets/5a144a6e-b680-4e98-8a60-009714019283">

2. We don't populate input or output at the top level for a crew. It would be good to show the final output from the crew when present:
<img width="1080" alt="Screenshot 2024-08-09 at 9 27 34 AM" src="https://github.com/user-attachments/assets/649eb5bf-a013-4840-b550-e11a6286a769">

**To Reproduce**
Create and kickoff any crew within CrewAI. Instrument with both our CrewAI and LangChain instrumentors

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Python local file connected to Docker Phoenix instance
 - Browser: Chrome

**Comment by avri-schneider** [comment]
@Jgilhuly Token usage count isn't reported either.

**Comment by mikeldking** [comment]
thanks for the report @avri-schneider - I'll get someone on the instrumentation team to take a look.

cc @harrisonchu
