### ISSUE TITLE
[BUG] Root span annotations missing from the trace details header

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4226]
See screenshot. Add an annotation - it's missing from the trace header
<img width="2056" alt="Screenshot 2024-08-13 at 11 10 20 AM" src="https://github.com/user-attachments/assets/5177549c-4040-454c-b718-a41da7641685">

**Comment by Parker-Stafford** [comment]
update just tested and just need to pull run `docker pull arizephoenix/phoenix:latest` also updated composes for openinference examples to always pull `pull_policy: always`
