### ISSUE TITLE
[auth][db] add uniqueness constraints on the users table

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4231]
there needs to be uniqueness constraints on email and username

<img width="535" alt="Screenshot 2024-08-13 at 2 00 46 PM" src="https://github.com/user-attachments/assets/aca91f40-110b-4ffe-8c45-5a7a383eceb3">

**Comment by axiomofjoy** [comment]
Surprised this isn't already there.

**Comment by axiomofjoy** [comment]
@mikeldking The unique constraint seems to be working for me. Are you using Postgres?

**Comment by axiomofjoy** [comment]
Closing this out for now, will reopen if the issue reappears
