### ISSUE TITLE
[BUG] Fix Tutorial Notebooks

### ISSUE THREAD

**Issue by P1et1e** [Arize-ai/phoenix#4258]
https://github.com/Arize-ai/phoenix/blob/main/tutorials/llama_index_search_and_retrieval_tutorial.ipynb

Notebook can't be executed any longer with Version 04.24.0 of Arize-Phoenix. 
Also add Tutorials for Inferences using a Docker Deployment for Arize-Phoenix

**Comment by RogerHYang** [comment]
Thanks for the report. The notebook above seems to be running fine for me. Can you please provide additional description on what the error message looks like?

**Comment by P1et1e** [comment]
Seems to work now. Actually don't can't figure out why it didn't work in the first place. 
But is it possible to add some tutorials on how to use the Inferences feature and embedding visualization with a Phoenix Docker Deployment ?

**Comment by RogerHYang** [comment]
> But is it possible to add some tutorials on how to use the Inferences feature and embedding visualization with a Phoenix Docker Deployment ?

Would you mind opening a new issue for that? It would help us manage our resources. Thanks.
