### ISSUE TITLE
[ENHANCEMENT] Improvements to workflow when Adding Custom LLM Evaluators

### ISSUE THREAD

**Issue by AparnaDhinakaran** [Arize-ai/phoenix#4289]
**Is your feature request related to a problem? Please describe.**
I can't modify the existing template + rails on the evaluator object to customize for my use case. 

**Describe the solution you'd like**
I'd like the eval template + rails to be parameters that I can pass in. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mikeldking** [comment]
From what I can tell you can pass a template into an LLMEvaluator (https://arize-phoenix.readthedocs.io/en/latest/api/evals.evaluators.html#evals.evaluators.LLMEvaluator)

@AparnaDhinakaran Does this not satisfy your use-case? https://github.com/Arize-ai/phoenix/blob/a3ff0f6b1c90f126db1249e877d2369ab9bffe02/packages/phoenix-evals/src/phoenix/evals/evaluators.py#L22

**Comment by AparnaDhinakaran** [comment]
Thanks for pointing this out! Hit a few snags, but was able to get it to work: 

Here's some feedback from along the way:

1. It wasn't clear what the format of record needed to be in the evaluator.evaluate function in the docs:
<img width="851" alt="Screenshot 2024-09-26 at 11 13 21 PM" src="https://github.com/user-attachments/assets/c437d3ea-f8e8-4ae3-98c3-27fd8f0f16a2">

Happy to add to the Phoenix readthedocs to make that more clear. 

2. It wasn't as easy to test the evaluate function when defining an experiment. RunLLM pointed me to the format of Record (https://github.com/arize-ai/phoenix/blob/main/packages/phoenix-evals/src/phoenix/evals/evaluators.py), but what I have is a dataset Example.  If I had a example.to_dict() method, that would've made it easier to just convert to record and then test my evaluate function. 
<img width="804" alt="Screenshot 2024-09-26 at 11 21 52 PM" src="https://github.com/user-attachments/assets/c642d1ff-0bad-49db-a736-4172ac93d0ad">

3. Passing the evaluator directly didn't work. I needed a wrapper function - not sure why, but RunLLM pointed me to this. This also wasn't clear in the docs, happy to add an example to the docs with an custom LLM template evaluator. 
```
# Define the wrapper function
def evaluator_wrapper(record):
    return good_summary_evaluator.evaluate(record, use_function_calling_if_available=False)
```

**Comment by AparnaDhinakaran** [comment]
I think the issue is here:  https://github.com/Arize-ai/phoenix/blob/main/src/phoenix/experiments/evaluators/base.py#L153


ExperimentEvaluator: TypeAlias = Union[
    Evaluator,
    Callable[..., EvaluatorOutput],
    Callable[..., Awaitable[EvaluatorOutput]],


This probably also needs to have LLMEvaluator in there
