### ISSUE TITLE
[BUG] Issue in get_qa_with_reference function in Phoenix eval

### ISSUE THREAD

**Issue by bhardwaj-vipul** [Arize-ai/phoenix#4300]
**Describe the bug**
[get_qa_with_reference](https://github.com/Arize-ai/phoenix/blob/a3ff0f6b1c90f126db1249e877d2369ab9bffe02/src/phoenix/trace/dsl/helpers.py#L71C5-L71C26) function gives the below error in case no context is retrieved.

```TypeError: sequence item 0: expected str instance, NoneType found``` 

The error is at [this](https://github.com/Arize-ai/phoenix/blob/a3ff0f6b1c90f126db1249e877d2369ab9bffe02/src/phoenix/trace/dsl/helpers.py#L115) point. In the below screenshot, I have `None` in the reference column as no context was retrieved. 

<img width="954" alt="Screenshot 2024-08-21 at 2 46 31 PM" src="https://github.com/user-attachments/assets/f47240ed-4a50-459f-bdb8-0a556da00036">

**To Reproduce**
The error can reproduced by submitting a query that will not retrieve any context. 

**Expected behavior**
`None` values in the context should be properly handled.

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - Notebook Runtime [e.g. Jupyter]
 - Browser [e.g. chrome]
 - Arize Phoenix  4.25.0
 - Arize Phoenix Evals 0.15.0

**Comment by bhardwaj-vipul** [comment]
I think I can help resolve it and would appreciate it if you could assign this to me.

**Comment by mikeldking** [comment]
hey @bhardwaj-vipul - thanks for the feedback. get_qa_with_reference tends to not work for every use case as RAG tends to be pretty different depending on your traces but happy for you to open a PR for us to take a look!

**Comment by mikeldking** [comment]
@bhardwaj-vipul maybe you could outline what fix you would like in this issue and we can discuss the details

**Comment by RogerHYang** [comment]
does adding a `.dropna()` work here?

**Comment by RogerHYang** [comment]
seems to work
```pycon
>>> import pandas as pd
>>> s = pd.Series([None, None])
>>> "\n".join(s.dropna())
''
```

**Comment by bhardwaj-vipul** [comment]
Yes, changing [this](https://github.com/Arize-ai/phoenix/blob/a3ff0f6b1c90f126db1249e877d2369ab9bffe02/src/phoenix/trace/dsl/helpers.py#L115) to 
`ref = df_docs.groupby("context.trace_id")["reference"].apply(lambda x: separator.join([ref for ref in x if ref is not None]))`
will work.
Lmk if this sounds good. I can create a PR.

**Comment by bhardwaj-vipul** [comment]
I have also found issue with [get_retrieved_documents](https://github.com/Arize-ai/phoenix/blob/a3ff0f6b1c90f126db1249e877d2369ab9bffe02/src/phoenix/trace/dsl/helpers.py#L37C5-L37C28). This will also fail in case the retriever fails to retrieve any context. 
I think empty context is not handled correctly in these functions. Let me know if this should be logged separately.
