### ISSUE TITLE
[BUG] - accessing a user-created project on app.phoenix.arize

### ISSUE THREAD

**Issue by dsaks9** [Arize-ai/phoenix#4365]
**Describe the bug**
The following bug pops up when I try to access a project that I have successfully accessed in the past and that has had traces successfully logged to it.

**To Reproduce**
Select the project from the main window.

**Expected behavior**
Access the project.

**Screenshots**
<img width="666" alt="image" src="https://github.com/user-attachments/assets/8f1aa757-72c0-47cd-b2e4-a41dd91ce052">

**Environment (please complete the following information):**
 - MacOS
 - Chrome

**Comment by mikeldking** [comment]
Hey @dsaks9 sorry you are facing issues with the hosted version. I've copied @exiao to see if they can troubleshoot it with the hosting team. Thanks for your patience

**Comment by exiao** [comment]
Looks like our GraphQL API is returning HTML after a 10s timeout. Instance version 4.22.1. Reproduction video:

https://github.com/user-attachments/assets/c6494d94-418f-48ad-8209-9b013b559852

![CleanShot 2024-08-26 at 14 27 15@2x](https://github.com/user-attachments/assets/fcfaa571-7aef-40db-aba7-1b5446af020b)

![CleanShot 2024-08-26 at 14 28 33@2x](https://github.com/user-attachments/assets/ce819d2d-5040-4186-9022-65c16e8bcb9c)

**Comment by exiao** [comment]
@dsaks9 can you try logging into your account again? We've upgraded the version and the dataset loads without error now.

**Comment by dsaks9** [comment]
yeah working now, thanks

**Comment by ljtsparky** [comment]
Hi, was that fix also available for helm deployed phoenix? I have exactly the same issue. My version was:
helm pull oci://registry-1.docker.io/arizephoenix/phoenix-helm --version 2.0.23

**Comment by mikeldking** [comment]
Hey @ljtsparky thanks for your message. Can you file a separate issue? The above was related to a load balancer. It's likely unrelated for on-prem deployments.
