### ISSUE TITLE
[BUG] Active Session doesn't update with Evals

### ISSUE THREAD

**Issue by camyoung93** [Arize-ai/phoenix#4389]
**Describe the bug**
When I generate evals, it doesn't reflect in my session until I click on the trace/span or refresh the page.

**To Reproduce**
1. Instrument an app within Phoenix
2. Pull down spans and execute evals
3. Log evals
4. Go to phoenix session and see no change
5. Click on a trace and it'll appear

**Expected behavior**
Evals used to appear as you logged them with no intervention

**Screenshots**
https://us02web.zoom.us/clips/share/_Kwq-gpGOWMxL9bSjlF4ZBFJ5hIXysbqW_SPo_Vmi5YnyWpWG0T82kXOgc2nXcb7_fqwOPxd3JpxvocRs4tzcCoS._64hABaYVDusKbpm

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime Juypter and Colab
 - Browser Chrome
 - Version 4.23.0

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by axiomofjoy** [comment]
Thanks @camyoung93. Can you upgrade to the latest version of Phoenix to see if this is still an issue?

**Comment by axiomofjoy** [comment]
It could also be that you have the stream refresh disabled. That recently moved into a settings configuration.
