### ISSUE TITLE
[BUG] 502 when using `phoenix.Client` with hosted phoenix

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4409]
User sets their environment variables the same as they would to log traces to hosted Phoenix. They attempt to get traces from the API using the client `get_trace_dataset` or `get_spans_dataframe` method, but get a 502 from the API.

https://arize-ai.slack.com/archives/C04R3GXC8HK/p1724789781231059

![image](https://github.com/user-attachments/assets/35aea094-4d2a-49d7-9a93-0deb38e3a9d2)

![image](https://github.com/user-attachments/assets/e6b78aa6-cfa0-4aa7-823c-3792327cda50)

![image](https://github.com/user-attachments/assets/f25c486e-f979-49d9-986e-6e0b64f0823d)

@dsaks9

Context: https://arize-ai.slack.com/archives/C04R3GXC8HK/p1724789781231059

**Comment by antoni0z** [comment]
I have a related error which I will report in a separate issue and will link here, when self hosting + accesing from the client I get Interanl server error front the server while trying to get both spans and traces

**Comment by antoni0z** [comment]
Link the related bug here as its also self-hosting https://github.com/Arize-ai/phoenix/issues/4420

**Comment by fjcasti1** [comment]
@antoni0z I have tested this and it works for me, can you confirm that the issue persists? Any additional information would be useful in that case
