### ISSUE TITLE
[BUG] Failed to export batch code: 405, reason: Method Not Allowed

### ISSUE THREAD

**Issue by taoari** [Arize-ai/phoenix#4529]
**Describe the bug**

**To Reproduce**

1. `docker compose up` allowing https://docs.arize.com/phoenix/deployment/docker
2. run the following script (from https://docs.arize.com/phoenix/tracing/integrations-tracing/langchain):

```python
from phoenix.otel import register

tracer_provider = register(
  project_name="my-llm-app", # Default is 'default'
  endpoint="http://localhost:6006",
)

from openinference.instrumentation.langchain import LangChainInstrumentor

LangChainInstrumentor().instrument(tracer_provider=tracer_provider)

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

prompt = ChatPromptTemplate.from_template("{x} {y} {z}?").partial(x="why is", z="blue")
chain = prompt | ChatOpenAI(model_name="gpt-3.5-turbo")
print(chain.invoke(dict(y="sky")))
```

and got the following errors:

Failed to export batch code: 405, reason: Method Not Allowed
Failed to export batch code: 405, reason: Method Not Allowed
Failed to export batch code: 405, reason: Method Not Allowed

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - Notebook Runtime [e.g. Jupyter, Colab]
 - Version [e.g. 0.0.1]

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by mikeldking** [comment]
hey @taoari - it should be

```
tracer_provider = register(
  project_name="my-llm-app", # Default is 'default'
  endpoint="http://localhost:6006/v1/traces",
)
```

the route for HTTP is /v1/traces slug. Can you try this?

**Comment by mfmezger** [comment]
it works with /v1/traces. 👍🏻  Maybe soemone can change here: https://docs.arize.com/phoenix/tracing/integrations-tracing/langchain in the docker tab and command line. Thank you! :).

**Comment by taoari** [comment]
@mikeldking Thank you! I believe the issue stems from an error in the document. It would be great if it could be corrected.

**Comment by mikeldking** [comment]
Ah good catch will fix.

Cc @Jgilhuly
