### ISSUE TITLE
[BUG] Missing Slash on HTTP Endpoint

### ISSUE THREAD

**Issue by camyoung93** [Arize-ai/phoenix#4563]
**Describe the bug**
When running in terminal, there's a missing slash on the HTTP endpoint so if you copy it, it will cause issues when setting up instrumentation.

**To Reproduce**
1. Run Phoenix via the terminal
2. See error

**Expected behavior**
Show HTTP: http://0.0.0.0:6006/v1/traces instead of http:/0.0.0.0:6006/v1/traces

**Screenshots**
![Screenshot 2024-09-10 at 11 34 00 AM](https://github.com/user-attachments/assets/c4fe6d94-fc1d-4ec0-82a5-5622b59b2659)

**Environment (please complete the following information):**
 - OS: Mac
 - Notebook Runtime - Local
 - Version v4.4.4rc4

**Comment by RogerHYang** [comment]
already [fixed](https://github.com/Arize-ai/phoenix/blob/58c770bb6c9df3715893a62457ff0373c311a4cb/src/phoenix/server/main.py#L353) in latest
