### ISSUE TITLE
Support Python 3.13

### ISSUE THREAD

**Issue by didmar** [Arize-ai/phoenix#4621]
Based on the `pyproject.toml`, Python 3.13 is not supported. Could it be added?

**Comment by axiomofjoy** [comment]
@didmar 3.13 has it's first official release in early October. We will add!

**Comment by didmar** [comment]
Great! FYI I was pointing that out because no other dependencies I use have an upper bound on the Python version, so maybe it is OK to not have a bound at all. Not a big deal anyway :)

**Comment by RogerHYang** [comment]
duplicate of https://github.com/Arize-ai/phoenix/issues/5082 (currently blocked)
