### ISSUE TITLE
Create content plan for evals + agents Q4 videos

### ISSUE THREAD

**Issue by Jgilhuly** [Arize-ai/phoenix#4666]

**Comment by jankowtf** [comment]
@Jgilhuly 
Hey there! 

I watched [AI Agent Mastery: Comparing Agent Frameworks](https://youtu.be/xWlMD6VtSd4?si=v7wlCHnbeFspeivZ) (great vid, btw) and was wondering if you already got around to publishing the code 😬

Don't mean to come off as pushy, just loved the clarity in your approaches and am eager to try for myself 🙂✌️

**Comment by Jgilhuly** [comment]
Hey @jankowtf apologies for the delayed response here! I ended up publishing the code just after your comment. You can find it all here: https://github.com/Arize-ai/phoenix/tree/main/examples/agent_framework_comparison

Hopefully you've already seen that, and sorry again for the delay!

**Comment by jankowtf** [comment]
@Jgilhuly 
I found it shortly after as well by just curiously keeping an eye on Aroze's GH 😉 

But thanks a lot for the reply nonetheless, appreciate it!

Really awesome "no BS and hands-on" series you guys are putting out there, looking forward to the future episodes - and possibly code 🙂✌️
