### ISSUE TITLE
[auth][oauth] set oauth2 state and nonce cookies with "lax" samesite policy

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4685]

**Comment by mikeldking** [comment]
Why lax?

**Comment by axiomofjoy** [comment]
@mikeldking If the user is not yet authenticated with the OAuth2 IDP and has to sign in for the first time, strict cookies won't be sent back to the callback URL.

https://stackoverflow.com/a/42220786
