### ISSUE TITLE
Wrong EnvVar referenced in docstring

### ISSUE THREAD

**Issue by enrico-stauss** [Arize-ai/phoenix#4787]
Hi, I noticed that you reference that `PHOENIX_OTEL_COLLECTOR_ENDPOINT` would be used of no endpoint is provided to `register` but in fact it is `PHOENIX_COLLECTOR_ENDPOINT`.

https://github.com/Arize-ai/phoenix/blob/26b422f70dd5e7b295f79a30a82dab1cc1ed9173/packages/phoenix-otel/src/phoenix/otel/otel.py#L54C29-L54C59

Cheers
Enrico

**Comment by axiomofjoy** [comment]
Good catch!
