### ISSUE TITLE
[playground][ui] dataset input mode

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4803]
rough list of todos

- [ ] dataset selector with ability to clear dataset
- [ ] fetch dataset examples
- [ ] display examples table, reference output, number of examples
- [ ] pull variables from examples input json, if an example doesn't make use of any of its variables, show warning
- [ ] plumb dataset_id through to subscription / mutation
- [ ] get output streaming or non streaming working for each example simultaneously
- [ ] stretch full-text toggle - might just be supported by table already if we can reuse dataset examples table

**Comment by Parker-Stafford** [comment]
these are all complete, irrelevant, or tracked elsewhere, closing
