### ISSUE TITLE
[playground] llm span to playground parameter parsing utils

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4886]
Analyze the contents of an LLM Span (e.g. the attributes) and parse out as much structured data (e.g. data to be passed to the playground) as possible. This utility should be used to mount state in the playground.

- [x] #4922
- [x] parse output messages
- [x] parse invocation parameters
- [x] add fallbacks for variant input / output
  - input messages with single content
  - input messages with multipart content
  - input.value
  - prompt templates
- [ ] parse variables
- [ ] parse templates?
- [x] #5180

**Comment by axiomofjoy** [comment]
calling this one done
