### ISSUE TITLE
[playground][ui] mustache template editor for codemirror

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4888]
syntax highlighting for `{{` and `}}` in the templating ui by building a codemirror extension.

Note that mustache as a "language" supports HTML and template iteration of input

**Comment by cephalization** [comment]
Relevant documents:
- https://codemirror.net/5/demo/mustache.html
- https://github.com/codemirror/lang-example/tree/main
- https://codemirror.net/examples/lang-package/

**Comment by cephalization** [comment]
See #4943
