### ISSUE TITLE
[playground][instrumentation] semantic convention for output schema definition (JSON mode)

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4896]

**Comment by RogerHYang** [comment]
completed by https://github.com/Arize-ai/openinference/pull/904

**Comment by RogerHYang** [comment]
see also https://github.com/Arize-ai/phoenix/issues/4904#issuecomment-2447784754

**Comment by RogerHYang** [comment]
Closing for now because it's not strictly needed for playground. But we'll revisit in the future.
