### ISSUE TITLE
[playground][instrumentation] openai support for output schema

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4904]

**Comment by RogerHYang** [comment]
completed by https://github.com/Arize-ai/openinference/pull/904

**Comment by RogerHYang** [comment]
Going to punt on this because it's already captured by invocation parameters, which is sufficient for playground purposes.

<img width="457" alt="Screenshot 2024-10-30 at 9 45 19 AM" src="https://github.com/user-attachments/assets/f6873e46-1110-47d5-9319-badb430bdab5">
