### ISSUE TITLE
[ENHANCEMENT] Support LiteLLM inference tracing

### ISSUE THREAD

**Issue by olafgeibig** [Arize-ai/phoenix#4910]
Developing a LLM based app with LiteLLM instead of using a heavy weight framework like LangChain and LlamaIndex has become very popular recently but phoenix only supports LiteLLM for evals.

Autoinstrumentation of LiteLLM via the already exiting opentracing library.

**Comment by axiomofjoy** [comment]
Hey @olafgeibig, it's not clear to me why the LiteLLM code snippet is not working for you. Can you try the example [here](https://github.com/Arize-ai/openinference/blob/main/python/instrumentation/openinference-instrumentation-litellm/examples/litellm.py)?

**Comment by olafgeibig** [comment]
The example is working. I figured out the difference to make my code work. I did:

```python
from litellm import completion
...
completion(...
```

and it works now after I imported all of litellm like in the example:
```python
import litellm
...
litellm.completion(...
```

**Comment by axiomofjoy** [comment]
@olafgeibig Good catch. This looks like a bug in our instrumentation. I've filed an issue [here](https://github.com/Arize-ai/phoenix/issues/4963).

> How to set the project name?

Please see the docs [here](https://docs.arize.com/phoenix/tracing/how-to-tracing/customize-traces#log-to-a-specific-project).

**Comment by olafgeibig** [comment]
Thanks, I missed that.
