### ISSUE TITLE
[BUG] Authentication issue from tutorial

### ISSUE THREAD

**Issue by vannestn** [Arize-ai/phoenix#4920]
**Describe the bug**
When running the Hosted Phoenix OpenAI Tutorial, an authentication bug is occurring where retrieving spans from the hosted phoenix instance is throwing a '302' error because of a redirect to a login page. 

**To Reproduce**
1. Go to 'https://github.com/Arize-ai/phoenix/blob/main/tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb'
2. Click the 'Run All' button that runs all of the cells for the entire notebook 
3. Provide an OpenAI API Key
4. Create an account at https://app.phoenix.arize.com and login. 
5. When a server is created for Phoenix, use the lefthand 'Keys' section to pull API keys for the instance. 
6. Provide the jupyter notebook with the API key from the 'Keys' section of the Phoenix instance
<img width="717" alt="Screenshot 2024-10-08 at 5 28 45 PM" src="https://github.com/user-attachments/assets/5eb8a282-4d10-47f0-a479-5fdc43639cfa">

7. Open https://app.phoenix.arize.com/projects/ and navigate to your project to confirm that all traces are correctly being captured from running the prior steps in the notebook.
8. Run 'Step 3: Access Phoenix Instance' code block to generate the error:
```
{
	"name": "HTTPStatusError",
	"message": "Redirect response '302 Found' for url 'https://app.phoenix.arize.com/v1/spans?project_name=default&project-name=default'
Redirect location: '/login'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302",
	"stack": "---------------------------------------------------------------------------
HTTPStatusError                           Traceback (most recent call last)
Cell In[6], line 14
     11 # Get spans to exclude the last 24 hours
     12 end = datetime.now() - timedelta(days=0)
---> 14 phoenix_df = px_client.query_spans(start_time=start, end_time=end)
     15 phoenix_df.head()

File ~/Desktop/github-personal/phoenix/myenv/lib/python3.12/site-packages/phoenix/session/client.py:194, in Client.query_spans(self, start_time, end_time, limit, root_spans_only, project_name, stop_time, timeout, *queries)
    192 elif response.status_code == 422:
    193     raise ValueError(response.content.decode())
--> 194 response.raise_for_status()
    195 source = BytesIO(response.content)
    196 results = []

File ~/Desktop/github-personal/phoenix/myenv/lib/python3.12/site-packages/httpx/_models.py:763, in Response.raise_for_status(self)
    761 error_type = error_types.get(status_class, \"Invalid status code\")
    762 message = message.format(self, error_type=error_type)
--> 763 raise HTTPStatusError(message, request=request, response=self)

HTTPStatusError: Redirect response '302 Found' for url 'https://app.phoenix.arize.com/v1/spans?project_name=default&project-name=default'
Redirect location: '/login'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302"
}
```

**Expected behavior**
The authentication should pass without issue when Client is passed the 'PHOENIX_API_KEY'

**Screenshots**
The hosted Phoenix instance is capturing the traces without issue. It's only the authentication in the final step 'Step 3: Access Phoenix Instance' that throws a '302' error. 
<img width="975" alt="Screenshot 2024-10-08 at 5 13 18 PM" src="https://github.com/user-attachments/assets/cabbc831-98ea-42dd-81cd-157fc3529554">

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Colab and Cursor jupyter notebook instances
 - Browser: Chrome

**Additional context**
None.

**Comment by fjcasti1** [comment]
Hey @vannestn, we addressed the issue and was fixed time ago. Will close the issue but feel free to reopen if problems persist
