### ISSUE TITLE
[BUG] Problems with using phoenix.otel.register with env variables

### ISSUE THREAD

**Issue by exiao** [Arize-ai/phoenix#4921]
**Describe the bug**
When using HTTP tracing using environment variables, it does not trace the openai call correctly. It's possible it does not know which URL to send to based on the environment variable when using phoenix.otel.register. When changing it to put the URL in the register function, it works correctly. This is for my own docker instance deployment, which only accepts traces on port 6006, since it can only have one port open at a time.

Does NOT work
```python
from phoenix.otel import register
from openinference.instrumentation.openai import OpenAIInstrumentor
import os
os.environ["PHOENIX_COLLECTOR_ENDPOINT"] = "https://phoenix-kd03.onrender.com"
tracer_provider = register(batch=True)
OpenAIInstrumentor().instrument(tracer_provider=tracer_provider, skip_dep_check=True)
```

Works
```python
from phoenix.otel import register
from openinference.instrumentation.openai import OpenAIInstrumentor
import os
tracer_provider = register(batch=True, endpoint="http://phoenix-kd03.onrender.com/v1/traces")
OpenAIInstrumentor().instrument(tracer_provider=tracer_provider, skip_dep_check=True)
```

Error of the NOT working trying to send traces over GRPC:
```bash
INFO:     127.0.0.1:51443 - "POST /api/choices HTTP/1.1" 200 OK
Transient error StatusCode.DEADLINE_EXCEEDED encountered while exporting traces to phoenix-kd03.onrender.com:4317, retrying in 1s.
```

**Comment by mikeldking** [comment]
See readme: https://github.com/Arize-ai/phoenix/tree/main/packages/phoenix-otel#specifying-the-endpoint-directly
