### ISSUE TITLE
[ENHANCEMENT] CrewAI migrated to LiteLLM

### ISSUE THREAD

**Issue by olafgeibig** [Arize-ai/phoenix#4964]
The crewAI related docs of Phoenix are not reflecting the latest development of crewAI. As of [0.63.0](https://github.com/crewAIInc/crewAI/releases/tag/v0.63.0) crewAI has migrated from LangChain to LiteLLM for calling models. The Phoenix docs do not reflect that. LiteLLM tracing with Phoenix is possible but it's not documented.

1. Add LiteLLM tracing to the docs
2. Update the crewAI related docs with an example for the legacy versions with LangChain and for the newer version with LiteLLM

**Comment by mikeldking** [comment]
Good call out @olafgeibig - we will get this documented. cc @Jgilhuly
