### ISSUE TITLE
[sessions][ui] session slideover with trace previews

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5008]

**Comment by mikeldking** [comment]
Planning for next sprint

**Comment by mikeldking** [comment]
Very early mocks here: https://www.figma.com/design/nvX5JTTdZddvLIYEjPIEM8/Phoenix-H2-2024?node-id=230-3098&t=1q0Vx815poXc56ov-1

**Comment by Parker-Stafford** [comment]
closing as complete in #5225
