### ISSUE TITLE
[sessions][ui] from a trace, give a way to navigate to the "parent" session

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5009]
As a user, I want to know if a trace is part of a session and to naviate "up" to the session

**Comment by mikeldking** [comment]
<img width="2056" alt="Screenshot 2024-10-15 at 10 10 02 AM" src="https://github.com/user-attachments/assets/403cd44d-3c79-473b-8dd4-7bd9e1af5d5e">

**Comment by Parker-Stafford** [comment]
completed in #5229
