### ISSUE TITLE
[ENHANCEMENT] filter experiment results

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#5015]
> In the UI I don't see a way to filter experiment results based on outcomes. Is this something you plan to add?

Users want a way to filter their experiment results based on evaluations.

Context: https://github.com/Arize-ai/phoenix/discussions/4985#discussioncomment-10939930

**Comment by omrihar** [comment]
Here the idea is to be able to find specific examples in a dataset where, for example, the QA correctness scored 1 but relevance was 0, or where Human vs AI gave a score of 0 even though QA correctness was 1. 
Another case is simply to find which rows failed a specific run of an experiment.

**Comment by axiomofjoy** [comment]
Closing this issue as a duplicate of #5681
