### ISSUE TITLE
Openinferencetracer error while using AzureOpenAI

### ISSUE THREAD

**Issue by RajeswariKumaran** [Arize-ai/phoenix#5017]
I am using AzureOpenAI for a rag based retrieval with source. I use langchain instrumentor. I get the following errors:

Error in OpenInferenceTracer.on_chain_start callback: ValidationError(model='Run', errors=[{'loc': ('__root__',), 'msg': "
argument of type 'NoneType' is not iterable", 'type': 'type_error'}])

Error in OpenInferenceTracer.on_chain_end callback: TracerException('No indexed run ID 9f0fd197-2815-426a-8742-ce9c39e2f89
7.')
Please suggest how to resolve these.

Given below are the versions used:

langchain==0.3.0
langchain-community==0.3.0
langchain-core==0.3.0
langchain-openai==0.2.0
langchain-text-splitters==0.3.0
openai==1.45.1
openinference-instrumentation==0.1.18
openinference-instrumentation-langchain==0.1.28
openinference-semantic-conventions==0.1.10
opentelemetry-api==1.27.0
opentelemetry-exporter-otlp==1.27.0
opentelemetry-exporter-otlp-proto-common==1.27.0
opentelemetry-exporter-otlp-proto-grpc==1.27.0
opentelemetry-exporter-otlp-proto-http==1.27.0
opentelemetry-instrumentation==0.48b0
opentelemetry-instrumentation-asgi==0.48b0
opentelemetry-instrumentation-fastapi==0.48b0
opentelemetry-proto==1.27.0
opentelemetry-sdk==1.27.0
opentelemetry-semantic-conventions==0.48b0
opentelemetry-util-http==0.48b0

**Comment by mikeldking** [comment]
Thanks for filing this issue. We will investigate and let you know.

**Comment by mikeldking** [comment]
just assigning some folks for next sprint @Arize-ai/oss-python

**Comment by RogerHYang** [comment]
Could you please provide a reproducible example? The last time we encountered a similar issue, it was due to a custom subclass not properly implementing an abstract method, which led to a validation error.
