### ISSUE TITLE
[BUG] when navigating from an LLM span to the playground, the variables in the inputs is stale

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5060]
**Describe the bug**
Going from an llm span to the playground produces incorrect "question" variable value

<img width="1810" alt="Screenshot 2024-10-16 at 10 02 06 PM" src="https://github.com/user-attachments/assets/01f182c3-b18f-41a1-b610-8eed82a06b90">

**Comment by cephalization** [comment]
I have a TODO comment to address this, came sooner than expected 😂
