### ISSUE TITLE
[BUG] tool calls show up as AI calls in the UI, should be displayed as tool

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5061]
<img width="2043" alt="Screenshot 2024-10-16 at 10 08 21 PM" src="https://github.com/user-attachments/assets/47c4976a-71d8-47f3-90ee-be36966ccc42">

**Comment by axiomofjoy** [comment]
Whoops

**Comment by axiomofjoy** [comment]
Actually, a little confused on the bug here. This is an assistant message, similar to the one shown below:

![Screenshot 2024-10-17 at 4 29 57 PM](https://github.com/user-attachments/assets/c00a5133-7517-4d98-8ecf-cc86f2ece530)

**Comment by axiomofjoy** [comment]
closing as i think this is the expected behavior. feel free to reopen
