### ISSUE TITLE
[playground][gql] filter down the list of providers depending on whether or not client packages are intalled

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5116]
As a user, I might not want to install all the clients for llms I don't care about. I might do

```
pip install 'arize-phoenix[openai]`
```

And expect the playground to only show openai in the dropdown

**Comment by mikeldking** [comment]
Note the UI should probably also give guidance on how to install the extras as well

**Comment by axiomofjoy** [comment]
unassigning myself since it sounded like you started in on this @anticorrelator
