### ISSUE TITLE
[BUG]Issue with '.' in eval template, wasn't an issue in past version of phoenix

### ISSUE THREAD

**Issue by arizedatngo** [Arize-ai/phoenix#5138]
when you pull data out of phoenix, the natural column name is like attribut.llm.input_messages (Image 1)
But you can’t run your eval template with that name because it doesn’t work with {} brackets as variables (Image 2)
You actually have to rename the columns to simpler names, without the . to get it to work (Image 3 and working) (edited) 

At one point this was working normally with the '.' convention

![image](https://github.com/user-attachments/assets/cc2c3756-23ca-4e99-be54-0cdb4d85489b)
![image](https://github.com/user-attachments/assets/fe31d55f-973f-4106-bafb-a91055fc2335)
![image](https://github.com/user-attachments/assets/0eb85344-307c-4a16-bbc5-ebf4ca18336d)

**Comment by arizedatngo** [comment]
Discussing with @anticorrelator and @jlopatec on what the game plan should be

**Comment by anticorrelator** [comment]
completed in #5436
