### ISSUE TITLE
[ENHANCEMENT] Pretty print structured outputs

### ISSUE THREAD

**Issue by Jgilhuly** [Arize-ai/phoenix#5140]
**Is your feature request related to a problem? Please describe.**
Structured outputs from providers like OpenAI are currently displayed as plaintext in the UI. This removes some of the benefit of using structured outputs, and can be hard to read and parse through.

**Describe the solution you'd like**
We should pretty print, indent, or format structured output data in the UI.

![Screenshot 2024-10-21 at 2 46 13 PM](https://github.com/user-attachments/assets/b9a8b790-84f0-47b9-ac31-86b2dc8f5507)

**Comment by axiomofjoy** [comment]
Good callout

**Comment by sraibagiwith100x** [comment]
yes please 🙏 this may a small thing but BIG impact to my manual inspection workflow

**Comment by mikeldking** [comment]
This is released in 7.3 @sraibagiwith100x !
