### ISSUE TITLE
[playground] Playground output displays escaped symbols

### ISSUE THREAD

**Issue by cephalization** [Arize-ai/phoenix#5155]
![2024-10-22 14 08 07](https://github.com/user-attachments/assets/c2efbdf0-2758-474b-bc00-acf65bdc0e54)

Notably, the final output in the span is not escaped in this way, this may be an issue with the chunk streaming instead of UI. For that reason I won't mark this issue as ui for now.

<img width="955" alt="image" src="https://github.com/user-attachments/assets/6b0d0cab-79ce-4995-833d-e9b63fed6622">

**Comment by cephalization** [comment]
Ah this is simply because the output is markdown, and the trace viewer renders the escaped characters properly while the output component in the playground renders in plaintext

**Comment by cephalization** [comment]
Should we implement the text/markdown toggle like the span viewer has?

**Comment by axiomofjoy** [comment]
> Should we implement the text/markdown toggle like the span viewer has?

Sounds good, we have a ticket for this [here](https://github.com/Arize-ai/phoenix/issues/5112).

**Comment by Parker-Stafford** [comment]
> > Should we implement the text/markdown toggle like the span viewer has?
> 
> Sounds good, we have a ticket for this [here](https://github.com/Arize-ai/phoenix/issues/5112).

thanks @axiomofjoy closing in favor of #5112
