### ISSUE TITLE
[BUG] Failed to export batch code: 401, reason: Invalid token

### ISSUE THREAD

**Issue by mhrsavci** [Arize-ai/phoenix#5162]
**Describe the bug**

**To Reproduce**
docker compose up allowing https://docs.arize.com/phoenix/deployment/docker
run the following script (from https://docs.arize.com/phoenix/tracing/integrations-tracing/langchain):

```python
from phoenix.otel import register

tracer_provider = register(
  project_name="my-llm-app", # Default is 'default'
  endpoint="http://localhost:6006/v1/traces",
)

from openinference.instrumentation.langchain import LangChainInstrumentor

LangChainInstrumentor().instrument(tracer_provider=tracer_provider)

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

prompt = ChatPromptTemplate.from_template("{x} {y} {z}?").partial(x="why is", z="blue")
chain = prompt | ChatOpenAI(model_name="gpt-3.5-turbo")
chain.invoke(dict(y="sky"))
```

Outputs: 

Overriding of current TracerProvider is not allowed
Attempting to instrument while already instrumented
Failed to export batch code: 401, reason: Invalid token
OpenTelemetry Tracing Details
|  Phoenix Project: my-llm-app
|  Span Processor: SimpleSpanProcessor
|  Collector Endpoint: http://localhost:6006/v1/traces
|  Transport: HTTP
|  Transport Headers: {}
|  
|  Using a default SpanProcessor. `add_span_processor` will overwrite this default.
|  
|  `register` has set this TracerProvider as the global OpenTelemetry default.
|  To disable this behavior, call `register` with `set_global_tracer_provider=False`.

Failed to export batch code: 401, reason: Invalid token
Failed to export batch code: 401, reason: Invalid token

**Comment by axiomofjoy** [comment]
Hey @mhrsavci 👋 It looks like you might be running an authenticated instance of Phoenix. If that is the case, you'll need to set the `PHOENIX_API_KEY` environment variable or attach a Phoenix API key via headers. Please see the documentation [here](https://docs.arize.com/phoenix/setup/authentication#sending-openinference-traces) and let us know if that works!

**Comment by axiomofjoy** [comment]
Awesome!
