### ISSUE TITLE
inconsistent openetelemetry versions

### ISSUE THREAD

**Issue by pavanjava** [Arize-ai/phoenix#5185]
**Describe the bug**
Followed the documentation and integrated LlamaIndex and i get `No module named 'opentelemetry.semconv.attributes'` Error.

**To Reproduce**
1. Follow documentation and the error is evident

**Expected behavior**
Should be no error and the traces should be in phoenix web ui

**Screenshots**
If <img width="1141" alt="Screenshot 2024-10-25 at 1 09 27 AM" src="https://github.com/user-attachments/assets/49847e8a-093d-4cca-ae1b-157e0a363efb">, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: MacOS 15.x
 - Python Runtime v3.10

**Additional context**
previous ticket: https://github.com/Arize-ai/phoenix/issues/5177

**Comment by pavanjava** [comment]
Any update?

**Comment by axiomofjoy** [comment]
Hey @pavanjava, sorry you're experiencing this issue. Can you point me to the documentation or example you're following? Can you also re-send the output of `pip list` so we can examine your installed dependencies?

**Comment by pavanjava** [comment]
@axiomofjoy

The doc I am following is:
https://docs.arize.com/phoenix/tracing/integrations-tracing/llamaindex

pip list:

Package                                   Version
----------------------------------------- ------------
aiohappyeyeballs                          2.4.3
aiohttp                                   3.10.10
aioitertools                              0.12.0
aiosignal                                 1.3.1
aiosqlite                                 0.20.0
alembic                                   1.13.3
annotated-types                           0.7.0
anyio                                     4.6.2.post1
appdirs                                   1.4.4
arize-phoenix                             5.5.2
arize-phoenix-evals                       0.17.2
arize-phoenix-otel                        0.6.1
attrs                                     24.2.0
Authlib                                   1.3.2
beautifulsoup4                            4.12.3
cachetools                                5.5.0
certifi                                   2024.8.30
cffi                                      1.17.1
charset-normalizer                        3.4.0
click                                     8.1.7
cryptography                              43.0.3
dataclasses-json                          0.6.7
datasets                                  3.0.2
deepeval                                  1.4.4
Deprecated                                1.2.14
dill                                      0.3.8
dirtyjson                                 1.0.8
distro                                    1.9.0
docx2txt                                  0.8
execnet                                   2.1.1
fast-hdbscan                              0.2.0
fastapi                                   0.115.3
filelock                                  3.16.1
frozenlist                                1.5.0
fsspec                                    2024.9.0
googleapis-common-protos                  1.65.0
graphql-core                              3.2.5
greenlet                                  3.1.1
grpc-interceptor                          0.15.4
grpcio                                    1.63.2
grpcio-tools                              1.62.3
h11                                       0.14.0
h2                                        4.1.0
hpack                                     4.0.0
httpcore                                  1.0.6
httptools                                 0.6.4
httpx                                     0.27.2
huggingface-hub                           0.26.1
hyperframe                                6.0.1
idna                                      3.10
importlib-metadata                        7.0.0
iniconfig                                 2.0.0
Jinja2                                    3.1.4
jiter                                     0.6.1
joblib                                    1.4.2
jsonpatch                                 1.33
jsonpointer                               3.0.0
langchain                                 0.3.4
langchain-community                       0.3.3
langchain-core                            0.3.12
langchain-openai                          0.2.3
langchain-text-splitters                  0.3.0
langsmith                                 0.1.137
litserve                                  0.2.3
llama-cloud                               0.1.4
llama-index                               0.11.19
llama-index-agent-openai                  0.3.4
llama-index-callbacks-arize-phoenix       0.2.1
llama-index-cli                           0.3.1
llama-index-core                          0.11.20
llama-index-embeddings-ollama             0.3.1
llama-index-embeddings-openai             0.2.5
llama-index-indices-managed-llama-cloud   0.4.0
llama-index-legacy                        0.9.48.post3
llama-index-llms-ollama                   0.3.4
llama-index-llms-openai                   0.2.16
llama-index-multi-modal-llms-openai       0.2.3
llama-index-program-openai                0.2.0
llama-index-question-gen-openai           0.2.0
llama-index-readers-file                  0.2.2
llama-index-readers-llama-parse           0.3.0
llama-index-vector-stores-qdrant          0.3.2
llama-parse                               0.5.11
llvmlite                                  0.43.0
Mako                                      1.3.6
markdown-it-py                            3.0.0
MarkupSafe                                3.0.2
marshmallow                               3.23.0
mdurl                                     0.1.2
multidict                                 6.1.0
multiprocess                              0.70.16
mypy-extensions                           1.0.0
nest-asyncio                              1.6.0
networkx                                  3.4.2
nltk                                      3.9.1
numba                                     0.60.0
numpy                                     1.26.4
ollama                                    0.3.3
openai                                    1.52.2
openinference-instrumentation             0.1.18
openinference-instrumentation-llama-index 3.0.2
openinference-semantic-conventions        0.1.11
opentelemetry-api                         1.24.0
opentelemetry-exporter-otlp               1.24.0
opentelemetry-exporter-otlp-proto-common  1.24.0
opentelemetry-exporter-otlp-proto-grpc    1.24.0
opentelemetry-exporter-otlp-proto-http    1.24.0
opentelemetry-instrumentation             0.48b0
opentelemetry-proto                       1.24.0
opentelemetry-sdk                         1.24.0
opentelemetry-semantic-conventions        0.45b0
orjson                                    3.10.10
packaging                                 24.1
pandas                                    2.2.3
pillow                                    11.0.0
pip                                       24.1.2
pluggy                                    1.5.0
portalocker                               2.10.1
propcache                                 0.2.0
protobuf                                  4.25.5
psutil                                    6.1.0
pyarrow                                   17.0.0
pycparser                                 2.22
pydantic                                  2.9.2
pydantic_core                             2.23.4
pydantic-settings                         2.6.0
Pygments                                  2.18.0
pynndescent                               0.5.13
pypdf                                     4.3.1
pysbd                                     0.3.4
pytest                                    8.3.3
pytest-repeat                             0.9.3
pytest-xdist                              3.6.1
python-dateutil                           2.9.0.post0
python-dotenv                             1.0.1
python-multipart                          0.0.12
pytz                                      2024.2
PyYAML                                    6.0.2
qdrant-client                             1.12.0
ragas                                     0.2.2
regex                                     2024.9.11
requests                                  2.32.3
requests-toolbelt                         1.0.0
rich                                      13.9.3
scikit-learn                              1.5.2
scipy                                     1.14.1
sentry-sdk                                2.17.0
setuptools                                70.3.0
shellingham                               1.5.4
six                                       1.16.0
sniffio                                   1.3.1
soupsieve                                 2.6
SQLAlchemy                                2.0.36
sqlean.py                                 3.45.1
starlette                                 0.41.0
strawberry-graphql                        0.243.1
striprtf                                  0.0.26
tabulate                                  0.9.0
tenacity                                  8.4.2
threadpoolctl                             3.5.0
tiktoken                                  0.8.0
tqdm                                      4.66.5
typer                                     0.12.5
typing_extensions                         4.12.2
typing-inspect                            0.9.0
tzdata                                    2024.2
umap-learn                                0.5.6
urllib3                                   2.2.3
uvicorn                                   0.32.0
uvloop                                    0.21.0
watchfiles                                0.24.0
websockets                                13.1
wrapt                                     1.16.0
xxhash                                    3.5.0
yarl                                      1.16.0
zipp                                      3.20.2

**Comment by axiomofjoy** [comment]
> ```
> opentelemetry-api                         1.24.0
> opentelemetry-exporter-otlp               1.24.0
> opentelemetry-exporter-otlp-proto-common  1.24.0
> opentelemetry-exporter-otlp-proto-grpc    1.24.0
> opentelemetry-exporter-otlp-proto-http    1.24.0
> opentelemetry-instrumentation             0.48b0
> opentelemetry-proto                       1.24.0
> opentelemetry-sdk                         1.24.0
> opentelemetry-semantic-conventions        0.45b0
> ```

Hi @pavanjava. It appears that these OpenTelemetry versions are incompatible. Can you try these versions (I grabbed from Colab).

```
opentelemetry-api                         1.27.0
opentelemetry-exporter-otlp               1.27.0
opentelemetry-exporter-otlp-proto-common  1.27.0
opentelemetry-exporter-otlp-proto-grpc    1.27.0
opentelemetry-exporter-otlp-proto-http    1.27.0
opentelemetry-instrumentation             0.48b0
opentelemetry-proto                       1.27.0
opentelemetry-sdk                         1.27.0
opentelemetry-semantic-conventions        0.48b0
```

**Comment by pavanjava** [comment]
Sure, let me give it a shot right away.

**Comment by pavanjava** [comment]
@axiomofjoy 

This is the issue, because I have evaluation framework `deepevals 1.4.4` integrated in my application and that is pointing to `opentelemetry-api 1.24.0` 

The conflict is caused by:
    The user requested opentelemetry-api==1.27.0
    deepeval 1.4.4 depends on opentelemetry-api~=1.24.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

**Comment by axiomofjoy** [comment]
Hey @pavanjava. Phoenix [loosely pins `opentelemetry`](https://github.com/Arize-ai/phoenix/blob/a1886a022056444c79f244e7750bb9f745ced64b/pyproject.toml#L41), so it is not causing the conflict. In this case, `deepeval==1.4.4` is pinning `opentelemetry-api~=1.24.0` so it's incompatible with `opentelemetry-api>=1.25.0`, but we've explicitly asked to install `opentelemetry-api==1.27.0` with the previous requirements I sent. We need to install a set of `opentelemetry` versions that are compatible with each other and with `deepevals==1.4.4`. For example,

```
opentelemetry-api                        1.24.0
opentelemetry-exporter-otlp              1.24.0
opentelemetry-exporter-otlp-proto-common 1.24.0
opentelemetry-exporter-otlp-proto-grpc   1.24.0
opentelemetry-exporter-otlp-proto-http   1.24.0
opentelemetry-instrumentation            0.45b0
opentelemetry-proto                      1.24.0
opentelemetry-sdk                        1.24.0
opentelemetry-semantic-conventions       0.45b0
```

**Comment by axiomofjoy** [comment]
Hey @pavanjava, I'm closing this issue since it is does not appear to be caused by Phoenix, but feel free to re-open or just respond in the thread if the issue persists. Thanks!
