### ISSUE TITLE
[playground][instrumentation] capture tool ids in openai js instrumentaiton

### ISSUE THREAD

**Issue by Parker-Stafford** [Arize-ai/phoenix#5195]
This needs to go on tool role messages at message.tool.id and on each tool call message.tool_calls.{i}.tool_call.id

need to add the equivalent of this into js semantic conventions as well https://github.com/Arize-ai/openinference/pull/1085

**Comment by cephalization** [comment]
See https://github.com/Arize-ai/openinference/pull/1105
