### ISSUE TITLE
[ENHANCEMENT] show summary of tabular information in cards for tabular embeddings

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#522]
**Is your feature request related to a problem? Please describe.**
Currently, we show blank cards in the panel below when no image or text is associated with an embedding feature. We should display some information about the data point here.

![Screenshot 2023-04-04 at 4 46 58 PM](https://user-images.githubusercontent.com/15664869/230173955-d384408a-9dfa-4eee-8b5a-d68a7dc03f47.png)

**Describe the solution you'd like, Describe alternatives you've considered**
Possibilities:
- Show a few feature values for each data point
- Show a prediction ID for the data point

**Comment by mikeldking** [comment]
Done
