### ISSUE TITLE
[BUG] llm_classify doesn't work without concurrency explicitly stated in a notebook.

### ISSUE THREAD

**Issue by exiao** [Arize-ai/phoenix#5240]
See screenshot. Without adding concurrency explicitly, it errors out and does not allow the function to run.

We should have a default concurrency when it is not added.

```python
llm_classify(
    dataframe=response_df,
    template=PARAMETER_EXTRACTION_EVAL_TEMPLATE.format(function_info=functions),
    model=OpenAIModel('gpt-4o'),
    rails=rails
)
```

![Screenshot 2024-10-31 at 02 48@2x](https://github.com/user-attachments/assets/ec2b8716-7b29-44f5-bbe4-e0675f28429d)

**Comment by exiao** [comment]
The llm_classify function will also error out if the template variable is in the dataframe, but the value is None instead of "".

**Comment by exiao** [comment]
### Some feature requests to track separately:

llm_classify also has quite a lot of parameters that are needed to get value out of the function. By default, I think we should:
1. Include explanations
2. Include the prompt
3. Include prompt variables
4. Do not require the user to specify concurrency.

After using llm_classify on a dataframe that a user created, there should be a way to log the evaluation to phoenix without tying it to a trace. The log_evaluations function does not allow for this capability.

**Comment by RogerHYang** [comment]
Thanks for the report @exiao. What version of `arize-phoenix-evals` are you using?

**Comment by RogerHYang** [comment]
This is resolved as follows.

This line
```python
model=OpenAIModel('gpt-4o'),
```
should instead be
```python
model=OpenAIModel(model='gpt-4o'),
```
