### ISSUE TITLE
[BUG] Unexpected token '<', "<!DOCTYPE "... is not valid JSON after Upgrade

### ISSUE THREAD

**Issue by PacoFarina** [Arize-ai/phoenix#5243]
**Describe the bug**
My setup is a Phoenix hosted as an Azure Webapp built from the docker hub image and using a Postresql db. I have a Dev environment and a Preproduction environment running on version 4.5.0. I decided to upgrade to 5.6.0 in both envs (different webapps). By simply pointing to the 5.6.0 release image from docker hub in the deployment center and restarting the webapp, the Dev  env webapp was upgraded and works fine.

However, when replicating the procedure to upgrade the Preprod webapp, the UI fails to load while showing the error messafe 

`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

**To Reproduce**
1. Upgrade Phoenix hosted on webapp from 4.5.0 to 5.6.0
2. Load UI on port 6006
3. Wait until the error screen appears

**Expected behavior**
Same behaviour as in the Dev environment webapp (wich should be an exact replica of the Preprod environment), after restart of the webapp, the Phoenix UI works as expected.

**Screenshots**
![image](https://github.com/user-attachments/assets/92514eda-7f13-4585-910f-279a48e3910d)

**Environment (please complete the following information):**
 - OS: Linux container running as Azure webapp
 - Browser Chrome
 - Version 5.6.0

**Additional context**
Pulled Phoenix image **arizephoenix/phoenix:version-5.6.0-nonroot**
Seems same as https://github.com/Arize-ai/phoenix/issues/4091

**Comment by axiomofjoy** [comment]
hey @PacoFarina, we had another team run into this issue with app service. they were able to resolve by scaling down all instances of their app service's vms and scaling back up again. can you give that a try and let us know how it goes?

**Comment by PacoFarina** [comment]
Hi @axiomofjoy , for now we were able to get Phoenix working in two different environments by moving to version 5.2.0. If the error reappears in this version I will try your workaround and let you know .

**Comment by axiomofjoy** [comment]
Thanks @PacoFarina, feel free to re-open the issue if it persists.
