### ISSUE TITLE
[ENHANCEMENT] isolated instrumentation

### ISSUE THREAD

**Issue by armoucar-neon** [Arize-ai/phoenix#5293]
**Is your feature request related to a problem? Please describe.**
My LlamaIndex app currently have a legacy endpoint which uses their old Query Pipeline abstraction and a new one which utilizes Workflows.

Both are instrumented with otel/phoenix

But I want to deprecate the Query Pipeline one and also remove their traces/spans from being sent to phoenix.

**Describe the solution you'd like**
Be able to do isolated instrumentation for different modules in my app.

**Comment by axiomofjoy** [comment]
Hi @armoucar-neon, you should be able to accomplish this by using `suppress_tracing`. Please see the docs [here](https://docs.arize.com/phoenix/tracing/how-to-tracing/setup-tracing/setup-tracing-python#pause-tracing-using-context-manager) for an example.
