### ISSUE TITLE
[ENHANCEMENT] In-product documentation on how Euclidean distance over time is being computed (with illustrations)

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#533]
**Is your feature request related to a problem? Please describe.**
New users have questions around how Euclidean distance over time is being computed. They struggle to understand the embeddings tab without this information.

**Describe the solution you'd like**
Concise in-product documentation on how Euclidean distance over time is being computed with illustrations.

**Describe alternatives you've considered**
Also need better documentation in our actual docs, I think we're working on that.

See usability studies with Etienne Deguine and Erick Siavichay.

**Comment by mikeldking** [comment]
This is technically done for now in the tooltip. For visual documentation I need a design resource so am going to punt for now.
