### ISSUE TITLE
[BUG] ☂️ Login issues with root path and SSO

### ISSUE THREAD

**Issue by stdweird** [Arize-ai/phoenix#5362]
**Describe the bug**
Trying a setup with phoenix 5.8.0 from container. 
Configuration has `PHOENIX_HOST_ROOT_PATH=/test` set, authentication and SSO is configured to be used and the whole setup is behind a proxy (`https://my.host/test` redirects to the container).

3 things go wrong:
1. navigating to `https://my.host/test` ends up trying to access `https://my.host/login?returnUrl=%2Ftest`; which can't work. manually adding the root path `https://my.host/test/login?returnUrl=%2Ftest` does bring me to the login page. the root path does work (i see in the logs that urls are being fetched; i presume some fallback code in case of unauthenticated access is missing the root path). the SSO login button has same issue: it tries to go to `https://my.host/oauth2/...` instead of `https://my.host/test/oauth2/...`. (Also the "return home" button in case of failure with SSO does not use the root path, it goes back to `https://my.host` instead of `https://my.host/test`)
2. i cannot use the `admin@localhost / admin` credentials to login using the username/password. is that due to the SSO setup? not really clear form the docs if this should always work or not. i have not tried a setup without the SSO bits.
3. the login screen has no scrollbar, see screenshot. i need to zoom out to see the SSO button. also, with SSO enabled, it might make more sense to put the SSO login first, and the username/password as second option (or have separate  url for username/password  login; this will only confuse people imho). 
![phoenix_login_screen](https://github.com/user-attachments/assets/350b37a1-6082-4d40-b46a-00b8c5f6db70)

**To Reproduce**

**Expected behavior**
Fallback to working login page in case first access to the site. Being able to login with admin credentials, aside from any SSO authentication.

**Screenshots**
Is attached for the missing scrollbar issue

**Environment (please complete the following information):**
Tested on fedora, with firefox browser.

**Additional context**

- [x] #5365
- [ ] #5367
- [x] #5368
- [x] #5376
- [ ] #5377
- [ ] #5378
- [ ] #4750

**Comment by axiomofjoy** [comment]
- [ ] allow login form scroll

**Comment by axiomofjoy** [comment]
these issues are resolved in `arize-phoenix 5.9.1`
