### ISSUE TITLE
[playground][instrumentation] strip out internal graphql / playground param from input.value in playground spans

### ISSUE THREAD

**Issue by Parker-Stafford** [Arize-ai/phoenix#5393]

**Comment by axiomofjoy** [comment]
Let's pair up on this ticket @Parker-Stafford, not sure which values you have in mind to remove.

**Comment by axiomofjoy** [comment]
I usually think of the `input.value` attribute as containing implementation-specific details of the API used to invoke the LLM, whether that is a client method in the case of our auto-instrumentors or a GraphQL API in the case of our chat completion subscriptions/ mutations. One benefit of leaving the input untouched (minus API key) in this case is that someone could copy the input value and use it to manually re-invoke the subscription, e.g., via GraphiQL or programmatically.

**Comment by axiomofjoy** [comment]
sg, going to close out this issue out for now
