### ISSUE TITLE
[playground][BUG][anthropic] system prompt is ignored

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#5407]
to reproduce, use [this example](https://github.com/anthropics/anthropic-cookbook/blob/main/tool_use/tool_choice.ipynb)

https://github.com/user-attachments/assets/c6af9ce7-32ec-4d85-8119-b1e0858fa576

**Comment by RogerHYang** [comment]
punt for after release

**Comment by Parker-Stafford** [comment]
Right now there are a couple of issues to investigate / solve:

- [ ] make sure the system message from playground is correctly passed in as an invocation parameter for anthropic
- [ ] for playground spans set system message as an invocation parameter under the same name as it is set in openinference and not in input messages (to avoid potential duplication when coming from span to playground)
- [ ] update span parsing logic to attempt to pull system invocation param into a message when going from span to playground

**Comment by RogerHYang** [comment]
@Parker-Stafford It looks like the necessary backend components are already in place. I can take a stab at the frontend logic
