### ISSUE TITLE
[playground][ENHANCEMENT][ui][azure] remember the deployment name

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#5413]
it can remember the endpoint but not the deployment name

https://github.com/user-attachments/assets/9d470af1-dd63-4e7e-84be-26816204c4b0

**Comment by Parker-Stafford** [comment]
ahh yeah we have to clear deployment because it uses the model name field, which we clear on provider update. I think I have an idea for this but in theory, this can also be avoided with the saveConfig button

**Comment by Parker-Stafford** [comment]
The fact that the endpoint was not being clear made this more confusing. Now all azure fields will clear when switching off and back (unless saved) the functionality desired in this enhancement can be achieved by saving the config for Azure so going to close for now.  cc @RogerHYang
