### ISSUE TITLE
[BUG]Unable to Parse Results Using llama3.1-70b-instruct Model in Evaluation

### ISSUE THREAD

**Issue by alexChiu127** [Arize-ai/phoenix#5430]
I tried the eval quick start, https://docs.arize.com/phoenix/evaluation/evals, 

but I used our company's self-hosted llama3.1-70b-instruct model. I ran the following code to get the evaluation results for 10 sample data points. You can see that many entries in the `hallucination_eval` and `qa_eval` columns are "NOT_PARSABLE". I would like to ask if this is because llama3.1 cannot parse the results, or should I not use the `OpenAIModel` object?

**here is my notebook code:**

```
import nest_asyncio

from phoenix.evals import HallucinationEvaluator, OpenAIModel, QAEvaluator, run_evals

nest_asyncio.apply()  # This is needed for concurrency in notebook environments


MODEL = "llama3.1-70b-instruct"
API_KEY = "SkJblk8gWx1CpVSvXUkbFzP3hs"
API_BASE = f"https://mycompany.inc/llm/v3/models/{MODEL}"
  
eval_model = OpenAIModel(
    api_key=API_KEY,
    base_url=API_BASE,
    model_kwargs={
        "extra_headers": {
            "x-user-id": "user123"
        }
    }
)


# Define your evaluators
hallucination_evaluator = HallucinationEvaluator(eval_model)
qa_evaluator = QAEvaluator(eval_model)

# We have to make some minor changes to our dataframe to use the column names expected by our evaluators
# for `hallucination_evaluator` the input df needs to have columns 'output', 'input', 'context'
# for `qa_evaluator` the input df needs to have columns 'output', 'input', 'reference'
df["context"] = df["reference"]
df.rename(columns={"query": "input", "response": "output"}, inplace=True)
assert all(column in df.columns for column in ["output", "input", "context", "reference"])

# Run the evaluators, each evaluator will return a dataframe with evaluation results
# We upload the evaluation results to Phoenix in the next step
hallucination_eval_df, qa_eval_df = run_evals(
    dataframe=df, evaluators=[hallucination_evaluator, qa_evaluator], provide_explanation=True
)


results_df = df.copy()
results_df["hallucination_eval"] = hallucination_eval_df["label"]
results_df["hallucination_explanation"] = hallucination_eval_df["explanation"]
results_df["qa_eval"] = qa_eval_df["label"]
results_df["qa_explanation"] = qa_eval_df["explanation"]
results_df.head()
```

Result:
![image](https://github.com/user-attachments/assets/efc73c88-20fc-4e39-8453-697a7cc5c87e)

**Comment by axiomofjoy** [comment]
Thanks @alexChiu127. What API or service are you using for self-hosting the model?

**Comment by alexChiu127** [comment]
Hi,

I'm not sure if my answer is accurate, but our company should be using HuggingFace-style APIs.

If you need more precise information, please let me know.

**Comment by alexChiu127** [comment]
v0.15.1, thanks.

**Comment by alexChiu127** [comment]
I tried to upgrade it to latest version, but the result is still "Not_Parsable".

**Comment by axiomofjoy** [comment]
hey @alexChiu127, there are a few reasons this might be happening

- model might not support json
- model might have a low max tokens set, which leads to invalid output

if you set `provide_explanation`, i expected to see the unparsed output in the explanation column for each eval. it seems like that's not what you're seeing, though, is that correct?

**Comment by alexChiu127** [comment]
Yes, I did set provide_explanation, but all the results I see are None. Function calling is supported, so maybe I’ll try adjusting the max tokens?

**Comment by axiomofjoy** [comment]
You certainly can try upping max tokens to see if it helps. I think the fact that explanations is not showing up is a separate bug we'll need to bottom out.

Can you also try running `llm_classify` with the `include_response` parameter set to true? This will include the raw response row in the dataframe so we can get a better sense of what is preventing parsing from working. It should be relatively straightforward to adapt [this notebook](https://github.com/Arize-ai/phoenix/blob/main/tutorials/evals/evaluate_hallucination_classifications.ipynb) to use your Llama 3 model and add `include_response=True`.

**Comment by alexChiu127** [comment]
1. I adjusted the max token to 1024, 2048, and 4096, but it seems to still result in the same outcome (Not_Parsable, None).

2. Below is my attempt to use llm_classify with the include_response parameter set to true. However, from the results(I tried HALLUCINATION for the same sample data of quick start), it seems like everything is being parsed correctly? 
Here is the screenshot:  
![image](https://github.com/user-attachments/assets/bd8dab2a-3dd0-4932-9dd8-3fbc354bb340)
![image](https://github.com/user-attachments/assets/345ef100-7898-4c26-813f-a4b160162015)

**Comment by alexChiu127** [comment]
Ok, I see the response format is different when I switch model to gpt-4o, may be it causes the issue?

![image](https://github.com/user-attachments/assets/163be4b9-64c6-48c1-a995-e90fd350218b)

**Comment by axiomofjoy** [comment]
> 1. I adjusted the max token to 1024, 2048, and 4096, but it seems to still result in the same outcome (Not_Parsable, None).
> 2. Below is my attempt to use llm_classify with the include_response parameter set to true. However, from the results(I tried HALLUCINATION for the same sample data of quick start), it seems like everything is being parsed correctly?
>    Here is the screenshot:
>    ![image](https://private-user-images.githubusercontent.com/28252925/388765676-bd8dab2a-3dd0-4932-9dd8-3fbc354bb340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDQ1NTQsIm5iZiI6MTczMjI0NDI1NCwicGF0aCI6Ii8yODI1MjkyNS8zODg3NjU2NzYtYmQ4ZGFiMmEtM2RkMC00OTMyLTlkZDgtM2ZiYzM1NGJiMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAyNTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NWFiYzVhYjBhNjIyZDAyZTdmMTkxYWYxNWE0MjAxODQxYThmYTNjY2IzYjYzM2MyZTgwZTM5NzAwODQ0NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7PAh4RVjfkN0L_O7aoZUcFetWJN55cnPISLdalI8MaE)
>    ![image](https://private-user-images.githubusercontent.com/28252925/388765846-345ef100-7898-4c26-813f-a4b160162015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDQ1NTQsIm5iZiI6MTczMjI0NDI1NCwicGF0aCI6Ii8yODI1MjkyNS8zODg3NjU4NDYtMzQ1ZWYxMDAtNzg5OC00YzI2LTgxM2YtYTRiMTYwMTYyMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAyNTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZTNmNWZjYWI5Y2ExODkxMDlkODJjZjhkYWNhYWZhNGEwNTIyNmM4YmY5MzQ5YzFlNWNmNmZiYjg4NzE3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uy7nb6mEdC7rk5I6vh2wjd5mdKaAWpJ43e2KNI-_SrY)

Can you also set `provide_explanation` to true?

**Comment by alexChiu127** [comment]
Yes, I can. 
When set provide_explanation to true, the result is different for llama 3,  all data in explanation column is "None", and the data in response column is different too.

The max token is set to default: 256, llama 3
![image](https://github.com/user-attachments/assets/8bba3413-9637-466a-ab4a-7e88b6e97408)

The max token is set to : 4096, llama 3
![image](https://github.com/user-attachments/assets/610b625e-2d49-4330-a746-4b22f999a690)

The max token is set to default: 256, gpt4-o, works great
![image](https://github.com/user-attachments/assets/92282454-72e2-4ef9-b049-b04a319ba460)

**Comment by alexChiu127** [comment]
Hi,
It seems possible that the function calling format of our llama3 model is inconsistent with the format required by phoenix.eval, which is why the results cannot be parsed. When I do not use function calling, the correct results appear. 

![image](https://github.com/user-attachments/assets/ff161737-c747-4484-93db-22f7cb7ffc56)
![image](https://github.com/user-attachments/assets/cfaec98c-deee-468c-9935-3940b0873ded)


I would like to ask, what are the disadvantages of not using function calling? For example, could it be due to non-fixed JSON leading to parsing issues?

**Comment by axiomofjoy** [comment]
Hey @alexChiu127, glad you resolved the issue. In this case, not using function-calling is the appropriate thing to do since it seems the API you are using does not conform to the OpenAI APi format. There's no downside to not using function calling if it is working for you. We default to use function calling since it helps ensure valid output.

Going to close this issue out since the API is not compliant with OpenAI. We'll open up separate tickets to address some of the bugs related to `provide_explanation`.

**Comment by axiomofjoy** [comment]
Actually, out of curiosity, does setting `provide_explanation` to true without function calling result in the full explanation appearing in the dataframe?

**Comment by alexChiu127** [comment]
Yes, I still can get the full explanation.
