### ISSUE TITLE
[playground][ENHANCEMENT][ui] users should be notified upfront about missing model parameters that are required so they don't get confused by errors

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#5431]
As users switch between providers, some model parameters may be left blank unwittingly.

Some examples:

### Azure OpenAI
- api version

### Anthropic
- max tokens

**Comment by cephalization** [comment]
This requires us to fetch invocation parameter definitions at the top level of each instance, such the the definitions are available for the rest of the playground instance components to use.

Of note:
- We would like to warn when all required invocation parameter definitions are not provided in the instance config form
- Unsupported invocation parameters should be stripped before sending to gql client
- _extra credit_ tool defs and tool messages should be dropped when moving from a provider that supports tools to one that does not
