### ISSUE TITLE
[ENHANCEMENT] Read first admin password from env variable

### ISSUE THREAD

**Issue by stdweird** [Arize-ai/phoenix#5449]
**Is your feature request related to a problem? Please describe.**
On initial setup, a very weak default password is set (and hardocded). On first login, you are supposed to change it.
It might be better that one can pass some random string via an environment variable and then this is the first password.
Wheter or not this password must be changed again on first login is up for debate. Ideally this is not needed; one can assume that the environment variable will contain a much stronger password, so this is not needed. It is not needed that upon change of the environment value, the admin password in the database is also modified. You can make this more clear by naming the variable as such, e.g. `PHOENIX_ADMIN_INITIAL_PASSWORD` or something.

**Describe the solution you'd like**
Default setup is not safe.

**Describe alternatives you've considered**

**Additional context**

**Comment by RogerHYang** [comment]
Thank you for the suggestion!

arize-phoenix 5.11.0 now has  `PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD`
