### ISSUE TITLE
[playground][ui] dataset example lines wrap mid-word

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#5483]
![Screenshot 2024-11-20 at 10 41 30 PM](https://github.com/user-attachments/assets/89292979-afd4-4164-aa9d-490f438e8133)

**Comment by Parker-Stafford** [comment]
@axiomofjoy whats the desired behavior here? Wrap but not mid word? i think this was added to help with super big json not wrapping, correct cc @cephalization

**Comment by cephalization** [comment]
> @axiomofjoy whats the desired behavior here? Wrap but not mid word? i think this was added to help with super big json not wrapping, correct cc @cephalization 

Correct. We either break mid word to support extremely long contiguous strings, or we add horizontal scroll to each individual cell

**Comment by axiomofjoy** [comment]
I see. The horizontal scroll would be tough because the table already needs to horizontally scroll. Makes sense to punt or close if there's not a clearly better way.

**Comment by axiomofjoy** [comment]
Closing for now
