### ISSUE TITLE
[BUG] Prompts containing Images with data URLs are not displayed in the UI

### ISSUE THREAD

**Issue by stefanadelbert** [Arize-ai/phoenix#5564]
**Describe the bug**
When prompting a multi-modal model (e.g. Gemini Pro using `langchain`) using a prompt which contains an image expressed with a data URL (see below) results in a captured trace in Arize Phoenix with a broken image.

```
"kwargs": {
          "content": [
            {
              "type": "text",
              "text": "What is shown in this image?"
            },
            {
              "type": "image_url",
              "image_url": {
                "url": "data:image/jpeg;base64,/9j/4AAQSkZJ..."
              }
            }
          ]
}
```

When inspecting the image element in the UI, I can see that it's actually an SVG (see screenshot below). I've looked at the code and I can see that there is logic there to check if the image is redacted (`url == "__REDACTED__"`) and draw the image placeholder (see `SpanImage.tsx`).

**To Reproduce**
Steps to reproduce the behaviour:
1. Prompt a multi-modal modal, like Gemini Pro, with langchain (see [here](https://python.langchain.com/docs/integrations/llms/google_vertex_ai_palm/#multimodality) for an example) where the image is a data URL.

**Expected behaviour**
The image should be shown in the Phoenix trace.

**Screenshots**

![image](https://github.com/user-attachments/assets/8a81ad75-7a69-48d0-87cb-13ddd0dfe0d9)
![image](https://github.com/user-attachments/assets/a8e3b89c-7ceb-4cf3-8c49-8efd9e58d1ee)
![image](https://github.com/user-attachments/assets/1c25483d-5b2e-4b41-bfea-2e59157d7371)

**Environment (please complete the following information):**
 - OS: Linux (Arch)
 - Browser Firefox, Chromium, Brave
 - Version 5.12.0 (arizephoenix/phoenix@sha256:02be73e6fa5e3d9b9ddb8e17f8767ef914a2165a163cb78f113d6f3eafbde54c)

**Comment by RogerHYang** [comment]
H @stefanadelbert you can add a config parameter to `.instrument(...)` as shown [here](https://github.com/Arize-ai/openinference/blob/036c86a532f057ddad780fb590e0a1b9c4bc09e8/python/instrumentation/openinference-instrumentation-vertexai/examples/image_upload.py#L21) and specify a higher value. The [default value](https://github.com/Arize-ai/openinference/blob/036c86a532f057ddad780fb590e0a1b9c4bc09e8/spec/configuration.md?plain=1#L19) is 32000, so image is larger than that (in terms of characters when base64 encoded)

**Comment by stefanadelbert** [comment]
So easy, when you know how! I did suspect it was somewhere pre-OTEL.

Thank you, @RogerHYang.

**Comment by stefanadelbert** [comment]
I confirm that this works excellently.

```python
tracer_provider = register(
  endpoint="http://localhost:4317",
)
config = TraceConfig(
    base64_image_max_length=32000*10
)
LangChainInstrumentor().instrument(tracer_provider=tracer_provider, config=config)
```

Thank you, @RogerHYang.
