### ISSUE TITLE
[BUG]: Multiple tiemout errors but only one method supports timeout config

### ISSUE THREAD

**Issue by joshuamoreno1** [Arize-ai/phoenix#5633]
**Describe the bug**

Hi there,

I'm having many timeout errors with 2 methods from your library and these methods does not support a way to increase it:

```
 INFO - [base]     with map_exceptions(exc_map):
 INFO - [base]   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
 INFO - [base]     self.gen.throw(value)
 INFO - [base]   File "/opt/pysetup/app/evaluations/.venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
INFO - [base]     raise to_exc(exc) from exc
INFO - [base] httpcore.ReadTimeout: timed out
INFO - [base] The above exception was the direct cause of the following exception:
```

Checking the documentation you only supports to increase the timeout in [query_spans](https://arize-phoenix.readthedocs.io/en/latest/api/client.html#session.client.Client.query_spans) method, but I need the same in these methods:

- [client.log_evaluations](https://arize-phoenix.readthedocs.io/en/latest/api/client.html#session.client.Client.log_evaluations)
- [client.get_evaluations ](https://arize-phoenix.readthedocs.io/en/latest/api/client.html#session.client.Client.get_evaluations)

Could you help me? I need these feature asap, not just in one method.

I'm using the 5.8.0 version

Thanks,

Regards,

**Comment by mikeldking** [comment]
Hey @joshuamoreno1 - sorry you are hitting timeouts. I'm guessing this might be related to the fact that the payloads are too big, there should be ways to narrow down the payload sizes via params - hopefully this unblocks you for now.

We'll take a look on Monday when the office is open on our end.

PRs are also welcome if you have bandwidth. 

Thanks for bringing this to our attention.

**Comment by joshuamoreno1** [comment]
Thank you!!
