### ISSUE TITLE
[BUG] Phoenix Evals `evaluate_tools_calling.ipynb` Demo Doesn't work.

### ISSUE THREAD

**Issue by hdotking** [Arize-ai/phoenix#5650]
**Describe the bug**
[The evaluate_tools_calling.ipynb notebook](https://github.com/Arize-ai/phoenix/blob/main/tutorials/evals/evaluate_tool_calling.ipynb) in the Phoenix Evals demo fails to execute due to a missing template variable error. Specifically, the error message reads:
Retries exhausted after 1 attempts: Missing template variable: '\n "name"'.

**To Reproduce**
1. Clone the Phoenix Evals repository.
2. Open the evaluate_tools_calling.ipynb notebook in a Jupyter or Colab environment.
3. Execute the cells sequentially until the error occurs.
4. Observe the error in the cell executing the llm_classify function.

**Expected behavior**
The notebook should execute successfully, with the llm_classify function processing inputs without errors. It should provide a classification output for the evaluated tools.

**Screenshots**
![Screenshot 2024-12-08 at 16 16 20](https://github.com/user-attachments/assets/43259976-ea84-4f37-925e-dc43c1350599)

**Environment (please complete the following information):**
 - OS: MacOS M1 : Sonoma 14.3
 - Notebook Runtime:  Jupyter Notebook on VSCode as well as Google Colab
 - Browser: Chrome
 - Version = "6.1.0"

**Additional context**
The error appears to stem from a missing name variable in the template used by the llm_classify function. Upon reviewing the default_templates.py file, no name placeholder is found, suggesting a mismatch between the function’s expectations and the template definitions.

**Comment by hdotking** [comment]
## UPDATE & FURTHER CONTEXT

I fixed an error in the json shown below but still get the same problem. (Added a missing `."` to the end of the description field below ).

```
                "discount_code": {
                    "type": "string",
                    "description": "The discount code to apply
                }
```


```
                "discount_code": {
                    "type": "string",
                    "description": "The discount code to apply."
                }
```

The new output looks like this. (Notice the warnings have been replaced by a few empty lines)

```
llm_classify |          | 0/26 (0.0%) | ⏳ 00:27<? | ?it/s

                                                       
                                                       
                                                       
                                                       
                                                       
                                                       

                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
                                                       
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
Retries exhausted after 1 attempts: Missing template variable: '\n        "name"'
```

Printing the `response_classifications` variable shows the following. 

<img width="1026" alt="Screenshot 2024-12-08 at 16 49 05" src="https://github.com/user-attachments/assets/8b00b811-95f9-44f5-891b-b95c8ee4ae4c">

**Comment by mikeldking** [comment]
Thanks for the report @hdotking - We'll take a look. Hopefully an easy fix on our end.

**Comment by mikeldking** [comment]
Should be resolved in https://github.com/Arize-ai/phoenix/pull/5675

Let us know if you face any more issues!
