### ISSUE TITLE
Querying Annotations in Phoenix with SpanQuery

### ISSUE THREAD

**Issue by alexChiu127** [Arize-ai/phoenix#5652]
Hi Team,

I would like to know how to use SpanQuery to query the "Hallucination" and "QA Correctness" data that has been recorded in Phoenix. As far as I know, these metrics should be in the annotations field of the root span.

Here are the queries statement I have tried. Other fields can be retrieved, but the annotations-related fields are not coming out (they are None).

**1.**
query = SpanQuery().where(
    "annotations['Hallucination'].label is not None",
).select(
    name="name", trace_id = "trace_id", span_kind = "span_kind", status_code="status_code",
    token="attributes.llm.token_count.total",
    **Hallucination="annotations"** , openinference = "openinference"
)

px_client.query_spans(query, start_time=start, end_time=end, project_name = project_name)

**2.**
query = SpanQuery().where(
    "annotations['Hallucination'].label is not None",
).select(
    name="name", trace_id = "trace_id", span_kind = "span_kind", status_code="status_code",
    token="attributes.llm.token_count.total",
    **Hallucination="annotations.Hallucination.label"** , openinference = "openinference"
)

px_client.query_spans(query, start_time=start, end_time=end, project_name = project_name)

**Two of above Result are the same(None):**
![image](https://github.com/user-attachments/assets/24117fc4-1af4-4a16-b081-d0bc3f24168a)

**I believe these metrics are in the Annotations, but I can't query them out.**
![image](https://github.com/user-attachments/assets/5006ff56-9833-44c8-b278-77e46e87f909)

**Comment by axiomofjoy** [comment]
Hey @alexChiu127, can you take a look at the documentation [here](https://docs.arize.com/phoenix/tracing/how-to-tracing/extract-data-from-spans#how-to-apply-filters) and let us know if you have further questions?

Closing this issue out since it does not describe a bug, but feel free to follow up in the thread with further questions or feedback.

**Comment by axiomofjoy** [comment]
Thanks for the clarification @alexChiu127. We don't currently support selecting evals as part of the `select` statement. You can get the span dataframe and eval dataframe perform the join in `pandas`. Code snippet below.

```
phoenix_client = px.Client()
spans_df = phoenix_client.get_spans_dataframe()
span_evals = phoenix_client.get_evaluations()
hallucination_evals = [span_eval for span_eval in span_evals if span_eval.eval_name == "Hallucination"]
assert len(hallucination_evals) == 1
hallucination_eval = hallucination_evals[0]
evals_df = hallucination_eval.dataframe
joined_df = spans_df.join(evals_df.rename(columns={
    'label': 'hallucination_label',
    'score': 'hallucination_score', 
    'explanation': 'hallucination_explanation'
}), how='inner')
print(joined_df)
```

Hope this helps!

**Comment by alexChiu127** [comment]
Thank you, 
but one quesiton, it seems that span_evals = phoenix_client.get_evaluations() only accepts the project parameter and does not allow filtering by time. As the number of evaluation records grows, will this result in slower retrieval of evaluation data?

**Comment by axiomofjoy** [comment]
Hey @alexChiu127, it should be possible to specify a time range. https://docs.arize.com/phoenix/tracing/how-to-tracing/extract-data-from-spans#how-to-specify-a-time-range
