### ISSUE TITLE
[BUG] Failed to export batch code: 204

### ISSUE THREAD

**Issue by philmui** [Arize-ai/phoenix#5653]
**Describe the bug**
A plain vanilla configuration generates the error below:

```
 2024-12-08 21:32:06,447 - opentelemetry.exporter.otlp.proto.http.trace_exporter - ERROR - Failed to export batch code: 204, reason: 
```

**To Reproduce**
1.  Python project dependencies:

```
openinference-instrumentation             0.1.19
openinference-instrumentation-llama-index 3.0.4
openinference-semantic-conventions        0.1.12
opentelemetry-api                         1.28.2 
opentelemetry-exporter-otlp               1.15.0 
opentelemetry-exporter-otlp-proto-grpc    1.15.0 
opentelemetry-exporter-otlp-proto-http    1.15.0 
opentelemetry-instrumentation             0.49b2
opentelemetry-proto                       1.15.0 
opentelemetry-sdk                         1.28.2 
opentelemetry-semantic-conventions        0.49b2 
```

2. Register a LlamaIndex tracer this way:

```            
tracer_provider = register(
    project_name="AmazingProject",
    endpoint=os.environ.get('PHOENIX_ENDPOINT', ""),
    headers={"api_key": os.environ.get('PHOENIX_API_KEY', "")},
    batch=True,
    verbose=True
)
            
LlamaIndexInstrumentor().instrument(
   tracer_provider=tracer_provider
)
```

**Expected behavior**
Do not expect to see any error from the opentelemetry package

**Screenshots**
See the exact standard out log
![Screenshot 2024-12-08 at 9 36 43 PM](https://github.com/user-attachments/assets/cb38877f-dc21-4b23-ace9-ae119d43f1b0)

**Environment (please complete the following information):**
 - OS: Mac OS (14.7.1 (23H222))
 - Runtime: Python 3.12.7

**Additional context**
 - Searched the web and found similar reporting but no resolution

**Comment by RogerHYang** [comment]
Can you try upgrading `opentelemetry-exporter-otlp` to >=1.23? Older versions do [not accept 204](https://github.com/open-telemetry/opentelemetry-python/pull/3623/files#diff-02d42a395e9e885110671b8db800ff93623e12220bababc32e60f58153168accL149) even though it's a successful response.

**Comment by philmui** [comment]
This is it.  Thanks @RogerHYang : I upgraded to >= 1.27 and seems to work -- but not 1.28 (which has breaking dependencies)
