### ISSUE TITLE
[docs] Add a why phoenix section

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5658]
Describe open standards, open source, etc.

**Comment by Jgilhuly** [comment]
@mikeldking - text of the first round here, let me know what you think: https://docs.google.com/document/d/1C0jvlmAgj3GuLHJSicMCc7P-8G4pW0qseTR6gqdeoIA/edit?usp=sharing

**Comment by mikeldking** [comment]
markin as done https://phoenix.arize.com/why/
