### ISSUE TITLE
[docs] add notebook links for sessions

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5689]
# Python

https://github.com/Arize-ai/phoenix/blob/main/tutorials/tracing/openai_sessions_tutorial.ipynb
https://github.com/Arize-ai/phoenix/blob/main/tutorials/tracing/project_sessions_llama_index_query_engine.ipynb

# TypeScript

https://github.com/Arize-ai/phoenix/blob/main/js/examples/notebooks/tracing_openai_sessions_tutorial.ipynb

**Comment by Jgilhuly** [comment]
Added these to [example](https://docs.arize.com/phoenix/notebooks) and [sessions](https://docs.arize.com/phoenix/tracing/how-to-tracing/setup-sessions) docs pages
