### ISSUE TITLE
[BUG] Sessions: Something went wrong 

### ISSUE THREAD

**Issue by MarouaneZhani** [Arize-ai/phoenix#5750]
**Describe the bug**
When something is going wrong and the AI had no output (an error was thrown, timeout...) the sessions cannot be accessed at all, and nothing is helping... 
the only thing to have back the possibility to check the session is if we delete all traces... 
In my point of view this is really critical and all sessions are just lost, and can no longer be accessed. 
**To Reproduce**
1. Start tracing using a session
2. Make sure to have an error in between (e.g. exceeding the timeout of the AI 
3. Try to access the sessions

**Expected behavior**
Possibility to see always the sessions. 
Don't lose old sessions!! 
**Screenshots**
![Screenshot 2024-12-17 144136](https://github.com/user-attachments/assets/1d720338-513f-4634-b346-255f82d1c987)

Version: 
Phoenix 7.1.0

**Comment by MarouaneZhani** [comment]
Now I can't access all the projects 

![image](https://github.com/user-attachments/assets/5e6dd288-3354-4762-9bb9-6e361cb88139)

**Comment by RogerHYang** [comment]
Thanks for the report. I think this is just a UI-level issue and I'll work on a fix.

**Comment by RogerHYang** [comment]
@MarouaneZhani We fixed the error in arize-phoenix 7.2.0. Please give it a try and let us know if you have further questions. Thanks!
