### ISSUE TITLE
Calling_llm_by_api

### ISSUE THREAD

**Issue by vishnu020** [Arize-ai/phoenix#5772]
"I have a service that I am using. I have the API endpoint, and I am hitting the LLM via the API to get responses and context related to the queries. However, I want to view the traces and spans, but I am encountering an error when trying to view the spans.

I am sharing the error screenshots below:"
<img width="858" alt="image" src="https://github.com/user-attachments/assets/e2759900-fc75-463e-9b15-5247397b8604" />

Below image is about traces i am able to see:
<img width="768" alt="image" src="https://github.com/user-attachments/assets/e8fc7a5d-ce1f-4051-a524-1c5dc62b3731" />

**Comment by axiomofjoy** [comment]
Thanks @vishnu020 for reporting this issue. It appears to be an issue with the Arize SaaS platform, which is a separate project from Phoenix. I have reported this issue to the team and am closing the issue in the Phoenix repo. If the issue persists, please join the [Arize AI Slack community](https://join.slack.com/t/arize-ai/shared_invite/zt-2wky2dr03-T23s_WGNewLoRnbl4JXYrg) and reach out to the team in the #arize-platform-support channel.
