### ISSUE TITLE
[BUG] Drift score is reversed

### ISSUE THREAD

**Issue by fjcasti1** [Arize-ai/phoenix#582]
**Describe the bug**
Drift scores should be positive when there's more baseline than primary points. Negative otherwise. This reflects the negative impact of having a model acting on regions of the space it has not been trained on.

**To Reproduce**
1. Run our Image Classification tutorial
2. Go to the embeddings page
3. See clusters sorting, blurry images appear on top (correct) but the drift is positive, it should be negative

**Expected behavior**
Situations, where there are more primary points than baseline, should yield negative values of drift, positive otherwise

**Screenshots**
![Screenshot 2023-04-12 at 9 49 18 AM](https://user-images.githubusercontent.com/39070172/231527672-9e6e614c-404a-46a9-bf6f-e5dfa84ea456.png)
![Screenshot 2023-04-12 at 9 49 08 AM](https://user-images.githubusercontent.com/39070172/231527690-21effa99-d570-4b16-9f50-e5641a6f31e3.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Jupyter
 - Browser: Chrome
 - Version: 0.0.11

**Additional context**
None

**Comment by mikeldking** [comment]
While this is inconsistent with Arize I think the way in which it was implemented assumed higher means more drift. Ultimately this metric may shift in meaning as it causes a fair amount of confusing. Closing for now as it's working as designed
