### ISSUE TITLE
[BUG][playground] OpenAI API key should not be required when only using AzureOpenAI (when API Key is set via environment variable)

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/phoenix#5822]
`super().__init__` in the Azure client [here](https://github.com/Arize-ai/phoenix/blob/783b66f9b98e48e0b670ce55ffe13598b3fd5728/src/phoenix/server/api/helpers/playground_clients.py#L582) goes to the OpenAI parent class and then fails [here](https://github.com/Arize-ai/phoenix/blob/783b66f9b98e48e0b670ce55ffe13598b3fd5728/src/phoenix/server/api/helpers/playground_clients.py#L268) when OpenAI API key is not available.

**Comment by mikeldking** [comment]
Marking as high since it precludes people from using azure only
