### ISSUE TITLE
[ENHANCEMENT] support ISO formatted strings in timestamp column

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#592]
**Is your feature request related to a problem? Please describe.**
Some users have shown they use ISO-formatted strings as their primary way to represent timestamps.

**Describe the solution you'd like**
Support ISO-formatted strings in timestamp column.

**Describe alternatives you've considered**
We could not support and require the user to convert to pandas datatime.

**Comment by pbadhe** [comment]
Hi @axiomofjoy,
I am trying to understand this and have a few queries. 
1. Are both types, ISO-formatted dateTime and pandas dateTime needed to be supported?
2. Which classes and tests can I debug for implementing this? Any examples or leads on what class (like schema) might require change would be appreciated.
Thanks.

**Comment by axiomofjoy** [comment]
Hey @pbadhe 👋 Thanks for checking out Phoenix, we're excited to have you as part of the community!

> 1. Are both types, ISO-formatted dateTime and pandas dateTime needed to be supported?

This ticket refers to adding support for ISO-formatted *strings*. We already support `pandas.Timestamp` columns and columns of `datetime.datetime` entries.

- This is the format we want to support: [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601). Here's an example string.

```python
import datetime
datetime.datetime.utcnow().isoformat()
>>> 2020-03-20T01:30:08.180856
```

- At a high-level, I think we want to check if the input timestamp column is a column of strings. If it is, we want to convert the column to `pandas.Datetime`.
  - We need to cover two cases, one case where the timestamp string is timezone-aware and the other where the timestamp string is timezone-naive. If the timestamp is timezone-naive, we want to convert to timezone-aware (assume UTC). This is needed to prevent downstream issues with comparison of timezone-aware vs. timezone-naive timestamps.

> 2. Which classes and tests can I debug for implementing this? Any examples or leads on what class (like schema) might require change would be appreciated.

- The relevant [code](https://github.com/Arize-ai/phoenix/blob/bf2292c41319d19783934794dc85872db4873cd3/src/phoenix/datasets/dataset.py#L550).
- You can add a few parameterized examples to this [test case](https://github.com/Arize-ai/phoenix/blob/bf2292c41319d19783934794dc85872db4873cd3/tests/datasets/test_dataset.py#L1075).
- We also need to update the [API reference documentation](https://github.com/Arize-ai/phoenix/blob/main/docs/api/dataset-and-schema.md) for the `timestamp_column_name` field to reflect added support for ISO-8601 strings.
