### ISSUE TITLE
[BUG] Cannot parse raw_text_data column on an event

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#616]
**Describe the bug**
follow this notebook: https://colab.research.google.com/drive/1sWztfe8xMIQwQQ_NXHxK3zTskIwE2jzV?usp=sharing

**To Reproduce**
Runtime exception trying to parse the "statement" column

v0.0.15

**Comment by RogerHYang** [comment]
couldn't repro this one. what actions led this error?

**Comment by mikeldking** [comment]
Cannot repro, closing
