### ISSUE TITLE
[BUG] Possible 403 on non-chrome browsers

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#655]
**Describe the bug**
Users are seeing a 403 when attempting to open our Colabs, the image classification notebook in particular. One user has reported this issue on Brave, another user has reported the issue on Safari. For the Safari user, the issue was resolved by signing into GitHub.

**To Reproduce**
Unclear, I haven't been able to reproduce the behavior.

**Expected behavior**
Users should be able to open the notebook without issue.

**Environment (please complete the following information):**
 - OS: Safari user was using Mac
 - Notebook Runtime [e.g. Jupyter, Colab]
 - Browser: Brave, Safari

**Comment by axiomofjoy** [comment]
@nate-mar Can you try to reproduce this issue?

**Comment by mikeldking** [comment]
Need more info, closing for now
