### ISSUE TITLE
[Enhancement] The app does not open on AWS SageMaker Notebooks

### ISSUE THREAD

**Issue by AbhiPawar5** [Arize-ai/phoenix#675]
**Describe the bug**
Hi Team, I am trying to run Phoenix with my datasets on AWS SageMaker Notebook instances. However, it simply says cannot connect to localhost (which makes sense since we are running infra on AWS). I (or the community) would like to know how to run Phoenix on SageMaker notebooks. Thanks.

**To Reproduce**
1. Go to [Phoenix Quickstart](https://github.com/Arize-ai/phoenix)
2. Follow the Quickstart instructions on your train and prod datasets
3. Start a session on AWS SageMaker notebooks
4. See the error : Localhost refused to connect

**Expected behavior**
The Phoenix UI should have been visible in the current notebook window or a new tab

**Screenshots**
NA

**Environment (please complete the following information):**
 - OS: Linux
 - Notebook Runtime : AWS SageMaker Notebook - t3.medium
 - Browser : Google Chrome
 - Version : 112.0

**Comment by mikeldking** [comment]
@AbhiPawar5 thanks for the bug report! We actually haven't tested with SageMaker notebooks but will prioritize this soon. With colab we have support for VM tunneling. We are hoping there is something similar.

**Comment by AbhiPawar5** [comment]
Hi @mikeldking, thanks for your message. I'm excited to try Phoenix soon :)

**Comment by mikeldking** [comment]
SageMaker notebook NAT configuration documentation: https://aws.amazon.com/blogs/machine-learning/understanding-amazon-sagemaker-notebook-instance-networking-configurations-and-advanced-routing-options/

**Comment by mikeldking** [comment]
Removing from sprint board @fjcasti1 - please add an update if you can.

**Comment by mikeldking** [comment]
cc @amyxst
