### ISSUE TITLE
[BUG] dimension values not appearing in color by section, or encountering error and failure to load dimension metadata

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#688]
**Describe the bug**
There are two distinct bugs I am seeing by running the attached notebook.

1. When one dataset has a tag that another does not (the "is_answerable" tag), the tag has unknown values inside the app.

<img width="1422" alt="Screenshot 2023-05-03 at 11 01 56 PM" src="https://user-images.githubusercontent.com/15664869/236128365-c17aae94-2f82-4632-b49b-50a468862e3e.png">

2. When I added the tag to the other dataset by literally adding a boolean column of the same name, I encountered the error below. This might have to do with the fact that the dtypes are different on the "is_answerable" column between the two datasets (bools on one, strings on another).

<img width="1725" alt="Screenshot 2023-05-03 at 11 25 28 PM" src="https://user-images.githubusercontent.com/15664869/236128802-42b9222b-61bf-4304-bc66-5c8b0929ad86.png">

**To Reproduce**
Run the [Colab](https://colab.research.google.com/gist/axiomofjoy/9c235391198ffc069f23d24c5254fad3/squad.ipynb). I've made a comment in the cell to run or not run to reproduce option 1 or 2 above. You might need to tweak the schemas to include/ exclude the "is_answerable" tag.

<img width="776" alt="Screenshot 2023-05-03 at 11 33 55 PM" src="https://user-images.githubusercontent.com/15664869/236127847-b21dc9d8-290e-43a8-b78f-59d737046e07.png">

**Expected behavior**
I expect for tags to appear with the actual values, even if the tag column is only present on one dataframe or in one schema.

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Colab
 - Browser: Chrome
 - Version: 0.0.18

**Comment by mikeldking** [comment]
One possible cause for this is that `categories` on a dimension only pulls from the `primary` dataset - it really needs to be a union of the categories of both datasets so that you can reason about the categories at a model level.
