### ISSUE TITLE
[ENHANCEMENT] support lists for embeddings

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#697]
context: https://github.com/Arize-ai/phoenix/issues/692#issuecomment-1539334467

We should support lists in addition to np.arrays

## Proposed solutions

1. transitively convert lists to np.array
 pro: ease of onboarding con: re-initializing will take time each time
2. reject the datafreame, propose a way to convert the embedding

**Comment by RogerHYang** [comment]
It's taking a _very_ long time computing `np.mean` for lists (which is _not_ surprising). We'll need to convert these to `np.array` upfront, which by itself is not cheap, but allow numpy to make progress on them later on

**Comment by RogerHYang** [comment]
`np.mean` (for euclidean distance) does not work with lists. And when the Series is too long, it hangs.

https://github.com/Arize-ai/phoenix/assets/80478925/17fc01c6-00e5-4a8c-acff-2497c8c6122e
