### ISSUE TITLE
[ENHANCEMENT] Ability to add points to a selection

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#702]
**Is your feature request related to a problem? Please describe.**

_When using the Select tool. Is it possible to add selections to an already selected list?
For example, what if I wanted to compare two clusters by looking at their inputs_

**Comment by sweenke4** [comment]
@axiomofjoy I appreciate that that may not be a good example. The use of the Lasso makes for good selection in 2D, but not ideal for selecting everything that may be desired in 3D. (what if we wanted to select points along two different planes at the same time?) 

Something of an ideal solution in my line of work would be to be able to use Lasso and move functionality multiple times to keep adding points to the current selection. 
The ability to deselect would be an added bonus!
