### ISSUE TITLE
[ENHANCEMENT] Cross-platform support for npm scripts

### ISSUE THREAD

**Issue by pbadhe** [Arize-ai/phoenix#732]
**Is your feature request related to a problem? Please describe.**
When Windows developers execute `hatch build`, [app/package.json ](https://github.com/pbadhe/phoenix/blob/main/app/package.json) scripts namely "prebuild" and "build:static" throw an error saying "rm is not recognized", "cp is not recognized" which makes sense as the scripts are meant for UNIX systems. According to @axiomofjoy, it would be great in the long term if cross-platform support is added for these scripts.

**Describe the solution you'd like**
Separate scripts for different platforms can be specified. For example, a tool named [run-script-os](https://www.npmjs.com/package/run-script-os) can be used. Its usage is better explained in this StackOverflow [answer](https://stackoverflow.com/a/45464858).

**Describe alternatives you've considered**
Currently, I am using Windows Subsystem for Linux ([WSL](https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R)) which allows `rm`,`cp` and other Unix utilities to be executed in Windows Command Prompt to make the scripts work. For example, I am prepending "wsl" as `"prebuild": "wsl rm -rf ../src/phoenix/server/static"` in app/package.json.

**Comment by axiomofjoy** [comment]
@pbadhe Thanks for the feedback.

**Comment by axiomofjoy** [comment]
run-script-os looks like an interesting option

**Comment by mikeldking** [comment]
Typically I've used https://www.npmjs.com/package/rimraf for this. PRs are welcome!
