### ISSUE TITLE
[dogfooding] dimension details

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#742]
roadmap PRD: #661 

Things to test:
- [x] feature parity with dimension details in platform
- [x] drift detection and troubleshooting causality
- [x] data quality issues - notably new cardinality, percent empty
- [x] single-dataset, time series @arizedatngo 
- [x] two datasets, time series @nate-mar 
- [x] single-dataset, no time @jlopatec

**Comment by axiomofjoy** [comment]
https://colab.research.google.com/gist/axiomofjoy/abc5e0452c9f0f1b436fb0d19cfc987a/dogfood.ipynb

For large number of bins, most of the distribution does not appear.

![Screenshot 2023-05-24 at 2 56 40 PM](https://github.com/Arize-ai/phoenix/assets/15664869/700aa09d-29d5-45c8-ae95-86b0f03dbb35)

**Comment by axiomofjoy** [comment]
![Screenshot 2023-05-24 at 2 57 34 PM](https://github.com/Arize-ai/phoenix/assets/15664869/25f1a60c-2417-44bf-90e8-5b5ce3b7f234)

Data with no timestamp has current timestamp reflected in the plot. This is confusing behaviors.

**Comment by axiomofjoy** [comment]
<img width="896" alt="Screenshot 2023-05-24 at 3 01 52 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/f97c449f-8a2b-4d2d-9a32-cb560e35c4c3">

Empty bin should appear on the left or right.

**Comment by axiomofjoy** [comment]
<img width="793" alt="Screenshot 2023-05-24 at 3 04 49 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/ed543c7d-f0af-4c28-b87d-1eb9c3afe0aa">

Tough to tell which percentiles are turned on or off based on light vs. dark. p50 is turned on when it is light and turned off when it is dark, p1 is the reverse. It's tough to tell which

**Comment by arizedatngo** [comment]
Be able to sort ascending or decending (alphabetical or numeric asc/desc)
![image](https://github.com/Arize-ai/phoenix/assets/97070834/b28d53a2-3d5e-45f9-a3d1-b0ab5a49c665)

**Comment by mikeldking** [comment]
-  First time load is slow since the table is not paginated
-  CTA for cells that are clearly bad (percent empty over 1%), 0.1 - 0.25 for PSI
-

**Comment by nate-mar** [comment]
Wasn't that clear what "Click to view detail" was supposed to do on the PSI chart. Was expecting there to be some extra information that showed up that revealed more info about the PSI drift a particular point. Actual behavior seems to be that it adjusts the distributions on the chart below per the selected point, which does makes sense to me. However, it is hard to tell that the distributions are changing depending on the point in time you select. So was still left unsure what clicking was supposed to do.

Also, once I click the point, the text that says click to show more detail still shows, so I'm unsure if I've actually clicked on the correct thing. Also the text uses the info icon, which in other places is used for help text upon hover, but in this case I can't hover over it.

<img width="1021" alt="Screenshot 2023-05-24 at 3 20 09 PM" src="https://github.com/Arize-ai/phoenix/assets/67926244/4f633049-8f78-45a8-a4f6-f0723885b9eb">

**Comment by mikeldking** [comment]
Thanks for the feedback! All comments have been converted to issues.
