### ISSUE TITLE
Anyscale meetup prep

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#748]
We need to tell an interesting story at the meetup on. The workshop is interactive.

Anyscale will present LLM fine-tuning using Ray.

- [x] Extablish communication with event coordinators and Anyscale Ray
- [ ] Notebook creation related to LLM fine-tuning (dalle using alpaca dataset) - instruction following use-case
- [ ] Coordinate day of coordination @tammy37

**Comment by tammy37** [comment]
Event registration page w/workshop details that Xander and Kamil from Anyscale team worked out: https://lu.ma/arize-anyscale-workshop

**Comment by mikeldking** [comment]
progress update: 
- code for extracting embedding is done.
- running LLM assisted evals
Next steps:
- get more data points
- clean up the notebook

**Comment by mikeldking** [comment]
progress update:
- switch to dolly
- compare to pre-fine-tuned model
- working on denser point-cloud

**Comment by mikeldking** [comment]
Completed
