### ISSUE TITLE
Use-case 6: Insights to Finetune Your LLMs/Prompt Engineering P0

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#756]
What responses are getting bad scores? Where should you fine tune for better responses?

**Comment by jlopatec** [comment]
1) We need to modify this T5 notebook. The data we run through in Load DF prompt & response (my own data), it needs to be the same Alpaca data we are going to fine tune with. 
- Swap out Load DF with Alpaca 
2) Review Results !! 
3) Run same notebook on post fine tune T5, with same Alpaca dataset
4) Generate prompt and responses similar to Alpaca using GPT (* if we have time)
https://colab.research.google.com/drive/1MAilqSjVaPUfGtgtBOvheLUtlO-p9cEc?usp=sharing

**Comment by mikeldking** [comment]
related to #748

**Comment by mikeldking** [comment]
@axiomofjoy can we get the anyscale notebook in a mergable state for this? moving to next sprint

**Comment by axiomofjoy** [comment]
I am not sure we got a good story out of this one. I need to check in with Jason.

**Comment by mikeldking** [comment]
@jlopatec still a priority?
