### ISSUE TITLE
[BUG] embeddings view crashing

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#801]
**Describe the bug**
Application crashes when I navigate to embeddings page. Looks like the error occurs on call to `scipy.linalg.eigh`.

```
Error fetching GraphQL query 'EmbeddingUMAPQuery' with variables '{"id":"RW1iZWRkaW5nRGltZW5zaW9uOjE=","timeRange":{"start":"2023-05-29T00:00:00.000Z","end":"2023-05-31T00:00:00.000Z"},"minDist":0,"nNeighbors":30,"nSamples":500,"minClusterSize":10,"clusterMinSamples":1,"clusterSelectionEpsilon":0}': [{"message":"Cannot use scipy.linalg.eigh for sparse A with k >= N. Use scipy.linalg.eigh(A.toarray()) or reduce k.","locations":[{"line":14,"column":7}],"path":["embedding","UMAPPoints"]}]
```

**To Reproduce**
Run notebook to launch Phoenix, navigate to embeddings page

**Expected behavior**
I expect Phoenix to launch without error.

**Screenshots**
<img width="546" alt="Screenshot 2023-05-30 at 4 08 32 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/9e383181-7cf6-4a9b-835e-6816c7413b99">

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Colab
 - Browser: Chrome
 - Version: 

**Additional context**
[Colab](https://gist.github.com/axiomofjoy/d5f38b7da830f4cbdb473a554b7af9e2)

**Comment by RogerHYang** [comment]
> can't use spectral initialisation (init='spectral', the default) when n_components is greater or equal to the number of samples

see [comment](https://github.com/lmcinnes/umap/issues/201#issuecomment-462097103)
