### ISSUE TITLE
i can't find the host setting, the host defaut is 127.0.0,but if i use it in my server machine,i can'open it.

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#811]
### Discussed in https://github.com/Arize-ai/phoenix/discussions/776

<div type='discussions-op-text'>

<sup>Originally posted by **xuyunlong123** May 24, 2023</sup>

</div>

**Comment by mikeldking** [comment]
One option is SSH? https://docs.anaconda.com/free/anaconda/jupyter-notebooks/remote-jupyter-notebook/

**Comment by mikeldking** [comment]
Dogfood ngrok? https://ngrok.com/docs/secure-tunnels/tunnels/

**Comment by RogerHYang** [comment]
@pbadhe is working on this

**Comment by Apoorva14396** [comment]
Facing same issue want to run phoenix launched app to another host
