### ISSUE TITLE
search by text content

### ISSUE THREAD

**Issue by tmc** [Arize-ai/phoenix#814]
Maybe I'm missing it but is there a way to find/filter based on text data?

**Comment by mikeldking** [comment]
Good idea! We've been thinking of search using a few different heuristics. If you have any specifics of what you are searching for please let us know!

**Comment by lit-in** [comment]
Exact match on a tag or ID works for me, as i already know the details of the records where the generation is sub-par(from user feedback) and would like to debug the reason, by checking the retrieved documents, context etc.
It would be great if the search input could support a list of queries, so multiple IDs/tags can be analysed together

**Comment by mikeldking** [comment]
bumping in priority
