### ISSUE TITLE
[BUG] newline characters are stripped from tags in the UI

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#823]
**Describe the bug**
Newline characters are stripped from tags in the UI. This makes it difficult to read tags that are multi-paragraph.

<img width="1715" alt="Screenshot 2023-06-06 at 12 46 52 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/46e734b9-2cb9-4cbf-90e7-e132f5e04749">

**To Reproduce**
Run the [LlamaIndex example notebook](https://colab.research.google.com/github/Arize-ai/phoenix/blob/llama-index/tutorials/llama_index_knowledge_base_tutorial.ipynb). Check out the "retrieved_context" tag (screenshot above).

**Expected behavior**
I expect new lines to be formatted in the UI so I can easily read multi-paragraph text.

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Jupyter/ VSCode
 - Browser: Chrome
 - Version: branch `llama-index` commit `3169041`

**Comment by mikeldking** [comment]
Won't fix
