### ISSUE TITLE
[BUG] phoenix fails to launch due to invalid time value error

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#841]
**Describe the bug**

Phoenix launches and I see this error:

<img width="713" alt="Screenshot 2023-06-09 at 11 25 24 AM" src="https://github.com/Arize-ai/phoenix/assets/15664869/76ae6f1f-72a7-4d6d-b385-8e07f13a3595">

I see this warning when launching Phoenix, may be related.
```
/usr/local/lib/python3.10/dist-packages/phoenix/datasets/dataset.py:412: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  timestamp_column = Series([default_timestamp] * len(dataframe), index=dataframe.index)
/usr/local/lib/python3.10/dist-packages/phoenix/datasets/dataset.py:412: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  timestamp_column = Series([default_timestamp] * len(dataframe), index=dataframe.index)
```

**To Reproduce**
Run this notebook, launch phoenix, try to view in the UI.

[llama_index_knowledge_base_tutorial.ipynb.zip](https://github.com/Arize-ai/phoenix/files/11709139/llama_index_knowledge_base_tutorial.ipynb.zip)

**Environment (please complete the following information):**
 - OS: Linux
 - Notebook Runtime: Colab
 - Browser: Chrome
 - Version: 0.0.23

**Comment by RogerHYang** [comment]
can't run the notebook: it keeps crashing on the `get_retrieval_data` step when running either locally and on colab
