### ISSUE TITLE
[ENHANCEMENT] custom metrics should not be called data quality metrics

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#848]
**Is your feature request related to a problem? Please describe.**
We currently assume all metrics from the dataframe are "data quality" metrics, which is not the case.

<img width="270" alt="Screenshot 2023-06-12 at 1 15 21 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/634085a2-1d27-4f63-aabe-620218cd4a1f">

**Describe the solution you'd like**
Make a section called "Custom Metrics" or "Dataframe Metrics"

**Comment by mikeldking** [comment]
punt
