### ISSUE TITLE
[ENHANCEMENT] support responses without requiring an embedding

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#851]
**Is your feature request related to a problem? Please describe.**
Sometimes a user wants to add the response to a prompt on the `response_column_names` field just to be able to see the text. We currently require that the user creates embeddings for the response, but this seems unnecessary.

```@dataclass(frozen=True)
class EmbeddingColumnNames(Dict[str, Any]):
    vector_column_name: str
    raw_data_column_name: Optional[str] = None
    link_to_data_column_name: Optional[str] = None
```

**Describe the solution you'd like**
One solution would be to make the `vector_column_name` field on `EmbeddingColumnNames` optional, although that would add complications when the value is used with `embedding_column_names`.

**Comment by mikeldking** [comment]
I believe this is high priority due to the fact that responses in particular never get embedded, we need to relax the schema to support simple text for query and response.
