### ISSUE TITLE
[ENHANCEMENT] support IP allow list for Phoenix server connections

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#920]
**Is your feature request related to a problem? Please describe.**
Users want to run Phoenix in a script on a server and access the UI remotely. We currently require the user to set up SSH on the remote server, or use something like `ngrok`. Some users want the easier but less secure option of running the app with an IP allow list.

**Describe the solution you'd like**
A few solutions are possible:
- add a `forwarded_allow_ips` argument defaulting to localhost to `phoenix.launch_app`, akin to the `--ip` flag you can use when running Jupyter from the command line
- alternatively, don't add this flag, but instead add documentation around how to use the `FORWARDED_ALLOW_IPS` environment variable, clearly noting that this results in an unencrypted connection and exposure to the internet

**Additional context**
<img width="1295" alt="Screenshot 2023-07-12 at 5 34 24 PM" src="https://github.com/Arize-ai/phoenix/assets/15664869/78299441-4bfa-4434-a74e-ddb0cd219752">

**Comment by labdmitriy** [comment]
Hi @axiomofjoy ,

I tried environment variable you mentioned above and it is not working for me.
According to the documentation of Uvicorn, it seems that we need to configure [--host](https://www.uvicorn.org/settings/#:~:text=%2D%2Dhost%20%3Cstr%3E%20%2D%20Bind%20socket%20to%20this%20host.%20Use%20%2D%2Dhost%200.0.0.0%20to%20make%20the%20application%20available%20on%20your%20local%20network.%20IPv6%20addresses%20are%20supported%2C%20for%20example%3A%20%2D%2Dhost%20%27%3A%3A%27.%20Default%3A%20%27127.0.0.1%27.) parameter, not [--forwarded-allow-ips](https://www.uvicorn.org/settings/#:~:text=%2D%2Dforwarded%2Dallow%2Dips%20Comma%20separated%20list%20of%20IPs%20to%20trust%20with%20proxy%20headers.%20Defaults%20to%20the%20%24FORWARDED_ALLOW_IPS%20environment%20variable%20if%20available%2C%20or%20%27127.0.0.1%27.%20A%20wildcard%20%27*%27%20means%20always%20trust.).

Thank you.

**Comment by labdmitriy** [comment]
Hi @axiomofjoy,

Could you please tell are there any plans to edit the code which I mentioned earlier or provide your own solution to it?

Thank you.

**Comment by axiomofjoy** [comment]
@labdmitriy It looks like I missed your previous message, my apologies and thanks for following up on this.

We added a `host` parameter to `phoenix.launch_app` a couple weeks ago: https://github.com/Arize-ai/phoenix/pull/1290

It should be available in the current release. Let us know if that works for you.

**Comment by axiomofjoy** [comment]
Closing this issue since `host` is the appropriate parameter.
