### ISSUE TITLE
[BUG] Phoenix Image Classification in Colab

### ISSUE THREAD

**Issue by ADoug4** [Arize-ai/phoenix#940]
**Describe the bug**
Phoenix App crashes when viewing image embeddings. Appears related to a type mismatch between float64 and integer for the locations (UMAPPoinnts embedding).

**To Reproduce**
1. Run notebook through [17] session = px.launch_app(primary=prod_ds, reference=train_ds)
2. View Phoenix App in browser or notebook
3. Click image embedding
4. Wait about 15 seconds
5. See error below

Error fetching GraphQL query 'EmbeddingUMAPQuery' with variables '{"id":"RW1iZWRkaW5nRGltZW5zaW9uOjA=","timeRange":{"start":"2022-08-03T21:00:00.000Z","end":"2022-08-05T21:00:00.000Z"},"minDist":0,"nNeighbors":30,"nSamples":500,"minClusterSize":10,"clusterMinSamples":1,"clusterSelectionEpsilon":0,"fetchDataQualityMetric":false,"fetchPerformanceMetric":false,"dataQualityMetricColumnName":null,"performanceMetric":"accuracyScore"}': [{"message":"'numpy.float64' object cannot be interpreted as an integer","locations":[{"line":18,"column":7}],"path":["embedding","UMAPPoints"]}]

**Expected behavior**
Display Euclidean distance chart and cluster for clicked timestamp.

**Screenshots**
<img width="521" alt="image" src="https://github.com/Arize-ai/phoenix/assets/37676417/474f06a3-1a5f-495e-8553-28ffac592465">

**Environment (please complete the following information):**
 - OS: [Windows 11 22H2 22621.1992]
 - Notebook Runtime [Colab]
 - Browser [Chrome]

**Additional context**
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/image_classification_tutorial.ipynb

**Comment by mikeldking** [comment]
hey @ADoug4 sorry you are hitting this - this is actually a runtime exception in HDBSCAN that we are tracking via #937 - the ticket contains a work around for now but we hope to have a fix out via sklearn HDBSCAN very soon!

**Comment by mikeldking** [comment]
Should work if you install HDBSCAN via github before the phoenix install

```
pip install git+https://github.com/scikit-learn-contrib/hdbscan.git
```

**Comment by ADoug4** [comment]
That worked, thank you!

Have a great day,
Aaron
